### ISSUE TITLE
Feature Request/Question: Is there a way to create a playlist from the favorites list in one click? 

### ISSUE THREAD

**Issue by kdebro** [clsid2/mpc-hc#1033]
I am looking for a feature that will allow me to save my favorites list as a MPC playlist in one action. What I'm doing now is opening each file separately and adding it to a list. An option to save the entire favorites list as a playlist will save so much time!

**Comment by butterw** [comment]
In portable mode, Favorites are in stored in mpc-hc64.ini under [Favorites\Files].

**Comment by emich-kyle** [comment]
thanks for the comment. investigating further, Favorites are in a registry key located here: [HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Favorites\Files]

I wish I could patch it for everyone but I don't know C++ yet 😁 my solution was to export the .reg (located above), filter just the filepaths, and then save it as a .m3u list. basically, convert the .reg to .m3u 

It seems like such an easy feature for someone to add who is smarter than me. hopefully this might help everyone else, but so far I've got it going for myself--converting to .m3u is the easiest way because it is just a list of directories. .m3u type requires no particular formatting like the .mpcpl, .pls, and .asx types do

take care!

**Comment by kdebro** [comment]
thanks for the comment. investigating further, Favorites are in a registry key located here: [HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC\Favorites\Files]

I wish I could patch it for everyone but I don't know C++ yet 😁 my solution was to export the .reg (located above), filter just the filepaths, and then save it as a .m3u list. basically, convert the .reg to .m3u

It seems like such an easy feature for someone to add who is smarter than me. hopefully this might help everyone else, but so far I've got it going for myself--converting to .m3u is the easiest way because it is just a list of directories. .m3u type requires no particular formatting like the .mpcpl, .pls, and .asx types do

take care!
