### ISSUE TITLE
8-Bit FLAC Playback Skips Silent Portions

### ISSUE THREAD

**Issue by nikku4211** [clsid2/mpc-hc#1105]
I've been playing 8-bit FLACs in MPC-HC, and for some reason, the silent portions are completely skipped over in MPC-HC. This is not a problem with the FLACs themselves, as I used to think, as I've had Saga Musix test for me, and the FLACs sounded just fine to him.

Apparently, this is an FFMPEG-related bug.

**Comment by clsid2** [comment]
That is not a FLAC file, but a .mod file (Tracker audio).

**Comment by nikku4211** [comment]
I accidentally included the wrong file and forgot about this issue, here's the actual FLAC.

[MPTRenderTest.zip](https://github.com/clsid2/mpc-hc/files/6565306/MPTRenderTest.zip)

**Comment by clsid2** [comment]
The internal codecs are developed as a separate project. You can report issues here:
https://github.com/Nevcairiel/LAVFilters/issues

If the problem also occurs with FFmpeg, then it is better to report it directly to them:
http://trac.ffmpeg.org/query?status=new&status=open&status=reopened&col=id&col=summary&col=status&col=type&col=component&col=version&col=time&col=changetime&report=1&desc=1&order=changetime

LAV Filters uses FFmpeg, so any issues fixed in FFmpeg will automatically find their way into LAV updates.

**Comment by nikku4211** [comment]
[Okay, I filed a bug report to FFMPEG.](http://trac.ffmpeg.org/ticket/9270)
