### ISSUE TITLE
Can add option to add others Subtitle providers?

### ISSUE THREAD

**Issue by richenberg** [clsid2/mpc-hc#1129]
Hello!
Can add option to add others Subtitle providers?
i want to add a brazilian subtitle provider like "http://legendas.tv/" and "https://legendei.to/"

**Comment by clsid2** [comment]
A subtitle website is not the same as a subtitle provider. A subtitle provider needs to provide a programming API for searching and downloading subtitles. Those websites and many other subtitle websites do not provide that functionality.

So they can't be added. Same answer applies to other websites as well.

**Comment by ale5000-git** [comment]
@richenberg: You tecnically can directly parse xml and html pages to get the same thing, but the parser should be updated every time the site change.

@clsid2: It could be interesting (but low priority) to create an interface in MPC-HC to use an external python script for getting subtitles (like youtube-dl) passing to it language, hash and filename.
It should be likely external since it would require prompt updates.
It could support an infinite number of websites.

**Comment by clsid2** [comment]
I am not interested in adding **any** new functionality.

You can make your own tool to download subtitles before even starting playback. The hash algorithm is open source.
