### ISSUE TITLE
Add ability to change default installation folder

### ISSUE THREAD

**Issue by anmolbyte** [clsid2/mpc-hc#1192]
Is there any way to change the installation folder for the windows .exe file?  The default installation location is c:/program files, which isn't where I have my installation, since mpc-hc needs to be in a location it can write files to store settings as an .ini file.

**Comment by clsid2** [comment]
You can choose location on the initial installation. Re-install if you want to change it.

Using INI is totally unnecessary in most cases. If your reason is "easy backup" then that is also possible when storing settings in the registry. In fact, the player even has an option for exporting the current settings:
Options > Miscellaneous > Export
