### ISSUE TITLE
Old regression regarding buttons using 32-bit toolbar bmp

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#12]
Back in 2016 I reported this in a commit: https://github.com/mpc-hc/mpc-hc/commit/3058daadd28ea456076a03d9c11622ffbdc09e35#comments but it went to the void and was never fixed. @clsid2 if you could take a look I'll give many thanks. Thank you.

PS: What does this commit from kasper93 do? https://github.com/kasper93/mpc-hc/commit/185bd36e6cba5512c4d6fd95cf05ba135582d0e8

**Comment by clsid2** [comment]
The problem is that for most toolbars the disabled buttons look the same as the enabled ones if the current behavior is reverted. And I am not very keen on adding another option. Hiding disabled buttons may be an alternative.

That other patch is to prevent accidental clicks on the video just above the seekbar.

**Comment by clsid2** [comment]
Detecting if it has 'proper' data in the alpha channel might be possible too.

How did you make your modified toolbar?

**Comment by Rikk** [comment]
I remember I got one image from https://trac.mpc-hc.org/wiki/Toolbar_images and used Photoshop to modify adding colors. It uses Alpha channel for delimiting buttons as recommended in that page for 32bit bmp. I still dunno what was wrong and which this commit tried to fix.

**Comment by adipose** [comment]
So, I made a really simple fix that should handle this situation.  If you name your toolbar color_toolbar.bmp, it will assume it doesn't need to create its own grayscale image and use the built-in capabilities.  Otherwise, it grays the image normally. This should isolate the fix to anyone who feels secure enough to name it color_toolbar. :)

See:

https://github.com/clsid2/mpc-hc/pull/166

**Comment by clsid2** [comment]
Patch has been committed.

**Comment by Rikk** [comment]
@adipose Works great, thank you!
