### ISSUE TITLE
Automatic video and audio files association

### ISSUE THREAD

**Issue by NightPurrer** [clsid2/mpc-hc#1253]
It will speeds up the configuration process.

**Comment by clsid2** [comment]
Install it through K-lite Standard if you want automatic configuration and file associations.

**Comment by NightPurrer** [comment]
But why can't this be added to the installer? Some people don't use KLite.

**Comment by camjac251** [comment]
Windows 11 has made it incredibly tedious to set defaults now since they removed the Default Audio/Video Player option altogether. I tried the file association option in the settings but unfortunately, it didn't work. Adobe programs are able to set defaults, Teracopy is able to set defaults too. It might be some new way since Windows 11 is much more frustrating now with this. I just wish they had a set all file types function right here
![image](https://user-images.githubusercontent.com/6313132/150670466-533655b5-d277-4d2f-b9ef-b1cc2151305b.png)
