### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by burakhanay** [clsid2/mpc-hc#1258]
Can u coding this program for Linux? Many Linux users are tired of using VLC.

**Comment by clsid2** [comment]
No.

**Comment by mysuf** [comment]
@clsid2 LoL. Actually it's pretty good question and it deserves broader answer. Linux media players are horrible and VLC is no exception. I'm still facing some issues with Ubuntu VLC - from delays when seeking to intermittent sound when changing subtitles(wtf), etc..

Can you atleast elaborate what it would require to make it cross-platform? Did you plan to make it cross-platform (because it affects whole sw design) when you started with MPC-HC?

Honestly I'm happy that you continue with support. I thought that this project is dead.

**Comment by xLn2** [comment]
[Mpc-qt](https://github.com/mpc-qt/mpc-qt) project might be what you are looking for. 

> Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc while using [libmpv](https://github.com/mpv-player/mpv) to play video instead of DirectShow.

**Comment by mysuf** [comment]
@xLn2 Thank you for tip. It looks good. I removed my comment because later I found out that this repo is a fork of original repository so my points've became irrelevant.
