### ISSUE TITLE
option to align video to top in fullscreen

### ISSUE THREAD

**Issue by adigourdi** [clsid2/mpc-hc#126]
Wide videos (movies) in fullscreen show black bars on top and bottom

Now subtitles in the bottom show half over the black bar and top half over the video

So I always move the video up using Ctrl+NumKey8

* subtitles are clear over the black section in the bottom
* video is better aligned with my eyes (on the laptop at least)

An option to do that automatically would be great, maybe called:
**Fullscreen video alignment/location/position/...**

I suggest putting it in Player > Before Language section
A combo box showing Top, Middle, and Bottom (Middle being the default value)
Both section "Open options" and "Title Bar" can be smaller to make space for the new section

What do you think?

**Comment by clsid2** [comment]
I am not adding new functionality like this. Someone else will have to implement it.

**Comment by adipose** [comment]
After messing around with subs I think this could be tricky.  For example, the Gravity cropped example clsid2 provided, we added functionality to make it fit with letterbox and without.  But that example has top located subs and bottom ones as well.

If we assume the subs should be left alone, and the video should be relocated only, it might be simpler.  But in the case of Gravity, you might get something like the below.  Note the result is one set of subs right on the video frame, and the bottom subs far below.

So we would need a few sets of rules for this to act sane for all the videos.  If the sub aspect ratio matches the video (non-cropped), making the subs offset from the bottom of a full-screen window instead of the top of the video frame might work.

```
centered:
===========================================  <----window frame
|                                         |
|           Top Subtitles                 |
|                                         |
-------------------------------------------  <----video frame
|                                         |
|                                         |
|                                         |
|                                         |
|                                         |
-------------------------------------------  <----video frame
|                                         |
|           Bottom Subtitles              |
|                                         |
===========================================  <----window frame

Top aligned:
===========================================  <----window&video frame
|                                         |
|           Top Subtitles                 |
|                                         |
|                                         |
|                                         |
-------------------------------------------  <----end video frame
|                                         |
|                                         |
|                                         |
|                                         |
|                                         |
|           Bottom Subtitles              |
|                                         |
===========================================  <----window frame
```

**Comment by adigourdi** [comment]
Thanks for working on this man, as I couldn't figure out where to start

I guess subtitles should be left alone, and only the video relocated

If the video is aligned to top, and occupies 80% of the window height with subtitles over at 20%, they would be drawn over the video, which would be the same current behavior, and thus an acceptable compromise

Also, I'm not sure what you mean by the "Gravity" concept, would you care to elaborate ?

**Comment by adipose** [comment]
It was a sample video of the 'Gravity' movie, which is cropped but also has subs intended for the letterbox areas.

https://www.sendspace.com/file/ffv00x

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/issues/134

Test build for pgs subs: 
https://mega.nz/#!AUhEjIYL!jE2rUaA3ry-4r_hgtNyEp9j55kh3_JggRaIALirfO3s

I just thought of something. In the current release there is a bug with subtitles not being placed correctly. The concern was related to the aspect ratio, but I also observed the location was not what the source video intended. The build above has the fix for subtitle rendering, including when the video has been cropped. Maybe it will make your subs show up in the black area more frequently.

Not to dismiss the original request, of course. But it might help.

**Comment by adigourdi** [comment]
I did try the build you provided, and couldn't actually notice a difference on my 16:9 screen

Also on my home install, I have the subs with a larger font for the TV

Is there no way to just simulate the Ctrl+Numpad8 ? on the sample Gravity video provided, the subtitles don't actually change their location when the video moves

**Comment by adipose** [comment]
I have an outstanding PR doing what you want.  Try this build:

https://mega.nz/#!JRhUlQpJ!YOx60GLrJkIlUU_nkvIFM3tZh0GsARtMCqk2iDgnav8

![image](https://user-images.githubusercontent.com/3324395/70942276-25d61800-2003-11ea-8585-d04aec7e2211.png)

**Comment by adigourdi** [comment]
Can confirm it's working, thanks

Hitting Numpad5 to reset the positioning respects the selected alignment

Now I have to hit Numpad5 or reopen the file (Ctrl+E), maybe you might wanna set the video to the selected alignment on apply, but only if the value actually changed? not a requirement though

Thanks again

**Comment by adipose** [comment]
If you change it mid-video it doesn't reload it until next play.  Probably not worth fixing that if you have a permanent preference, otherwise you can just hit stop and restart.

Num5 goes back to "zero" offset, so yes it does respect the current alignment.  The align is independent of the panscan offset.  I could possibly make it move to the correct "center" offset, but I don't really see much point.

If really desired, the most useful thing would be new hotkeys to align top, middle, bottom respecting the new settings.

**Comment by adigourdi** [comment]
agreed, no need for new shortcuts though, not something to change multiple times during play, maybe for testing purposes initially
