### ISSUE TITLE
[Request] Auto-select audio and subtitles

### ISSUE THREAD

**Issue by enerjazzer** [clsid2/mpc-hc#1284]
When watching a series of similar videos, all having multiple audio tracks and subtitles, it would be good for MPC-HC to remember the choices and when switching to the next video with PgDn, select the same (or the closest) automatically.
Things to remember are: 
* audio track language (or the closest name if the language info is not available)
* subtitles turned on/off, if on - what language (can be different from the audio), speech only or closed captioning
For both, if the metadata (language, CC) is not available, match by name closest to the currently selected (e.g. by editing distance).

**Comment by ArcticGems** [comment]
So the settings in these two are not enough? =

`Options->Playback->Default track preference`
`Options->Internal Filters->Internal LAV Filters settings->Splitter`

If language definition is not available, it will be seen as undefined by MPC-HC (or by any program).

I guess you could correct spelling (if encoder misspelled with free-form input), but they are all so similar so it would be hard (maybe?).

**Comment by clsid2** [comment]
You can use the options in the splitter to configure it so that it uses the correct one by default.

I do not have plans for any additional options.

**Comment by enerjazzer** [comment]
Let me give an example. 
When I'm watching Japanese series, I want Japanese audio and Russian subtitles, but when I'm watching English series, I want them both in English. 
The easiest would be to select audio&subtitles when I play the first video (if the default ones from the options mentioned above were not what I wanted for this particular session) and then all others will retain the selection automatically.
The default ones from the Settings work when I open MPC-HC for the first time, but since I changed the selection it would take precedence for all next videos (at least for those opened with PgUp/PgDn) until the next MPC-HC restart.
That's the desirable behavior: this way I only need to select audio & subtitles once per session without going to Options.
I believe that's the most intuitive for users.

A workable (but less desirable) solution would be a command like "Remember Audio & Subtitles" that would set the options mentioned above from the currently selected languages - still less hassle that either going every time to several places in the settings or to manually change audio & subtitles on every video.

**Comment by clsid2** [comment]
I have already said that I am not going to add any new options.

In the splitter settings you can configure which subtitle language is preferred for an audio language. So that part is already possible!

**Comment by DaiMaouCC** [comment]
Very unprofessional and rude way of dealing with a request, even if you're lazy and don't want to add things that make it easier for the user, you can't just say "I don't want to add it! I already said that I won't add anything!" like you're bossing the user around just for making a request, and closing the request without asking the user for further question or confirming that the user is finished?! instead of saying "thank you for the request, for now there's no plans in making a new option, but we'll take this into consideration, is there any thing else we can help with?" and wait for them to confirm is they're finished with this request or if they have anything else to add to it, instead of closing it

**Comment by kkdexz** [comment]
@enerjazzer https://1f0.de/lav-splitter/lav-splitter-stream-selection/

Not sure if this will help you out, but think it might. The audio/subtitle selection is actually quite customizable. Should be better than what you're doing now. If you weren't aware of and haven't tried this already, that is; which it sounds like.

These options are in the LAV splitter settings btw:

Options -> Internal Filters -> Internal LAV Filters settings -> Splitter
         OR
[When media is playing]
Menu (Right-click) -> Filters -> LAV Splitter Source (Internal) -> Properties

-> Subtitle Selection Mode => Advanced


Edit: Just noticed how old this issue is. You probably figured this out by now.

**Comment by mpek** [comment]
Suggestion for a better usabilty of subtitle settings: 
It would be nice if subtitle splitter settings where available at subtitle settings, i looked for the preferred language feature, but have to find this thread to be able to set it.

**Comment by dbregman** [comment]
Found this issue via google so I'm posting my solution here for anyone else who follows the same path: PotPlayer supports this feature and it just works. Just pick your audio and subs and it gets remembered to every subsequent episode in the playlist.

btw, weird to see this marked as "completed". Maybe the authors don't have much experience with anime because the splitter settings are not a good alternative to this feature. There are all kinds of cases where it doesn't do what you want. The user's preference will not always be a pure function of some data in the video file. Also, the splitter settings thing is truly horrible UX that is barely even usable by power users. By the time you are reading a frigging 1000 word readme on the syntax of the expressions for the advanced selection mode, you already lost because it is way faster to just select the subs and audio manually for every single video.
