### ISSUE TITLE
[Request] Load subtitles that are not named as the movie file itself

### ISSUE THREAD

**Issue by gthbububba** [clsid2/mpc-hc#1288]
Any chance to load subtitles (from a subfolder) that have a different name than the file itselt?
Let's say you torrent a movie but the subs are always called "20_English.srt" instead of "movie.2021.1080p.BlueRay.x265-RaRxx.mp4.srt"

In that case mpc-hc simply does ignore the subs.

A simple solution would be to look for all subtitles in the same folder (and subfolder) the movie is loaded from or allow that option.

Would be very convenient.

Edit:Typo

**Comment by clsid2** [comment]
You can just drag&drop a subtitle file onto the video to load it.

**Comment by gthbububba** [comment]
Ok fine thanks. Your suggestion works but it would still be better if mpc-hc would just simply automatically (or better via optin) load any subtitle regardless of the name. This way you could also preview a movie while torrenting.

All options here: load subtitle from menu (Ctrl+L), drag&drop but not the most simple solution to just load any subtitle in the same folder...

Would this be hard to implement?

**Comment by clsid2** [comment]
That will never be implemented because it is a terrible idea.

There can be hundreds of different video and subtitle files in the same folder.

**Comment by ANaPhOrAX** [comment]
> That will never be implemented because it is a terrible idea.
> 
> There can be hundreds of different video and subtitle files in the same folder.

Actually, it's not a terrible idea at all. Potplayer i.e. has this, and it works wonderfully. They have it as "load any subs in folder if none match", which would honestly be a godsend (and would as such also not cause an issue in the situation you're describing (which btw - increasingly rare, since a lot of rips nowadays have softcoded subtitles, instead of separate SRT etc. files)).

For the past couple hours I've been trying to solve this specific annoyance: A lot of torrents will have subtitles in a subfolder called i.e. "Subs". Now, potplayer for some reason doesn't scan subdirectories for subtitles, and you can't even add those as like ".\Subs" either (sigh), and mpc-hc _can_ scan subdirectories, but doesn't have the option to load any subtitle files if none match the filename of the media file... sheesh. Yes, I can go into the subfolder and drag the subtitle file onto mpc.. _but I shouldn't have to_. This is honestly so silly. I was even looking at a batch script that would rename and move the SRT file from the Subs subfolder into the main folder and delete the Subs subfolder.. but that one broke as soon as the Subs folder contained more than 1 SRT file. Sigh. Please reconsider implementing this.

**Comment by clsid2** [comment]
Complain to the idiots that made the torrent.

**Comment by ANaPhOrAX** [comment]
Buy a mirror.
