### ISSUE TITLE
Subtitle bug about Emoji

### ISSUE THREAD

**Issue by k9fvm** [clsid2/mpc-hc#1368]
I used a simple Chinese character "七" (seven , 7) to show the bug.
Load the subtitle.srt file with any video.

The test subtitle.srt file :

1
00:00:01,000 --> 00:00:02,500
aa (ok)

2
00:00:03,000 --> 00:00:04,500
bb七七七七七 (English & Chinese , good)

3
00:00:05,000 --> 00:00:06,500
cc七七七七七 (both good , again)

4
00:00:07,000 --> 00:00:08,500
dd😁 (Start wrong , Not support Emoji ?)

5
00:00:09,000 --> 00:00:10,500
ee七七七七七 (Chinese , wrong ! This is the bug !)

6
00:00:11,000 --> 00:00:12,500
ff end (English , good)

**Comment by adipose** [comment]
Reproduced.

**Comment by adipose** [comment]
Caused by this.  If the number of bytes is greater than 2, it corrupts the stream.  I updated it to 3 and everything works except rendering the emoji (just shows up as blank).  At a minimum, we should make sure it seeks past the valid sequence.

![image](https://user-images.githubusercontent.com/3324395/139500781-89fcc39d-9378-4253-84b1-a8ac2df71178.png)

**Comment by k9fvm** [comment]
In addition,
As more and more subtitle files contain Emojis, it is hoped that MPC-HC will support Emoji.

**Comment by ale5000-git** [comment]
@adipose:
There can be 4 bytes in a single UTF-8 character, I think it is better to support all of them.

**Comment by ale5000-git** [comment]
Like this: 𒁐

More info here: https://design215.com/toolbox/utf8-4byte-characters.php

**Comment by adipose** [comment]
> @adipose:
> 
> There can be 4 bytes in a single UTF-8 character, I think it is better to support all of them.

Yes, I know. Just showing where the bug is. There are lots of utf8 libs we might want to use instead of decoding ourselves.

**Comment by ale5000-git** [comment]
> 
> 
> > @adipose:
> > There can be 4 bytes in a single UTF-8 character, I think it is better to support all of them.
> 
> Yes, I know. Just showing where the bug is. There are lots of utf8 libs we might want to use instead of decoding ourselves.

But they should be tested with complicate animated subtitles and 4K videos because if they aren't performant they can slow down everything.

**Comment by adipose** [comment]
I need to look closer, but it seems to be a bug introduced by checking the continuation bytes before seeking. The code has a fall through for long sequences, to replace them with '?' symbol. But due to the check for 3 bytes or more, it never even gets there and also fails to seek past the continuation bytes. This corrupts the stream afterwards.

By the way, 3 continuation bytes should mean 4 total bytes, I think.

**Comment by adipose** [comment]
Problem is the invalid char causes it to reopen the file as text.  Thereafter, no UTF-8 chars will be recognized.

Code is 9 years old.  Best guess, it tries to opt out of UTF-8 in case a local encoding could have better results.  Elsewhere in mpc-hc, there are checks for "valid utf-8", which is unlikely to succeed on a local encoding.  If we verify the line of text is valid utf-8, maybe we don't allow it to fallback to text.  Simply giving up because it's a UTF-8 char > 3 bytes makes no sense to me.

`Utf8::isStringValid` was the function.

**Comment by clsid2** [comment]
continuationBytes() always returns value between 0 and 3.

**Comment by adipose** [comment]
> continuationBytes() always returns value between 0 and 3.

Right. 3 continuation = 4 byte encoding.

**Comment by clsid2** [comment]
```
diff --git a/src/Subtitles/TextFile.cpp b/src/Subtitles/TextFile.cpp
index 3290b5d1f..6199f2e18 100644
--- a/src/Subtitles/TextFile.cpp
+++ b/src/Subtitles/TextFile.cpp
@@ -373,34 +373,32 @@ BOOL CTextFile::ReadString(CStringA& str)
                     abuffer[nCharsRead] = m_buffer[m_posInBuffer] & 0x7f;
                 } else if (Utf8::isFirstOfMultibyte(m_buffer[m_posInBuffer])) {
                     int nContinuationBytes = Utf8::continuationBytes(m_buffer[m_posInBuffer]);
-                    bValid = (nContinuationBytes <= 2);
-
-                    // We don't support characters wider than 16 bits
-                    if (bValid) {
-                        if (m_posInBuffer + nContinuationBytes >= m_nInBuffer) {
-                            // If we are at the end of the file, the buffer won't be full
-                            // and we won't be able to read any more continuation bytes.
-                            bValid = (m_nInBuffer == TEXTFILE_BUFFER_SIZE);
-                            break;
-                        } else {
-                            for (int j = 1; j <= nContinuationBytes; j++) {
-                                if (!Utf8::isContinuation(m_buffer[m_posInBuffer + j])) {
-                                    bValid = false;
-                                }
+                    ASSERT(bValid);
+
+                    if (m_posInBuffer + nContinuationBytes >= m_nInBuffer) {
+                        // If we are at the end of the file, the buffer won't be full
+                        // and we won't be able to read any more continuation bytes.
+                        bValid = (m_nInBuffer == TEXTFILE_BUFFER_SIZE);
+                        break;
+                    } else {
+                        for (int j = 1; j <= nContinuationBytes; j++) {
+                            if (!Utf8::isContinuation(m_buffer[m_posInBuffer + j])) {
+                                bValid = false;
                             }
+                        }
 
-                            switch (nContinuationBytes) {
-                                case 0: // 0xxxxxxx
-                                    abuffer[nCharsRead] = m_buffer[m_posInBuffer] & 0x7f;
-                                    break;
-                                case 1: // 110xxxxx 10xxxxxx
-                                case 2: // 1110xxxx 10xxxxxx 10xxxxxx
-                                    // Unsupported for non unicode strings
-                                    abuffer[nCharsRead] = '?';
-                                    break;
-                            }
-                            m_posInBuffer += nContinuationBytes;
+                        switch (nContinuationBytes) {
+                            case 0: // 0xxxxxxx
+                                abuffer[nCharsRead] = m_buffer[m_posInBuffer] & 0x7f;
+                                break;
+                            case 1: // 110xxxxx 10xxxxxx
+                            case 2: // 1110xxxx 10xxxxxx 10xxxxxx
+                            case 3:
+                                // Unsupported for non unicode strings
+                                abuffer[nCharsRead] = '?';
+                                break;
                         }
+                        m_posInBuffer += nContinuationBytes;
                     }
                 } else {
                     bValid = false;
@@ -408,7 +406,7 @@ BOOL CTextFile::ReadString(CStringA& str)
                 }
 
                 if (!bValid) {
-                    abuffer[nCharsRead] = '?';
+                    abuffer[nCsharsRead] = '?';
                     m_posInBuffer++;
                     nCharsRead++;
                     break;
@@ -590,35 +588,36 @@ BOOL CTextFile::ReadString(CStringW& str)
                     m_wbuffer[nCharsRead] = m_buffer[m_posInBuffer] & 0x7f;
                 } else if (Utf8::isFirstOfMultibyte(m_buffer[m_posInBuffer])) {
                     int nContinuationBytes = Utf8::continuationBytes(m_buffer[m_posInBuffer]);
-                    bValid = (nContinuationBytes <= 2);
-
-                    // We don't support characters wider than 16 bits
-                    if (bValid) {
-                        if (m_posInBuffer + nContinuationBytes >= m_nInBuffer) {
-                            // If we are at the end of the file, the buffer won't be full
-                            // and we won't be able to read any more continuation bytes.
-                            bValid = (m_nInBuffer == TEXTFILE_BUFFER_SIZE);
-                            break;
-                        } else {
-                            for (int j = 1; j <= nContinuationBytes; j++) {
-                                if (!Utf8::isContinuation(m_buffer[m_posInBuffer + j])) {
-                                    bValid = false;
-                                }
+                    ASSERT(bValid);
+
+                    if (m_posInBuffer + nContinuationBytes >= m_nInBuffer) {
+                        // If we are at the end of the file, the buffer won't be full
+                        // and we won't be able to read any more continuation bytes.
+                        bValid = (m_nInBuffer == TEXTFILE_BUFFER_SIZE);
+                        break;
+                    } else {
+                        for (int j = 1; j <= nContinuationBytes; j++) {
+                            if (!Utf8::isContinuation(m_buffer[m_posInBuffer + j])) {
+                                bValid = false;
                             }
+                        }
 
-                            switch (nContinuationBytes) {
-                                case 0: // 0xxxxxxx
-                                    m_wbuffer[nCharsRead] = m_buffer[m_posInBuffer] & 0x7f;
-                                    break;
-                                case 1: // 110xxxxx 10xxxxxx
-                                    m_wbuffer[nCharsRead] = (m_buffer[m_posInBuffer] & 0x1f) << 6 | (m_buffer[m_posInBuffer + 1] & 0x3f);
-                                    break;
-                                case 2: // 1110xxxx 10xxxxxx 10xxxxxx
-                                    m_wbuffer[nCharsRead] = (m_buffer[m_posInBuffer] & 0x0f) << 12 | (m_buffer[m_posInBuffer + 1] & 0x3f) << 6 | (m_buffer[m_posInBuffer + 2] & 0x3f);
-                                    break;
-                            }
-                            m_posInBuffer += nContinuationBytes;
+                        switch (nContinuationBytes) {
+                            case 0: // 0xxxxxxx
+                                m_wbuffer[nCharsRead] = m_buffer[m_posInBuffer] & 0x7f;
+                                break;
+                            case 1: // 110xxxxx 10xxxxxx
+                                m_wbuffer[nCharsRead] = (m_buffer[m_posInBuffer] & 0x1f) << 6 | (m_buffer[m_posInBuffer + 1] & 0x3f);
+                                break;
+                            case 2: // 1110xxxx 10xxxxxx 10xxxxxx
+                                m_wbuffer[nCharsRead] = (m_buffer[m_posInBuffer] & 0x0f) << 12 | (m_buffer[m_posInBuffer + 1] & 0x3f) << 6 | (m_buffer[m_posInBuffer + 2] & 0x3f);
+                                break;
+                            case 3:
+                                // We don't support characters wider than 16 bits
+                                m_wbuffer[nCharsRead] = L' ';
+                                break;
                         }
+                        m_posInBuffer += nContinuationBytes;
                     }
                 } else {
                     bValid = false;

```

**Comment by clsid2** [comment]
Fixed. But emojis will not be displayed because they are not supported.

**Comment by adipose** [comment]
One comment.  Where it says "characters wider than 16 bits," it actually means 24 bits.  The code always permitted 3-byte UTF-8.  Maybe by accident, because of confusion about what `nContinuationBytes` actually means.

**Comment by adipose** [comment]
I have submitted a new patch for this.

https://github.com/clsid2/mpc-hc/pull/1376

Instead of manually decoding and trying to push the result into a single wchar, I allow multiple wchar, supporting utf-16 properly.  I used `UTF8ToStringW` which has a similar algorithm, but supports more than the basic multilingual plane for utf-16.

The result was that the emoji does not show up, except as a square.  The Japanese character hokke (U+29E3D) also is not working, but probably due to the font I'm using.

I can add a check to eliminate common emoji blocks, or we could just leave them as a square to indicate an unrecognized character (depending on font).

**Comment by adipose** [comment]
Hmm, I think I'm wrong, that algorithm doesn't handle multiple wchar, either.

**Comment by adipose** [comment]
Patch now supports all utf-16, I believe.  DSUtil routines don't work because they use CStringW, which needs a null terminator, but the single codepoint won't always be null terminated.  Either we could copy to another buffer, decode the entire string at once, or use the method I did of decoding a fixed length with no null terminator.

![image](https://user-images.githubusercontent.com/3324395/139930340-ae4737c4-5ccd-482a-81e4-d22e8b1f45d9.png)

![image](https://user-images.githubusercontent.com/3324395/139930350-0f084922-6e11-4c61-a6d2-d4be4b0e6b7d.png)

![image](https://user-images.githubusercontent.com/3324395/139930365-afdf500c-6308-438e-af01-899973ba103e.png)
