### ISSUE TITLE
[Bugreport] subtitles auto download not working

### ISSUE THREAD

**Issue by hajosattila** [clsid2/mpc-hc#139]
hi,

Automatic download of subtitles isn't working on my languages (hungarian | magyar)
There is no problem with other languages...

It does not list the Hungarian language
![bugrep_1](https://user-images.githubusercontent.com/1567493/66705608-52329700-ed29-11e9-8b12-e36e9b4cf52d.jpg)

It does exist
![bugrep_2](https://user-images.githubusercontent.com/1567493/66705609-52329700-ed29-11e9-8808-6c0651939d91.jpg)

Sorry for my bad English!

**Comment by clsid2** [comment]
The search on OpenSubtitles is done using a file hash. The subtitle that you are finding on the website might not be associated with that specific hash. So that is why it can show less results.

I am not going to change how things work. Someone else will have to submit patches for any enhancements of current functionality.
