### ISSUE TITLE
EVR Gamma Too High Whereas MPC Renderer Lagspikes When Playing Movies

### ISSUE THREAD

**Issue by alienfxfiend** [clsid2/mpc-hc#1431]
I would like to use EVR over Media Player Renderer for playing movies (I've got subtitles for them), but the gamma is too high & so is the contrast\ saturation, why isn't the EVR color settings customizable like the MPC Renderer ? 'Cause the MPC Renderer lagspikes a lot whereas the EVR is blazing fast, but is too bright\ Gamma-high. Please could you make color settings for EVR tweakable ? P.S: I have increased the Gamma\ Color settings via my Intel HD Graphics Control Panel on my Dell laptop, but still MPC Renderer is just right, but lags.

**Comment by clsid2** [comment]
There are color controls for EVR here:
Options > Miscellaneous
If they do not work, you need to disable color overrides in the driver. Applications can't override if driver already does it!

If colors are wrong because you are playing HDR video, then I can disappoint you, because EVR does not support HDR tonemapping.

**Comment by alienfxfiend** [comment]
Yeah it turned out to be due to the Intel Driver Profile via I had overriden (the Video Color Settings.) Thanks for resolving the issue.
