### ISSUE TITLE
Windows 7 Autoplay Defualt

### ISSUE THREAD

**Issue by Sin-Shadow-Fox** [clsid2/mpc-hc#1485]
I'm about 2 seconds away from uninstalling this thing. Why is it when i try to select windows media player for my dvd movie and enhanced dvd movie autoplay options the only options that show up are vlc, dropbox and media player classic?
![Capture](https://user-images.githubusercontent.com/96899282/148615331-23cacf07-2d30-48c4-b014-83223fd6f089.PNG)

**Comment by clsid2** [comment]
If WMP options are broken it is not the fault of MPC-HC.

**Comment by Sin-Shadow-Fox** [comment]
As you can see in the upper menus WMP options are not broken.
EDIT: Also this didn't become an issue until media player classic was installed so it does have something to do with it.

**Comment by clsid2** [comment]
MPC_HC did not cause this !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by clsid2** [comment]
Registry key:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers\EventHandlers\PlayDVDMovieOnArrival
-> should contains empty string value with name "MSPlayDVDMovieOnArrival"

**Comment by Sin-Shadow-Fox** [comment]
Hmm. You seem angry. Maybe this will help. (hugs) ^_^

**Comment by Sin-Shadow-Fox** [comment]
Also how do i find this local machine folder? When i put it in windows explorer my webrowser pops up with 
"Hmm. We’re having trouble finding that site.

We can’t connect to the server at www.hkey_local_machine.com."

**Comment by clsid2** [comment]
You can edit the Registry with regedit.exe
If you have never done that before you need to be very careful not to do anything stupid.

In your screen shot you say "Windows Media Player" is "Classic", which does not make any sense at all, because they are two totally different and unrelated players. And if you say you can't select WMP, then why is it already selected by default...

I can't provide anymore help. I have better things to do with my life.

If you mean that MPC-HC is NOT shown there, then you need to let it create the autoplay entries first.
MPC-HC options > Player > Formats

Again...
Windows Media Player is a player made by Microsoft
Media Player Classic is a totally different player and has no relation to Microsoft at all, nor is it based on an old version of WMP. It only has a similar look as a very old WMP.

**Comment by Sin-Shadow-Fox** [comment]
The audio cd and enhanced audio cd autoplay options open windows media player as intended but dvd and enhanced dvd autoplay options open media player classic instead.

**Comment by Sin-Shadow-Fox** [comment]
Also you still sound kinda angry. So here, have another hug. (hugs again) ^_^

**Comment by Sin-Shadow-Fox** [comment]
Bump.

**Comment by Sin-Shadow-Fox** [comment]
Bump.

**Comment by clsid2** [comment]
I can't help you.
