### ISSUE TITLE
Subtitles embedded into mkv are not displayed

### ISSUE THREAD

**Issue by antrv** [clsid2/mpc-hc#1520]
Subtitles embedded into mkv are not displayed. The same .ass subtitles in external files are displayed correctly.

I extracted `.ass` subtitles from 1280x720 video and then I embedded them into 4k video using `ffmpeg`.
MPC-HC doesn't display embedded subtitles, although it shows in the context menu that the subtitle track is present and I choose it.
If I choose external the subtitle files, they are displayed normally.

**Comment by antrv** [comment]
Sorry, that was my fault. I have found the option `Subtitles -> Maximum texture resolution` in mpc-hp and I set it to `3840x2160`.

**Comment by clsid2** [comment]
It should also work with a lower texture resolution. That works exactly same for internal and external subtitles.

So your problem was likely caused by some other issue. Maybe the subtitle wasn't enabled/selected.

**Comment by antrv** [comment]
Of course I select the subtitles in the context menu.

Actually I met this problem not once. 
In the past I integrated subtitles into 1920x1080 mkv videos and MPC-HC displayed subtitles unstable (it may show subtitles in the middle of video but not from the start or it may show some pieces only). I blamed `ffmpeg` for that issue, because in that case using `mkvmerge` instead of `ffmpeg` solved the issue.
However it didn't happen in this case. I tried `mkvmerge` and it didn't help in this case.

**Comment by antrv** [comment]
I can give you an example of the video and subtitles if you want.

**Comment by antrv** [comment]
btw, is there any way to get logs about how MPC-HC parses subtitles? I may assume the subtitles has some invalid pieces.

**Comment by clsid2** [comment]
Does the problem only occur after seeking in the video? Then the file probably does not contain any cue elements for the subtitle data. The splitter needs that information to find the subtitle data inside the file. That is split up in pieces and scattered throughout the file.

This is not something that can be fixed by the player or the splitter. You need to use a proper muxer.

I can take a look if you share a file. You can't log anything yourself with a normal build. But your files are likely just improperly muxed.
