### ISSUE TITLE
Major issue in EVR-CP

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1528]
EVR-CP produces poor quality. It is noticeable when dark scenes come in a video.
Only VMR 9 (renderless) gives good quality at dark scenes. Also color shifts little bit in VMR 9.
I think this is because Surface option is not available in EVR-CP.

Here are screenshots for reference:

https://drive.google.com/file/d/14myreRKuuOv2K8sDC4VPjhfWmHaoSaX8/view?usp=sharing

**Comment by clsid2** [comment]
EVR-CP always uses 3D surfaces and that option is completely utterly unrelated to you problem.

The problem is caused by your graphics driver, which is using wrong luminance range.

If you have NVIDIA GPU then use this setting:
NVIDIA Control Panel > Video > Adjust video color settings > With NVIDIA Settings > Advanced > Dynamic Range = Full
(after this change you can select "with video player settings" again)

If you are using AMD, then you need to report the bug to them. It is a known fault in their drivers for some of their GPUs.
You can try this setting:
MPC menu > View > Renderer Settings > Output Range > 16-235
(this value is WRONG! but may correct the fault of the driver)

If you are using Intel, then disable "Contrast Enhancement" and "Fleshtone Enhancement" in the driver settings.

Otherwise use a different video renderer:
https://github.com/Aleksoid1978/VideoRenderer

I would like to emphasize that your problem is **not** the fault of EVR-CP!

**Comment by bibsp** [comment]
Thanks. I have intel gpu. Disabling contrast enhancement fixed the issue. You are great.

**Comment by clsid2** [comment]
Great. It is super annoying that Intel enables those settings by default. It is ridiculous how many problems it causes.
