### ISSUE TITLE
Request Play URL Videos

### ISSUE THREAD

**Issue by EgeGurkan** [clsid2/mpc-hc#1556]
Can't play youtube or any other famous links. can we have some support for atleast youtube?

**Comment by clsid2** [comment]
Already possible. Read this:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.19

**Comment by bibsp** [comment]
@clsid2 , Is there any future plan to integrate yt-dlp and MPCVR inside MPC-HC setup.exe?

Because as you see here people don't know those things. Normal people just install a program and start using that. They don't do research or experiment. It's obvious. They will just simply conclude that mpc be can do that. Hc can't.
It's better to integrate those inside MPC-HC installation setup.

What is your thought?

**Comment by clsid2** [comment]
No plans for integrating anything. This project is just for the player. Period. End of discussion.

You can install other software through for example K-Lite Codec Pack. The majority of MPC-HC users already use such packs.
