### ISSUE TITLE
The last path of the "Quick Open File" will be synced with the last path of the "Save Image"

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#1562]
Hi

When saving a screenshot with "Save Image", "Quick Open File" will overwrite the path where the last media file was opened with the path where the screenshot was saved.

For example, if you open `D:\Video\example.mp4` and then save a screenshot to `D:\Screen_Shot\example.jpg`, the "Quick Open File" dialog will open `D:\Screen_Shot\` next time.

"Open file/open URL" is unaffected.

**Comment by clsid2** [comment]
The player does not remember locations of those regular file dialogs. Windows does.

Fixing this is low priority.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1582

I didn't check too closely, but it seems the save image causes windows to remember the folder, but quick open did not.  Not sure why, but they are different dialogs.

This just forces mpc-hc to store and load the last folder path, instead of trying to decipher why windows was doing what it was doing.

**Comment by FX8350** [comment]
Works fine.
Thank you fix!
