### ISSUE TITLE
Cannot quickly load different video files

### ISSUE THREAD

**Issue by kot2202** [clsid2/mpc-hc#1604]
Try double clicking any video file in windows file explorer to open it and instantly after that, double click any other video - the first video will continue playing as long as you will keep double clicking. You have to stop for like 3 seconds between video switching and it's pretty annoying with small files. It happens to any file extension and the files are placed on ssd drive

**Comment by clsid2** [comment]
That happens if you click again within 2 seconds. In that case the file is appended to playlist instead. This is done to deal with opening a selection of videos. Explorer has annoying behavior that it opens a new instance for each selected file. The player detects this and redirects everything to one instance.

I can't fix this.
