### ISSUE TITLE
[Feature suggestion] Glob expression support in subtitle autoload paths

### ISSUE THREAD

**Issue by ghost** [clsid2/mpc-hc#1611]
Hi!~ It would be nice to implement glob expression support in `Options -> Subtitles -> Misc -> Autoload paths`. I think it can be really useful feature

So, with path `subs\*` and file structure like:

- cute_sample.mkv
- subs/
  - first/
    - cute_sample.ass
  - second/
    - cute_sample.ass

MPC-HC will pick up subtitles from `subs/first/cute_sample.ass` and `subs/second/cute_sample.ass`

**Comment by clsid2** [comment]
Not interested in that.

You can use name tags in the filename if you need multiple.
cute_sample.first.ass
cute_sample.second.ass

**Comment by anonghuser** [comment]
When I get a show with 12 or 24 or more episodes with subs in a stupid subfolder structure, renaming the subs to fit mpc-hc requirements is annoying enough that instead of spending 2-5 minutes doing it manually file by file i sometimes spend 15 looking up batch file for loop syntax and stuff to rename them automatically, and then lose the batch file by the next time i happen on another such show. having mpc-hc understand glob expressions and/or a $filename placeholder for the episode's name (without extension) would be very useful. 

Specifically, I want it to be able to find `.\Subs\$filename\*English.srt` files.
[EDIT: The glob part is actually less of a priority than the filename placeholder, as I can easily enumerate `.\Subs\$filename\1_English.srt; .\Subs\$filename\2_English.srt; .\Subs\$filename\3_English.srt;`, etc. It will look stupid but at least work. Those numbers are not episode numbers btw, in case someone gets confused. They are just the index of the ripped subtitle tracks\languages in many releases.]

Yes, it would've been great if whoever made the subs organized them like `Subs\[$language]\[$filename].srt` so i could just copy them from the relevant language folder into the videos folder, but a lot don't.

**Comment by clsid2** [comment]
I already said that I am not interested in this. Someone else has to submit a patch.

Go complain to the idiots that make those stupid folder structures.
