### ISSUE TITLE
Need help (high cpu usage)

### ISSUE THREAD

**Issue by saidmoudj-canopus** [clsid2/mpc-hc#1767]
Why I have a high CPU usage when I am playing video on K lite codec pack ?   (Even I am not recording)
![image](https://user-images.githubusercontent.com/80714022/177893092-facb4873-88d5-4bbc-b50e-cec56c4d00f8.png)

**Comment by clsid2** [comment]
High usage from MPC-HC is likely because you are playing a video format for which your computer does not provide hardware acceleration.

OBS Studio is using a significant amount of CPU, so it seems to keep doing something, even when recording is disabled. You should close OBS if you are not actively using it. The high usage of Desktop Window Manager is also likely due to OBS being active.

**Comment by saidmoudj-canopus** [comment]
Yeah.
But also if OBSis closed I have the same issue.
Thanks & Regards.

‫في الجمعة، 8 يوليو 2022 في 1:43 م تمت كتابة ما يلي بواسطة ‪clsid2‬‏ <‪
***@***.***‬‏>:‬

**Comment by clsid2** [comment]
I can't say if anything is abnormal without details about the video file and your computer hardware.

**Comment by saidmoudj-canopus** [comment]
Thanks, I'll check it out.

‫في الجمعة، 8 يوليو 2022 في 3:04 م تمت كتابة ما يلي بواسطة ‪clsid2‬‏ <‪
***@***.***‬‏>:‬
