### ISSUE TITLE
Access violation on video changing resolution mid-play

### ISSUE THREAD

**Issue by namazso** [clsid2/mpc-hc#1792]
Video to reproduce:
[bhop_cut.webm](https://user-images.githubusercontent.com/8676443/182185609-0d5515b2-5d6e-45db-8f27-d19aaf272d7e.webm)

**Comment by namazso** [comment]
After updating to latest development version it still crashes, and redirects me to https://github.com/clsid2/mpc-hc/issues/454

Internal filters are all enabled

**Comment by clsid2** [comment]
Problem only seems to occur with MPC Video Renderer.

@Aleksoid1978
LAV Video Decoder reconnects to the renderer on size change. This fails with VFW_E_TYPE_NOT_ACCEPTED when new width is uneven. Can you have a look at this?

LAV debug output for a successful reconnect followed by a failed one:
```
LAVVideo.ax(tid 32b0)   227123 : ::ReconnectOutput(): Performing reconnect
LAVVideo.ax(tid 32b0)   227124 : Using VIH2, Format dump:
LAVVideo.ax(tid 32b0)   227124 : -> width: 870 -> 966
LAVVideo.ax(tid 32b0)   227124 : -> height: 360 -> 360
LAVVideo.ax(tid 32b0)   227124 : -> AR: 16:9 -> 16:9
LAVVideo.ax(tid 32b0)   227124 : -> FPS: 333333 -> 333333
LAVVideo.ax(tid 32b0)   227124 : -> interlaced: 0x00000000 -> 0x00000000
LAVVideo.ax(tid 32b0)   227124 : -> flags: 0x00012081 -> 0x00012081
LAVVideo.ax(tid 32b0)   227134 : ::CheckTransform()
LAVVideo.ax(tid 32b0)   227135 : -> New MediaType negotiated; actual width: 966 - renderer requests: 1024
LAVVideo.ax(tid 32b0)   227136 : ::CheckTransform()
LAVVideo.ax(tid 32b0)   227136 : SetMediaType -- out
LAVVideo.ax(tid 32b0)   227156 : ::ReconnectOutput(): Performing reconnect
LAVVideo.ax(tid 32b0)   227157 : Using VIH2, Format dump:
LAVVideo.ax(tid 32b0)   227157 : -> width: 966 -> 1049
LAVVideo.ax(tid 32b0)   227157 : -> height: 360 -> 360
LAVVideo.ax(tid 32b0)   227157 : -> AR: 16:9 -> 16:9
LAVVideo.ax(tid 32b0)   227157 : -> FPS: 333333 -> 333333
LAVVideo.ax(tid 32b0)   227157 : -> interlaced: 0x00000000 -> 0x00000000
LAVVideo.ax(tid 32b0)   227157 : -> flags: 0x00012081 -> 0x00012081
LAVVideo.ax(tid 32b0)   227157 : -> Receive Connection failed (hr: 8004022a); QueryAccept: 1
```

**Comment by Aleksoid1978** [comment]
MPC-VR rejects odd sizes for some formats, including NV12.

**Comment by clsid2** [comment]
@nevcairiel

In `CLAVVideo::ReconnectOutput` I have added:
```
if (mt.subtype == MEDIASUBTYPE_NV12 || mt.subtype == MEDIASUBTYPE_YV12 || mt.subtype == MEDIASUBTYPE_YUY2 || mt.subtype == MEDIASUBTYPE_I420)
{
    pBIH->biWidth = FFALIGN(width, 2);
}
```
This solves the problem. Do you think this is a good solution/workaround?

**Comment by Nevcairiel** [comment]
LAV Video should not mess with the image because a renderer refuses the connection. Original dimensions, or no connection.

**Comment by clsid2** [comment]
The image width itself is not changed, just the biWidth value in the output mediatype used for connection negotiation. The renderer typically requests a larger (mod32) biWidth anyway for final connection. So it seems the workaround does not do harm, or am I missing something? Your code does a similar thing for v210 already.

I do agree that the renderer should not be refusing the (re-)connection. Then LAV does not have to mess around with this stuff.

@Aleksoid1978
Why refuse uneven width in initial mediatype when the renderer will request a larger stride during mediatype negotiation? The initial width is then not relevant anymore.

Playback works fine for the sample file if I remove the uneven biWidth check in `VerifyMediaType()`.
I propose moving the width check to `CMpcVideoRenderer::SetMediaType()`. If `QueryAccept` fails for new calculated mediatype, then fail if width of current mediatype is uneven.

```
if (S_OK == m_pInputPin->GetConnected()->QueryAccept(&mtNew)) {
	DLog(L"CMpcVideoRenderer::SetMediaType() : upstream filter accepted new media type. QueryAccept return S_OK");
	inputPin->SetNewMediaType(mtNew);
	mt = mtNew;
} else {
	// new code
	const BITMAPINFOHEADER* pBIH = GetBIHfromVIHs(pmt);
	if (pBIH && (pBIH->biWidth & 1)) {
		const auto& FmtParams = GetFmtConvParams(pmt);
		if (FmtParams.Subsampling == 420 || FmtParams.Subsampling == 422) {
			return VFW_E_UNSUPPORTED_VIDEO;
		}
	}
}
```

**Comment by v0lt** [comment]
> This solves the problem. Do you think this is a good solution/workaround?

This is a bad decision. The NV12 format must have even dimensions. If you think otherwise, then I ask you to show the document of the standard, which says otherwise and explains how such a frame should be stored in memory. I have not found such a document.

If the VP9 format allows odd frame sizes (I also want to see a reference to the standard here), then when decoding in NV12, the frame sizes should be increased to even sizes and rcSource and rcTarget filled accordingly. Then it will work correctly (if VP9 allows odd sizes).

In any case, you can release your version of the renderer, which will support the wrong NV12.

**Comment by clsid2** [comment]
@v0lt
MPC-BE Video Decoder has same problem with the sample file.

**Comment by Aleksoid1978** [comment]
Do not pay attention to such a file - it is 100% incorrect. Google's official VP9 encoder(libvpx) does not support odd sizes.

**Comment by namazso** [comment]
So is crashing with ACCESS VIOLATION the expected behavior here?

**Comment by Aleksoid1978** [comment]
Crash in decoder.

**Comment by namazso** [comment]
Sorry for my potential lack of understanding (i've only been an user to video stuff so far), but doesn't that mean this shouldn't work? (the video is VP8 btw, not VP9)

```
ffmpeg -i .\bhop_cut.webm -vf scale=1279:719 -acodec copy -vcodec libvpx bhop_cut2.webm
```

Because it does. It also doesn't crash MPC-HC and shows the correct dimensions too:

![image](https://user-images.githubusercontent.com/8676443/182976110-59670a82-a225-4d6e-a8bf-7b5a78adf389.png)

ffplay also plays both the original and the new files

**Comment by clsid2** [comment]
Both the code changes I posted above solve the crash. Question is what is the best and most correct solution.

The problem is that on size change the pin connection between decoder and renderer is updated. With a new uneven width, MPCVR rejects that change. After this the decoder will work with the new size, but with the unchanged (smaller) buffer, and crash happens.

The renderer will propose a padded buffer (multiple of 32) on the initial connection request. Even if width is even. So there is no reason to refuse connection that early when width is uneven. In normal situation the actual size that will get used is a proper padded even value.

The video itself is probably also encoded using padded dimensions. Afaik some/most encoders use module 16.

**Comment by v0lt** [comment]
I checked VP9 video 1279x719 pixels.
Video processor D3D11 does not work.
D3D11 decoder not working.
Incorrect display of the bottom line.
Other undetected problems are also possible.

But I have another question. Why would anyone need support for such incorrect media types as input in a renderer? Just because someone wanted it?

**Comment by Aleksoid1978** [comment]
I think there may be one normal explanation for videos with odd frame sizes - it's screen recording.

**Comment by clsid2** [comment]
I have applied the biWidth padding workaround.
