### ISSUE TITLE
Option to modify shell integration to default "/add" command on double-click

### ISSUE THREAD

**Issue by kdebro** [clsid2/mpc-hc#1793]
i wanna double-click any associated file and queue it in the same MPC instance in the same list without clearing the current list and without opening new instance. Yes, i could right click and select "add to playlist," but those micro clicks add up to wasted time, literally twice the time. this request is a matter of convenience and general efficiency

if no patch will be done, then could someone explain how to change this default behavior on windows 10 to enqueue files to an MPC list? a direct answer is hard to find

**Comment by clsid2** [comment]
I will not add such options.

You can also enqueue by dragging file(s) on to the player window. Hold Ctrl while dragging to enqueue instead of open.

You can modify the default action by editing the Registry.
As an example, in this key:
`HKEY_CLASSES_ROOT\mplayerc64.mp3\shell`
Change the `default` value to `enqueue`. When the value is empty, windows defaults to `open`.
Do this for all file types that you want to adjust behavior.

**Comment by kdebro** [comment]
i don't like the drag-drop either, but setting default to enqueue for each filetype works as intended, thanks

**Comment by ghost** [comment]
> I will not add such options.

Please? Or maybe if you don't want an option, make this behaviour the default, so that the default is non-destructive? Or... Something?

>  Do this for all file types that you want to adjust behavior.

There are hundreds. This is not a very practical way. In fact, as a disabled user, it's literally not worth the pain, and I'm about to just remove all file associations so that I don't ruin my playlist every time I open a file.... but I like to think you might consider a superior alternative :)

**Comment by kdebro** [comment]
> There are hundreds. This is not a very practical way. In fact, as a disabled user, it's literally not worth the pain, and I'm about to just remove all file associations so that I don't ruin my playlist every time I open a file.... but I like to think you might consider a superior alternative :)

rep owner has almost no interest in any update regarding user convenience to the point where he prevents others who might be able to do it from helping: here's a ps script you can use to change the default behavior

```
Get-ChildItem Registry::HKCR\mplayerc64.* -Recurse |
  Where PSChildName -eq 'Shell' |
Set-ItemProperty -Name '(Default)' -Value 'enqueue'  
#change 'enqueue' to empty string or 'play' to default to play
```

**Comment by ghost** [comment]
> ```
> Get-ChildItem Registry::HKCR\mplayerc64.* -Recurse |
>   Where PSChildName -eq 'Shell' |
> Set-ItemProperty -Name '(Default)' -Value 'enqueue'  
> #change 'enqueue' to empty string or 'play' to default to play
> ```

Thanks so much for sharing this. Posting to confirm it works but mostly to show appreciation to you :)

I saw many questions/requests about this elsewhere, so I had prioritised coming here for a fix for everybody, over automating a workaround for myself. Now I can have my cake and eat it too.
