### ISSUE TITLE
Sub opaque box

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1803]
![Screenshot (552)](https://user-images.githubusercontent.com/98865389/183293329-36860b98-d33d-421d-b828-5b8ed4ea7df8.png)
![Screenshot (554)](https://user-images.githubusercontent.com/98865389/183293330-fd79b2e7-e1a1-4719-ae9b-c895fac945aa.png)

Can you fix it? Two opaque boxes should blend with each other.

**Comment by adipose** [comment]
Probably would be fixed with libass fork.

**Comment by clsid2** [comment]
Can be fixed in current code as well. Some extra pixels line spacing could be added in this situation as a workaround.

**Comment by passat1** [comment]
As temporary solution I use value 0.0001 in field 'Width' (as value 0.0000 could not be used), so boxes do not overlap.
I also suggest that boxes should have additional side (left and right) "space", same as at top and bottom, because with that small value, letters are at the edge of box (no extra dark area) and when text is in 'italic' at the end of line, part of last letter could be out of box.

IMHO, best solution would be to separate 'outline' from 'box' (independent), not to chose 'outline' **OR** 'box'.
Choice should be 'shadow' OR 'box'.
That way we would be able to have outlined text in box.

**Comment by bibsp** [comment]
> I also suggest that boxes should have additional side (left and right) "space", same as at top and bottom

Yes, I agree with passat1.

**Comment by clsid2** [comment]
Fixed the overlap by adding some padding between lines.

There can be an occasional 1 pixel overlap or gap. Don't know why and I am not going to spend more hours to fix that. So any motherfuckers with OCD that are bothered by that can just die.

**Comment by passat1** [comment]
@clsid2 
Thanks for your effort, but your last sentence is just too much ...
