### ISSUE TITLE
Weird issue caused by MKV files

### ISSUE THREAD

**Issue by TsukiZero** [clsid2/mpc-hc#1804]
![image](https://user-images.githubusercontent.com/78157224/183788951-1826a46a-86df-45b6-a7a1-fdc6610a2f5c.png)
It's not all, but with GeoSubs it's consistent to mess with the ui.

**Comment by clsid2** [comment]
This happens because the idiots that created this file are embedding the `Segoe UI` font, which is a system font that is used by the interface. Embedded fonts are loaded for use for the subtitles, and that overrules the installed fonts. The embedded font differs though, with other character set, causing the text corruption.

One easy fix is to remux the file with MkvToolNix, with only change to remove the Segoe font attachments.

**Comment by clsid2** [comment]
I have implemented a workaround for this.
