### ISSUE TITLE
Gsync Support!

### ISSUE THREAD

**Issue by marat569** [clsid2/mpc-hc#1834]
So I love MPC-HC + MadVR. My favorite player for years now.

Recently I've gotten a monitor with a Gsync Ultimate module; which supports a refresh rate of 1-max; which means 24hz is no problem.

Sadly I can't engage gsync in MadVR without using the Nvidia Control Panel workaround which enables gsync for "windowed applications" -- which is a big nono to enable. 

I don't like MPV, it's too big brain for me; but when it's in fullscreen it engages gsync and my monitor's OSD shows 24hz.

If we can get gsync support in MPC-HC; that would be awesome.

On a side note, I don't get why gsync does not activate in the first place, since MPC-HC is a full screen d3d11 program.

**Comment by clsid2** [comment]
Video playback requires a constant and predictable refresh rate. Variable refreshrate is useless and will not be supported.

Refreshrate switching ability in madvr should not depend on GSYNC. You just need to add a custom refreshrate in Windows display settings (if 24hz mode is not available yet) and configure madvr with the available rates it can use.

Disable GSYNC globally and use profiles to enable it in supported games.

**Comment by ColonelGerdauf** [comment]
VRR may be useless for video playback, but there still needs to be contingency in place regardless. Asking people to just global disable stuff like G-Sync is less than ideal, given the wide scope of use cases for people who have installed MPC.

For instance, people may be frequently gaming, and watching/listening from time to time. In that case, flipping VRR and even using profiles will become a needless chore for people to do, especially when people's gaming and media consumption habits are sporadic, random, and personally situational.

Regardless, VRR is in a position now where it is inching closer and closer to being a universal display standard, due to the wide number of use cases where VRR ended up being quite helpful. VRR is less about frame rate numbers and more about things such as preventing display jitter. Jitter is a particularly big deal when it comes to video playback, especially in the scope of personal computers where other things are happening.

**Comment by ColonelGerdauf** [comment]
> Disable GSYNC globally and use profiles to enable it in supported games.

I have so many problems with this statement.

First off, it carries the tone that VRR is "useless", when as I explained previously it is far from useless.

Second, as I said, that plan can be quite annoying for people depending on the situation at hand of how their computers are set up and how they use their computers. It would be much much easier just to disable G-Sync on a MPC profile and potentially other video-related programs.

Third, "supported games". This is not a matter where a game needs to be certified for VRR compatibility. As long as the game devs don't do anything stupid by breaking program standards, such as enforcing or even "allowing" the ancient and actually useless FSE (fullecreen exclusive), the game is automatically supported by G-Sync and the like. In fact, it goes beyond games; if general-use programs are compliant, then they get the benefits of VRR as well without even needing to be fullscreen.

**Comment by Aemony** [comment]
I'm not sure this is the right forum for this, as it concerns madVR first and foremost since that's what's processing, rendering, and, I assume, actually presenting the frames. It's basically more appropriate to raise it with the madVR team, I imagine.

That said, VRR is absolutely relevant for media players as it allows the display to sync to the frame rate of the video instead of the opposite, however because of the "classic" method of relying on vertical sync to pace the frames of a video properly it's understandable that basically no media player today is actually capable of utilizing VRR properly due to poor / non-existent frame pacing.

A media player utilizing VRR with a modern high-end frame rate limiter would be able to achieve sub-1ms frame variance between presents, and allow any arbitrary video frame rate to be displayed accurately on any VRR display in both window and maximized borderless window mode, without having to mess around with custom refresh rates, CRU, nor experience judders, frame drops, etc either.

It's a shame VRR isn't taken more seriously within the media playback landscape since it is tech intended for this sort of specific use case (it harkens back to eDP and embedded devices only refreshing their display once something on the screen has changed), but it's understandable since the one main thing it demands, a good frame rate limiter on the part of the media player, is something all popular media players today tend to suck at due to never being relevant for them up until VRR came along.

Anyway, for madVR related stuff, it's probably better to post about it over on their support thread? 
https://forum.doom9.org/showthread.php?t=146228

**Comment by clsid2** [comment]
This already has been discussed several times in that madvr topic years ago already. Long story short, madvr will not support it.

If having GSync enabled gives troubles with applications, it is the fault of NVIDIA.
