### ISSUE TITLE
Make the area under the seekbar NOT drag the entire window

### ISSUE THREAD

**Issue by HamzaETTH** [clsid2/mpc-hc#1855]
Is there an option I'm not seeing to not make the [area ](https://i.imgur.com/i6KZ6eM.png)under the seekbar not drag the whole window and only allow dragging from the title bar like pretty much all other apps/softwares.

**Comment by clsid2** [comment]
There is no option for it and there will be no option. There is a small safezone below seekbar.

If you use dark theme, then you can increase height of the seekbar in the advanced options.

**Comment by kkdexz** [comment]
IIRC, there used to also be a safezone above the seekbar as well, and it was overall a bit larger (on both sides I think?). Would you consider reverting back to that size? This would make it so that the user won't have to compromise on their preference for seekbar size.

I can't remember exactly why you changed it, I think it was due to an issue another user had brought up, but I can't imagine anyone deliberately choosing to drag the player so close to the seekbar, let alone the controls bar which is right below it. I would assume most would either drag somewhere in the vicinity of the middle of the player (such as myself), or the title bar, or even the status bar, but not the controls bar.

Personally, a safezone above the seekbar is equally, if not more, important than below it.
