### ISSUE TITLE
MPC-Home keeps setting display 2 as display 1 randomly

### ISSUE THREAD

**Issue by molitar** [clsid2/mpc-hc#1858]
So I am using a remote control software but stupid MPC keeps switching randomly which display is Display 1.  I have it set to Full screen on Display 2 but than it will full screen on Display 1 not monitor 2!  I than have to manually change it to Display 1 so it shows on Monitor 2!  

Next time I run it.. it will decide Display 1 is actually Display 1 and do full screen on display 1 and I have to manually change it back.. this is making my HTPC totally useless!

**Comment by clsid2** [comment]
MPC does **not** switch display names. It is Windows which is doing that. Probably because you are turning one of the screens on after boot and Windows then does stupid things.

I have applied a patch that stores both the display name and device name. So it will work better in next development build.

**Comment by molitar** [comment]
Thanks.. because windows reports monitor numbers properly and so does Radeon.. so it's probably a hidden value it's using under the engine by Windows.

**Comment by clsid2** [comment]
The identification numbers and the display "name" that Windows uses are two separate things. Windows messes up the naming in your case.
