### ISSUE TITLE
Video freezing when looping

### ISSUE THREAD

**Issue by ssheep** [clsid2/mpc-hc#1940]
Same problem as #1691.

Last frame freezes and audio loops back:

https://user-images.githubusercontent.com/22974058/206921399-3ea22375-63e5-4a35-9f5a-9fb928cc9fa7.mp4

Doesn't happen when replaying it, only with "Repeat Forever" checked and a single file (doesn't affect playlists):

https://user-images.githubusercontent.com/22974058/206921403-0f25ed4a-8a6d-4c3f-b66d-91dab4d2c20c.mp4

Here's the [original video file](https://www.flickr.com/video_download.gne?id=3524824341). But it happens with every video tested and all formats (.mp4, .mkv, .webm, .avi).

Resetting settings (and rechecking only "Repeat Forever") had no effect.

Intel Graphics up to date.

MPC-HC (64-bit)
---------------

Build information:
    Version:            1.9.24 (ffe50c0c7)
    Compiler:           MSVC v19.29.30145
    Build date:         Nov 12 2022

LAV Filters:
    LAV Splitter:       0.77.0.1
    LAV Video:          0.77.0.1
    LAV Audio:          0.77.0.1
    FFmpeg compiler:    MinGW-w64 GCC 12.2.0

Operating system:
    Name:               Windows 11
    Version:            10.0.22621 (64-bit)

Hardware:
    CPU:                12th Gen Intel(R) Core(TM) i7-12700
    GPU:                Intel(R) UHD Graphics 770 (driver version: 31.0.101.3959)

**Comment by clsid2** [comment]
Looping is working fine here with that video.

Update to latest development build:
https://github.com/clsid2/mpc-hc/releases

Otherwise I can only suggest to test with hardware decoding disabled.

**Comment by clsid2** [comment]
And maybe try with different audio and video renderer.
Options > Playback > Output

**Comment by oceanful** [comment]
If it's helpful, I was able to fix the problem by changing the `Options > Playback > Output > DirectShow Video` setting to anything that did not enable DXVA (i.e. "Video Mixing Renderer 9 (or 7)" and "Old Video Renderer").

**Comment by clsid2** [comment]
Instead of doing that you can disable DXVA in the internal video decoder settings.

**Comment by ssheep** [comment]
> If it's helpful, I was able to fix the problem by changing the `Options > Playback > Output > DirectShow Video` setting to anything that did not enable DXVA (i.e. "Video Mixing Renderer 9 (or 7)" and "Old Video Renderer").

It worked, thank you.

> Instead of doing that you can disable DXVA in the internal video decoder settings.

For some reason just disabling DXVA did not work here.

**Comment by gitschab** [comment]
Pardon me for resurrecting this, but I've had this exact problem. Actually the video doesn't to be on loop - once the player reaches its final frame and stops playback you can seek to anywhere in the video and only the audio will play; the video will be frozen on the final frame) since I switched to laptops with Intel Iris Xe Graphics (Dell Precision 5570, same issue on Dell XPS 9530 (2023)). Happens on both W10 and W11.

Also the picture controls (those found in "Miscellaneous") don't work since then (in EVR they have no effect, in "VMR9 (renderless)" they just turn picture completely black when set to anything but the default value(s)) (which is a shame, I had a keybinding for decreasing/resetting contrast for late night watching)

**Comment by clsid2** [comment]
Those problems are caused by bugs in either the Intel driver on in the d3d9on12 compatibility layer that the driver uses. I can not fix any of those problems.

You should try MPC Video Renderer which you can get on our download page.

**Comment by butterw** [comment]
gitschab: (Intel) Broken seeking after reaching end of file https://github.com/clsid2/mpc-hc/issues/2366
