### ISSUE TITLE
Donate with PayPal or Stripe or Revolut

### ISSUE THREAD

**Issue by ChrisPrefect** [clsid2/mpc-hc#1968]
Hi!

I wanted to donate but I can't use bitcoin, but PayPal (yes. they are pure evil, I know) or Stripe or Revolut would work.

Thanks for your work!!

**Comment by clsid2** [comment]
Sorry, not possible.

**Comment by SigHunter** [comment]
github sponsoring? patreon? unnumbered bills in a neutral brown bag that I can drop off in a dumpster?

**Comment by SanderBouwhuis** [comment]
I came here because I too pressed the Donate link and saw I couldn't donate. We really need some way to do this, or nobody will be able to donate.

**Comment by wyndigo94** [comment]
I'd also love to donate, but I do not use Bitcoin. If other options become available in the future that would allow more community members to donate.

**Comment by clsid2** [comment]
Paypal also supports bitcoin:
https://www.paypal.com/us/digital-wallet/manage-money/crypto

**Comment by Tampa** [comment]
> Sorry, not possible.

You know if you openly complain about something that you make the hardest to accomplish then I am not exactly surprised you got no takers. You said in another ticket regarding this that you think PayPal is an evil company and while I won't dispute that you also want people to put their data into the hands of Nord, which push their "privacy and security" bullshit vpn as something it isn't. It's not even just that people find the setup for even sending you some bitcoin cumbersome, they might not want to use a technology that wastes so much electricity and harms the environment in many ways. Most people that accept donations to fund their development efforts make an effort to make it as convenient as possible, because the less hoops one has to jump through to send cash the more likely it is you'll get it. It's why patreon took off like a rocket and most similar platforms do too. One has to make some compromise in most things in life to get something and that might mean providing some basic details to a company that will enable you to actually get paid for all the work you provided over the years. I can understand things being complicated when your country of residence doesn't allow those things, but that doesn't seem to be the case, though do enlighten me if it is. Even then there are options through shell accounts and other means to facilitate donations more easily. You have to put yourself in the shoes of those that wish to support you and their outlook on the options you provide them with may not be easy for them as they are for you. :)
