### ISSUE TITLE
Add option to use libass to render ass/ssa subtitles

### ISSUE THREAD

**Issue by g-2-s** [clsid2/mpc-hc#205]
This is not an issue but a question from a noob user: are external sub renderers like XySubFilter or AssFilter still necessary/recommended or is the internal one good enough?

**Comment by eXmendiC** [comment]
XySubfilter as a libass wrapper is my recommendation.
Take a look here: https://github.com/Cyberbeing/xy-VSFilter/pull/16

**Comment by clsid2** [comment]
The internal subtitle renderer works good and is reliable. Perhaps only with idiotically complex typesetting it might struggle with performance.

xy-VSFilter and XySubFilter are based on VSFilter, which is actually part of MPC-HC code base and shares the rendering code with the ISR. So instead of trying to modify a dead fork of a dead project (xy-VSFilter) people should consider implementing a libass rendering option for ISR. The patch that you have linked to could probably be ported with some small modifications.

**Comment by MatiasMovie** [comment]
XySubFilter work better than internal sub filter but when you using external filter then you can't using delay (F1 and F2 button). Delay with external sub filter works in MPC-BE.

**Comment by clsid2** [comment]
It could be interesting to port this patch to MPC-HC:
https://github.com/Cyberbeing/xy-VSFilter/pull/16

**Comment by adipose** [comment]
I looked at the patch, and I'm sure it could be ported, but most of the changes are in new cpp files that don't exist in the mpc-hc-included VSFilter.

**Comment by clsid2** [comment]
Yes, it seems the patch only changes it for XySubFilter and not for VSFilter. But they share the same lower level code, so it should be portable to VSFilter (and Internal Subtitle Renderer) as well.

**Comment by adipose** [comment]
https://en.wikipedia.org/wiki/DirectVobSub

The article mentions mpc-hc being shut down due to lack of developers.  Might be worth updating it.

**Comment by adipose** [comment]
@clsid2 

The patch relies on RequestFrame, which isn't an implemented method in vsfilter (though it is in xy-vsfilter via xy_sub_filter).  It seems more like the code in XySubPicProvider in mpc-hc.  So maybe a new sub provider similar to PGSSub would be the most analogous.

I was hoping a 3 way merge might be possible, but after reviewing it, it seems basically it would have to be reimplemented in mpc-hc.

I'm not familiar with vsfilter code, so I'm probably not the right person to do it, but it seems to me the code that this patch depends on isn't really in mpc-hc vsfilter.

**Comment by clsid2** [comment]
I am not very familiar either. But yes, it seems it would require a new implementation similar to CRenderedTextSubtitle/CPGSSub.

**Comment by clsid2** [comment]
Test build with libass:
https://mega.nz/file/FJoQQYDY#RJoFWI4m4fB86zpi9W9_9_Tmf5tv8doNkHfm9y1O80E

**Comment by eXmendiC** [comment]
Since you closed the issue and already and have a test build, does it mean it will be implemented (as an alternative option) with a newer version? I downloaded the test build but can't see an option available besides "Internal Subtitle Renderer". You changed the name to "Add option to use libass to render ass/ssa subtitles", so it shouldn't replace the old "Internal Subtitle Renderer", should it?

**Comment by clsid2** [comment]
It will be optional.

**Comment by MatiasMovie** [comment]
I think Masaiki create good solution to use libass in mpc
https://github.com/Masaiki/xy-VSFilter/releases
