### ISSUE TITLE
Where is the save data for your MPC-HC? 

### ISSUE THREAD

**Issue by Theletha** [clsid2/mpc-hc#2127]
i reinstalled windows and was trying to find the data folder for all the settings and themes and such. Where can i find it?

**Comment by clsid2** [comment]
Settings are stored in the Windows Registry.
HKEY_CURRENT_USER\Software\MPC-HC

**Comment by Theletha** [comment]
oh god, why not just a simple folder in appadata?

Thanks for the reply by the way.

**Comment by butterw** [comment]
You can configure so that mpc-hc64.ini is saved to the player folder instead:  
mpc-hc > Options > Player > x Store Settings in .ini file

**Comment by clsid2** [comment]
Storing to INI does not work when installed in program files folder, because that is a protected system folder. Unless you mess around with file permissions on the INI file.

INI file is also slower.

Registry can also easily be saved for backup. That is the primary "bad" reason why most use INI.
MPC Options > Miscellaneous
