### ISSUE TITLE
DVB subs

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2130]
@adipose
Do you still have DVB hardware? Can you test if subtitles are working for live DVB playback?
Got a report that it might got broken after 1.9.24.

**Comment by adipose** [comment]
I do, but I am not sure if I have any feed with subtitles.  I'll check if my emulation software can do that.

**Comment by adipose** [comment]
I got an ATSC stream with captions streaming.  WinTV shows captions but mpc-hc does not.  Tested using 1.9.17.6 with same results.

**Comment by clsid2** [comment]
Does it correctly parse the subs? Meaning bug is with visibility/size.

**Comment by adipose** [comment]
No, it doesn't seem to recognize them at all.

CC in ATSC seems to be embedded in the mpeg stream.  I will check dvb next.

**Comment by adipose** [comment]
I confirmed something is different in DVB.  I could not get subtitles to actually show, yet.  But in 1.9.16, it shows "Subtitles (French)" and in latest it just says "Subtitles".  Need to find a stream that actually has valid subs.

**Comment by adipose** [comment]
OK, https://github.com/clsid2/mpc-hc/pull/2146 fixes the issue where no subs are ever selected.  At least, in the one stream I have, I was able to get subs after changing this, when previously it last worked with 1.9.24 (broken in 1.9.24.8).

The other issue where it doesn't show the language on the sub is still happening since 1.9.17.

**Comment by clsid2** [comment]
This affects just the initial selection. I changed that to avoid potentially unwanted language selections.

The real problem is that the subtitle should not break if not selected initially but manually selected later. Question is what is happening differently when it is selected from start or not? That is puzzling me. Afaik problem is only with live DVB and not with recorded files.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/commit/c6b9544dc45f8c73768b00c614f54cf4a27df5ab

This is the commit where the option to have "(French)" was removed.  I don't know why.

What's interesting in FGManagerBDA tries to set the language name (with brackets) if LCID==0:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/45d48143-f242-46da-8a31-7f5eb93e92d4)

So ironically if LCID is unset (0), you get the language name but otherwise you now don't.  Maybe intentional?

**Comment by clsid2** [comment]
I messed around with that code because the language was often already in the name itself. For example external tracks with known LCID already have language appended, and internal ones (from LAV) have the ISO codes.
I have pushed a commit that partially reverts it.

Any idea yet what break the subtitle rendering itself?

**Comment by adipose** [comment]
Not much idea, but I can fix it by doing this:

![image](https://github.com/clsid2/mpc-hc/assets/3324395/6c74b888-38be-43ad-b64a-0e21ba3308b6)

Once the setsubtitle happens once, the subtitle works after that.  The way it's selected from the menu is different, which I couldn't find yet.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2146

This seems to fix the issue and doesn't auto-select a sub when the channel has no default.

I don't understand why this became necessary.  But setting the subtitle seems necessary, rather than just the default.

**Comment by adipose** [comment]
Or...maybe it was always broken, but you fixed the problem where default subs were enabled, and then nothing worked.

**Comment by clsid2** [comment]
Yes, I suspect it was always broken, but never noticed because of the initial selection. Can a stream have multiple subs? Because switching between them was probably also broken then I think.

**Comment by adipose** [comment]
> Yes, I suspect it was always broken, but never noticed because of the initial selection. Can a stream have multiple subs? Because switching between them was probably also broken then I think.

Yes. My example has two subs. But the second seems empty. I will check with WinTV.
