### ISSUE TITLE
Subtitle delay not work with XySubFilter

### ISSUE THREAD

**Issue by MatiasMovie** [clsid2/mpc-hc#214]
not working delay subs with F1 and F2 buttons when you using XySubFilter.

**Comment by clsid2** [comment]
That functionality only works with the internal subtitle renderer.

You can set a delay in XySubFilter options.

**Comment by MatiasMovie** [comment]
do you plan to add such functionality in the future?

**Comment by clsid2** [comment]
No plans. But anyone can submit a patch for this.

**Comment by LazyGeniusMan** [comment]
hi, could anyone do this or help me?, i kinda have idea how to implement this but i have very limited experience in cpp. I dont even sure how to check whether XySubFilter is selected or not :(. is it `if (CAppSettings::SubtitleRenderer::XY_SUB_FILTER)` ?, also i dont know how to build and test whether my code is working or not

The idea is to override default F1 & F2 action in `src\mpc-hc\MainFrm.cpp` if XySubFilter is selected. The part that will be change in the file is:
```
        int newDelay;
        int oldDelay = m_pCAP->GetSubtitleDelay();
        int nDelayStep = AfxGetAppSettings().nSubDelayStep;

        if (nID == ID_SUB_DELAY_DOWN) {
            newDelay = oldDelay - nDelayStep;
        } else {
            newDelay = oldDelay + nDelayStep;
        }

        SetSubtitleDelay(newDelay);
```
If XySubFilter is selected, instead of run `SetSubtitleDelay()` we will change XySubFilter timing setting in registry `HKEY_CURRENT_USER\Software\Gabest\XySubFilter\Timing` using [RegOpenKeyEx(), RegGetValue(), RegSetKeyValue(), and  RegCloseKey() funtion](https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-functions?redirectedfrom=MSDN),  the registry key is `subtitle_delay`. The `newDelay` (KeyValue) need to be converted to hexadecimal before push to registry. `int oldDelay` value is obtained from `subtitle_delay` registry KeyValue and need to be converted to integer.

**Comment by clsid2** [comment]
You can check how it is done in MPC-BE:
https://sourceforge.net/p/mpcbe/code/HEAD/tree/trunk/src/apps/mplayerc/MainFrm.cpp

m_pDVS holds reference to DirectVobSub interface when that is part of filter graph. That interface is used by VSFilter/XySubFilter.

As you can see it is also used for making other subtitle functionality compatible with those external filters. Such as drag&drop, download, and the contents of the subtitle section in the play menu. So ideally those changes are ported as well.
