### ISSUE TITLE
Dark theme has small bug on win 11

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#2141]
Top menus and right click menus are not rounded.
![Screenshot (30)](https://github.com/clsid2/mpc-hc/assets/98865389/74156de2-dba4-4ea5-91c6-04009db8c999)

**Comment by clsid2** [comment]
That is not a bug.

Dark theme uses our own custom drawing.

**Comment by Aleksoid1978** [comment]
This can be done by calling **DwmSetWindowAttribute()** with the **DWMWA_WINDOW_CORNER_PREFERENCE** + **DWMWCP_ROUNDSMALL** options.

**Comment by clsid2** [comment]
@adipose

**Comment by bibsp** [comment]
**If** adipose is interested then one more thing is there. The separators between the menus are not grey. If you make them grey it will match windows 11 theme as well as it will look good. And arrows are bigger. **Light theme is perfect.**

![Screenshot (33)](https://github.com/clsid2/mpc-hc/assets/98865389/51cf8ee9-8626-4a0a-bd2f-65e1e1eee3d4)
![Screenshot (34)](https://github.com/clsid2/mpc-hc/assets/98865389/b3d70c0e-cd01-4505-af8f-e110d96dde1c)

**Comment by DRSDavidSoft** [comment]
Would like to see this happening in MPC-HC! ❤
I'll be working on minor tweaks like this in #3403

**Comment by DRSDavidSoft** [comment]
I believe fixing this issue requires some minor tweaks to the custom drawn menus as well, see:

![MPC-HC Rounded Corners using DWMA](https://github.com/user-attachments/assets/c7cebe00-fe13-43cf-acd9-05781009acef)

It looks like the custom shadows are not rounded. Also, the selected/hover item requires rounded corners for the background as well.

I'm testing the code below:

```
LRESULT CALLBACK CBTProc(int nCode, WPARAM wParam, LPARAM lParam)
{
    if (nCode == HCBT_CREATEWND)
    {
        HWND hwndMenu = nullptr;
        EnumWindows([](HWND hwnd, LPARAM lParam) -> BOOL {
            TCHAR className[256] = {};
            GetClassName(hwnd, className, ARRAYSIZE(className));
            if (_tcscmp(className, _T("#32768")) == 0) {
                *(HWND*)lParam = hwnd;
                return FALSE; // Stop enumeration
            }
            return TRUE;
        }, (LPARAM)&hwndMenu);

        if (hwndMenu) {
            DWORD dwAttribute = 2; // DWM_WINDOW_CORNER_PREFERENCE_ROUND
            DwmSetWindowAttribute(hwndMenu, 33, &dwAttribute, sizeof(dwAttribute)); // 33 = DWMWA_WINDOW_CORNER_PREFERENCE
        }
    }
    return CallNextHookEx(g_hCBTHook, nCode, wParam, lParam);
}
```

However, I'm thinking of another approach, why use custom drawn menus on Windows 11 at all, since it supports native dark mode, which looks nice?

I think it makes more sense to completely disable the custom drawn menus on Windows 11, and instead just apply the native dark mode.

Which route do you think is preferred?

**Comment by bibsp** [comment]
@DRSDavidSoft Looks good. But if you are willing to enable rounded corners, you should enable this in both light and dark themes.

Because in past light theme had rounded corners.
But later developer (most probably **adipose**) removed rounded corners from light theme to make both the themes identical.

**Comment by adipose** [comment]
> [@DRSDavidSoft](https://github.com/DRSDavidSoft) Looks good. But if you are willing to enable rounded corners, you should enable this in both light and dark themes.
> 
> Because in past light theme had rounded corners. But later developer (most probably **adipose**) removed rounded corners from light theme to make both the themes identical.

I didn't remove any corners, but I believe that I extended the custom theme to the light mode, which probably had that effect.

**Comment by DRSDavidSoft** [comment]
@adipose Hmm, so my original assumption is not correct, in the new MPC-HC update, **both** the dark and light versions of the menu are custom drawn.

![Image](https://github.com/user-attachments/assets/06d1d1c7-6c56-470b-9e13-44b36fff40a1)

This wasn't a major issue back in Windows 10, because the custom drawn menus look very similar to Windows 10's native ones, but in Windows 11, that's not quite the case.

Assuming that we like to update the design to have rounded corners (as well as fix other aspects to make it look like native Windows 11 menus), we have two options:

- Continue implementing the DWMA rounded corners, then work on the custom draw code to look nicer on Windows 11
- Revert back to native menus (no custom draw code)

There are some other themed controls as well (like buttons on forms) that also don't look nice on Windows 11 since they're not rounded.

There's also the third option to forget about it and basically keep the current Windows 10 looking theme as is.

I'm interested to know everyone's opinion before I continue.

One more thing; I'm very novice to MFC/AFX theming and the way MPC-HC is using it, so I don't expect myself to be well versed in editing those parts. But if adipose is interested in tweaking the theme, I'd certainly appreciate any help I can get.

**Comment by DRSDavidSoft** [comment]
This is kind of off-topic, but using the approach that I'm going with you can also achieve some nifty blurred-behind effects on Windows 11, if anyone's interested with that at all:

![Image](https://github.com/user-attachments/assets/397bfa54-55a7-4d42-8939-246f0185b555)

**Comment by bibsp** [comment]
@DRSDavidSoft No doubt this looks fantastic. But this app itself is a classic looking app. It's not like latest windows media player.

On a classic desktop app if you add a modern transparent menu, will it look good? It will be a mismatch kind of thing. In my opinion a classic context menu is better choice.

**Comment by DRSDavidSoft** [comment]
> On a classic desktop app if you add a modern transparent menu, will it look good? In my opinion a classic context menu is better choice.

Exactly. I don't think MPC-HC should ever have this, but it was interesting to try out! Also, I'm working on a private extension to MPC-HC (for my own use case), I guess something like this could better live there.

I'm trying to bring out my personal "tweaks" and improvements to the main MPC-HC codebase, hopefully @clsid2 would see it soon and merge it.

(Sidenote, I'm currently working on internal API aspects of projects to port them out of my fork back to the main repo, in the meantime I'd love to address the look and feel of the menus, but for sure I'll need @adipose's (and maybe even @Aleksoid1978's) advice and help to submit some good PRs)

**Comment by Aleksoid1978** [comment]
> This is kind of off-topic, but using the approach that I'm going with you can also achieve some nifty blurred-behind effects on Windows 11, if anyone's interested with that at all:
> 
> ![Image](https://github.com/user-attachments/assets/397bfa54-55a7-4d42-8939-246f0185b555)

Looks interesting, waiting for the code :)

**Comment by adipose** [comment]
I don't object to rounded corners if people like them. But the original theme is a windows 10 Explorer clone.  Windows 11 menus are not my favorite.

Maybe rounded can be an advanced option.  Windows 11 theme maybe one day.
