### ISSUE TITLE
Movie playback fails from mapped samba share after resuming from suspend

### ISSUE THREAD

**Issue by RenHoekNL** [clsid2/mpc-hc#2197]
I'm playing a movie from a mapped samba share (so a it's a drive letter). I pause playback, suspend the machine, resume the machine and then resume playback.

It looks like what was cached is played, but as soon as it runs out, the timeline indicator jumps to the end and playback stops.

I assume re-opening the file fails or is skipped. The mapped network drive is available.

The expected behavior is that the movie just resumes play without issue.

> 
> MPC-HC (Nightly, 64-bit)
> ------------------------
> 
> Build information:
>     Version:            2.0.0.5 (22dccf89a)
>     Compiler:           MSVC v19.29.30147
>     Build date:         Jan 22 2023
> 
> LAV Filters:
>     LAV Splitter:       0.77.1.2
>     LAV Video:          0.77.1.2
>     LAV Audio:          0.77.1.2
>     FFmpeg compiler:    MinGW-w64 GCC 12.2.0
> 
> Operating system:
>     Name:               Windows 10 (Build 22H2)
>     Version:            10.0.19045 (64-bit)
> 
> Hardware:
>     CPU:                Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
>     GPU:                NVIDIA GeForce RTX 2070 SUPER (driver version: 31.0.15.3179)
>

**Comment by clsid2** [comment]
The actual code that deals with file access is in FFmpeg (from LAV Filters) and thus outside of the player. I can't fix this and don't expect it to be fixed by FFmpeg either. Suspending must be causing the file handles to become invalid.

Workaround is to press Ctrl+E (file reload) before resuming playback. The player has options to remember playback position.

In fact, the player even has an option to reload automatically.
Options > Advanced > ReloadAfterLongPause
