### ISSUE TITLE
Mediainfo tab not showing up in properties the first time opening properties

### ISSUE THREAD

**Issue by bacondither** [clsid2/mpc-hc#2322]
Mediainfo tab not showing up in properties the first time opening properties.
Opening properties a second time or more and the mediainfo tab shows up.
Reverting pullrq #2308 fixes the issue for me.

**Comment by clsid2** [comment]
```
MediaInfoDLL::MediaInfo mi;
if (mi.IsReady()) {
```
After first line both `Handle` and `MediaInfo_Module` have a value. But IsReady which checks these values return false. Weird.

Edit: fixed it by adjusting `IsReady()`

ToDo note: I also noticed that `LoadDuration` is getting called when opening a file from recent file menu. Which is pointless since we are opening the file. LoadDuration should be limited to file that are appended and not directly played after adding.

**Comment by bacondither** [comment]
Yep works fine now.
