### ISSUE TITLE
harmless dark theme glitch

### ISSUE THREAD

**Issue by Rikk** [clsid2/mpc-hc#2374]
Hi
There is a harmless glitch that happens on dark theme when you click a button that resets ComboBoxes' values. In this example, when you click 'Default' button the visual style of all comboboxes is changed; when the dialog is reopened, normal style is restored.

![darktheme-combobox-glitch](https://github.com/clsid2/mpc-hc/assets/2916485/9b856295-e9d7-4fb6-811a-a54a30f414e0)

**Comment by adipose** [comment]
I don't see anything in your screenshot that shows what you are describing.  What "default" button?

**Comment by adipose** [comment]
I see it now in the subscreen.

![image](https://github.com/clsid2/mpc-hc/assets/3324395/a212bc92-9aa0-4021-ab82-bf1223376cde)

**Comment by adipose** [comment]
https://github.com/Aleksoid1978/VideoRenderer/pull/108

This would solve it.  The issue is that no erase or redraw signal is received from the video renderer property page.

Furthermore, CBN_SELCHANGE isn't reflected to the combobox when done through CB_SETCURSEL, even though it is when clicking manually.

**Comment by Rikk** [comment]
It doesn't happen only in MPCVR settings, but also in our Audio Renderer settings, and possibly more places with such kind of reset mechanism.
I may be wrong, but it seems the dark theme is where we are missing a refresh. Look: after you click the button and the visual changes, if you mouse over the comboboxes they will paint themselves again. Imo, it indicates a transition between comboboxes' visual states is not happening automatically.

**Comment by adipose** [comment]
> It doesn't happen only in MPCVR settings, but also in our Audio Renderer settings, and possibly more places with such kind of reset mechanism.
> I may be wrong, but it seems the dark theme is where we are missing a refresh. Look: after you click the button and the visual changes, if you mouse over the comboboxes they will paint themselves again. Imo, it indicates a transition between comboboxes' visual states is not happening automatically.

No message is received by the combobox when CB_SETCURSEL is sent.

The problem is that sometimes windows repaints the widgets in an "optimized" way and doesn't actually send the WM_PAINT message.  In this case no WM_PAINT is ever sent.  For other scenarios, I can hijack the event and force it to repaint.  I have done many like that, but in this case, the code is inside MPCVR, so I cannot do it.

The event to trap would be `CBN_SELCHANGE`, though it is not sent when the control is manually updated as opposed to the user. So I do not get a paint message nor do I get notified the dropdown even changed.  There's nothing to be done.

**Comment by adipose** [comment]
This will fix it for mpc-hc code (including MPC-AR) that uses explicit themed subclass, provided `.SetCurSel()` is used:

https://github.com/clsid2/mpc-hc/pull/2378

**Comment by Rikk** [comment]
Ok
Just thinking loud... I see the comboboxes have, in light themes (classic or modern), 3 states: "normal", "mouse over" and "pressed". But in the dark theme, however, there's a fourth: the one that appears when a reset button is used. Why there is this difference and what causes it? ~~I suppose we can't disable one of these states even if we wanted, right?~~

**Comment by adipose** [comment]
> Ok
> 
> Just thinking loud... I see the comboboxes have, in light themes (classic or modern), 3 states: "normal", "mouse over" and "pressed". But in the dark theme, however, there's a fourth: the one that appears when a reset button is used. Why there is this difference and what causes it? ~~I suppose we can't disable one of these states even if we wanted, right?~~

The issue is not really *state* but windows messages vs optimized redraw.  

Normally a widget gets a WM_PAINT message when something invalidates it.  Mouse over, click, key-stroke, or data change.  The developer can process these events by subclassing or monitoring the windows event loop.

For some reason Microsoft has decided that dropdown data changes don't need a paint message.  *But* they are still redrawing the area in closed-source win32 code.  The result is they may honor currently selected colors but the redraw is done in some undocumented way.

It's an issue with a bunch of common control widgets.  Static, combo box, edit an others.  As I mentioned there are workarounds.

Fact is Microsoft barely cares to support custom themed win32 widgets. It's unlikely to improve as they push toward metro.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2382

This should workaround the issue for MPCVR.
