### ISSUE TITLE
Improve Save Image Filename for online streams

### ISSUE THREAD

**Issue by SomewhatDamaged** [clsid2/mpc-hc#2522]
## Issue
When taking a snapshot (Default F5) it prepends the username and password of the current RTSP stream to the filename. 
Example:
`rtsp://admin:n%7D%29%3D%23W%40V%3BKWVL%3Dd%5E%297%2ayN9%2B~sqh9Mji%29@192.168.1.140:554`
`admin_n})=#W@V;KWVL=d^)7_yN9+~sqh9Mji)@192.168.1_snapshot_00.02.771.jpg`

## Expected
Image screenshots shouldn't leak such data. Perhaps chop such stream names at the `@`?
Example:
`192.168.1_snapshot_00.02.771.jpg`

### MPC-HC (64-bit)
---------------

Build information:
    Version:            2.1.4 (c82061aef)
    Compiler:           MSVC v19.29.30152
    Build date:         Jan 15 2024

LAV Filters:
    LAV Splitter:       0.78.0.1
    LAV Video:          0.78.0.1
    LAV Audio:          0.78.0.1
    FFmpeg compiler:    MinGW-w64 GCC 13.2.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                AMD Ryzen 7 3700X 8-Core Processor
    GPU1:               NVIDIA GeForce GTX 1070 (driver version: 31.0.15.3623)
    GPU2:               NVIDIA GeForce GTX 1070 (driver version: 31.0.15.3623)
    GPU3:               NVIDIA GeForce GTX 1070 (driver version: 31.0.15.3623)

**Comment by xLn2** [comment]
https://github.com/clsid2/mpc-hc/issues/995 is a similar problem that can be solved with abbreviation.

**Comment by clsid2** [comment]
Maybe all online streams should just use a generic filename for screenshots.
E.g. `webvideo_[timestamp]_snapshot_[videotimestamp].jpg`

**Comment by xLn2** [comment]
I think there should be distinction between online streams (have duration) and live streams (no have duration). Since live streamings have no duration, [videotimestamp]s are somehow pointless to me. The current system time [timestamp] as a constant value makes more sense.

Online stream: [Big Buck Bunny, Sunflower version](http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4)
Live stream: [Free iptv](https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8)

**Online stream: Big Buck Bunny, Sunflower version**
Advanced settings, {SavelmagePosition, SavelmageCurrentTime _opposite of default_} bbb_sunflower_1080p_60fps_normal.mp4_[2024.02.05_15.23.41]

Advanced settings, {SavelmagePosition, SavelmageCurrentTime _default settings_} bbb_sunflower_1080p_60fps_normal.mp4_snapshot_00.15.372


**Free iptv first live stream: Kanali 7 Ⓢ**
Advanced settings, {SavelmagePosition, SavelmageCurrentTime _opposite of default_}
1200_1.m3u8_[2024.02.05_15.58.42]

Advanced settings, {SavelmagePosition, SavelmageCurrentTime _default settings_}
1200_1.m3u8_snapshot_10.26.495

**Findings/suggestions:**
"_snapshot_" shouldn't depend on SaveImagePosition state[on].
If media has no duration just use {`SavelmagePosition=False, SavelmageCurrentTime=True`}.
On playlists streams mostly have significant list names. For playlist files it can be used as filename.
If clip name is available, it can be used as filename (Big Buck Bunny, Sunflower version _has_)

**Comment by adipose** [comment]
>"snapshot" shouldn't depend on SaveImagePosition state[on].

Fixed.

>If media has no duration just use {SavelmagePosition=False, SavelmageCurrentTime=True}.

Done.

>On playlists streams mostly have significant list names. For playlist files it can be used as filename.

Done, but note that if it detects a youtube url, including the twitch url used in your playlist (twitch.tv/abcnewsal), it uses a different method to get the name.

>If clip name is available, it can be used as filename (Big Buck Bunny, Sunflower version has)

Done, but only if save extension is disabled.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2813

**Comment by clsid2** [comment]
For local files I think it should always use the filename, not the title.

**Comment by adipose** [comment]
OK, added that now.
