### ISSUE TITLE
ToDo: Better sorting of subtitle search results

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2567]
They are currently only sorted based on preferred language.

After that it could sort those results based on score, and for equal score then further based on download count. That should make it easier to find best match.

Perhaps low score results (<=16) should be filtered out when a good score (>=21) is available for a language?

**Comment by xLn2** [comment]
> Perhaps low score results (<=16) should be filtered out when a good score (>=21) is available for a language?

Instead of completely removing it from the list, how about painting it in accordance with the passive color scheme of the theme in use?

For me, one of the most important criteria for finding suitable subtitles is the frame rate at which the subtitle is prepared to match. With minor adjustments they can often be made to match the video. But in cases where the frame rate is different (i.e 23.976 vs 25) the synchronization naturally breaks down after a while.

Do we able to know the frame rate at which the subtitle is specified as appropriate at the provider? Do you insterest to adding this value as a separate column, or are inappropriate values already automatically filtered out?

**Comment by clsid2** [comment]
I am adding FPS column.

**Comment by clsid2** [comment]
I am working on a sorting patch.
