### ISSUE TITLE
When saving thumbnails, the file size unit is encoded according to the system language, not the interface language

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2584]
![thumbcharencoding](https://github.com/clsid2/mpc-hc/assets/3073922/4977eb07-6cc6-4853-b5e3-6fee308ed2ff)
![image](https://github.com/clsid2/mpc-hc/assets/3073922/7246fc4f-6ed8-4b0a-bc9e-0e2ee1a7b6b0)

I wanted to report that I have seen a couple of examples where the file size section is in Cyrillic but the rest of the text is in English. There may also be a problem with the separator, it uses from Windows regional settings decimal and thousand separator.
GB - MB etc. Units are encoded according to first MPC-HC installation (high probably)
This problem is also present in Mpc-be.

**Comment by adipose** [comment]
How to reproduce this?  Simply running with ACP 1254?

**Comment by xLn2** [comment]
You can change Mpchc interface language to i.e Russian and
* GB unit will be latin
* Thousand and decimal seperator will use windows regional settings <there are some system settings for it>

But not sure which are related first mpchc install language or is it irrelevant here.

![images (2).jpeg](https://github.com/clsid2/mpc-hc/assets/3073922/9d7d61e2-f589-4992-81d4-23e7978d5715)

**Comment by adipose** [comment]
What's your default subtitle font?

**Comment by xLn2** [comment]
Roboto or Segoe Ui. But one of the screenshot taken from web so I am not sure their default subtitle font.

**Comment by adipose** [comment]
I could not reproduce the issue of Cyrillic characters.  But I did learn a few things:

1. Yes, numbering format is using system locale.  That seems fine to me.  The user has chosen their locale for a reason.  I do recognize that if a user cannot change their locale but wants to override using mpc language, we support it to a point.  Perhaps using a matching locale for the language is something that would be easy to add.  But it seems fairly low priority.  I believe windows locale settings can be set per user anyway.
2. The way this text is rendered to the image is the internal subtitle renderer. So we can expect a few possible wrinkles: 
    a. The font used will be the subtitle font
    b. ANSI codepage may matter, but I wouldn't think so

If the font doesn't have the typical letter in the G and B positions, I guess that could result in the weird pic you had above.

**Comment by adipose** [comment]
It actually uses the default windows font, just realized.

**Comment by adipose** [comment]
Well, anyway, it uses StrFormatByteSizeW which doesn't say anything about localization.  But evidence suggests it supports it:

https://learn.microsoft.com/ru-ru/windows/win32/api/shlwapi/nf-shlwapi-strformatbytesizew

This surely has to be based on the OS, though.  What's odd is, I couldn't reproduce it even on with my language changed to Russian.

**Comment by adipose** [comment]
I reproduced it now.  It is based on region rather than language.

On the other hand, the "bytes" above comes from string IDS_THUMBNAILS_INFO_FILESIZE which we translate based on the mpc-hc language.

I can't say I really care much.  But here's one way we could solve it.  Instead of using `StrFormatByteSizeW` we use something else (I found code for wine for example that is not region aware).  Then we have the translators provide translators for GB=ГБ and such.  This would allow it to be consistent.

@clsid2 , I bet I can guess your opinion.

**Comment by xLn2** [comment]
People who does same operations (English thumbnails) should not result differently by their Windows local format settings imo.

Somekind of array/table for mpchc localization for numbering format might be helpfull. 

i.e
Language -- Thousands seperator -- Decimal seperator
English -- " " -- "."
Turkish -- "." -- ","

I will update list and stylise when I have access computer so if there is easy solution for using these, and making these as translatable variable for future cases might be nice.
YYY_RR_DECIMALSEPERATOR
YYY_RR_THOUSANDSEPERATOR

**Comment by clsid2** [comment]
We are not going to translate separators.

**Comment by adipose** [comment]
There are four things that affect translations:

1. Windows language: affects cancel/ok buttons on various forms throughout MPC-HC regardless of translation used
2. Windows region (windows 10-11): affects the KB/MB/GB postfixes used by StrFormatByteSizeW
3. Region formats (this has been around since at least NT4): affects date and time formats and can be changed regardless of region
4. MPC-HC translation language
5. Subtitles are also potentially affected by font, ansi encoding, and opentype hint language

Your best best is to align these all to your use case and hope everything looks good.  Trying to mix and match is going to lead to disappointment.  But if you can show me how, despite your best attempt, you cannot get them to align due to a fault in MPC-HC, I of course will listen and see if it can be improved.

This is the first time I have seen where the windows API is being called by MPC-HC directly to provide what is essentially a translation of an abbreviation, so it's a bit of a gray area.  Unfortunately, unless we replace that API call with something else it will be "pre-translated" which makes it more difficult to adjust.  On the plus side, what you are getting is what you "asked" Windows to provide.

One thing I did not like when I observed it was the default buttons defaulting to Windows languages while the rest are honoring the MPC-HC translations.  This is most likely easy to solve.  It happens on MPCHC options dialogs.  Those standard buttons can be easily identified as they use common IDs.
