### ISSUE TITLE
[Bug] Remember external playlist position bug introduced in 2.1.5

### ISSUE THREAD

**Issue by WildS0ft** [clsid2/mpc-hc#2630]
There seems to be a bug introduced in 2.1.5 in regards to resuming where a playlist position was left off.

**Current behavior:** 2.1.5 & 2.1.6 (x64)
When deleting entries in an opened playlist before the current selection and then saving said playlist to file, the next time the playlist is opened it will skip ahead and play the file corresponding to the same amount that was previously deleted.

**Expected behavior:**
When opening a playlist the player should start on the file in the list where it was last left off as long as 'RememberExternalPlaylistPos' is set to 'True' (default).

**Steps to reproduce the problem:**
1. Open a .mpcpl playlist containing multiple entries.
2. Skip ahead a few and play that file.
3. Delete some or all of the previous entries in the list.
4. Right click inside the playlist and select 'Save'.
5. Close MPC-HC.
6. The next time you open the same .mpcpl playlist it will jump ahead and start playing the file equal to how many entries you previously deleted instead of the file where it was last left off in the list.

**Comment by adipose** [comment]
To understand, you are expecting that you can change a playlist, then save the playlist, and have it remember the current position at the time of saving, so that you can load the playlist later and have it remember?

This seems like a reasonable expectation, but the way that it works is it only records position for unaltered playlists.  Once you alter it within mpc-hc, it stops trying to track the position, as it assumes the playlist is fixed and your position doesn't apply anymore.

A solution might be to save position when a playlist is saved, for the destination filename chosen (as it may differ).

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2643

I think this should solve it.
