### ISSUE TITLE
Issue when using MPC-HC and SubtitleEdit at the same time.

### ISSUE THREAD

**Issue by USSWashington** [clsid2/mpc-hc#2684]
I don't know if there's a “cross-post” on GitHub, but I think it's a good idea to contact both developers, as there might be a solution.

Basically, I can't run both programs at the same time. Playing a video on MPC-HC (any video) force closes SE, with no resulting error messages. More info can be seen in the OG issue report here: https://github.com/SubtitleEdit/subtitleedit/issues/8055

But for the sake of brevity:
Video package: K-Lite Codec Pack (18.2.4) Full
Video player: MPC-HC with MadVR
SubtitleEdit Version 4.04 with MPV embedded video player
Win11 build 22631.3296

I tried playing videos using the native windows “Movies” program and that didn't crash SE, I am more inclined to think that there's a conflict between SE and MPC-HC/ K-Lite Pack.
[klcp_codec_log.txt](https://github.com/clsid2/mpc-hc/files/14731051/klcp_codec_log.txt) ← log file.

**Comment by clsid2** [comment]
This is NOT a bug in MPC-HC so there is nothing I can do about it.

I suspect your system has insufficient graphics ram to handle two videos at same time, at least with your current rendering settings.

Try different renderer instead of Madvr. If that solves problem, then try lowering all the queue settings in Madvr to reduce its memory usage.

You might be able to find a SE crash log in Windows Event Viewer.

**Comment by USSWashington** [comment]
At least wait for me to reply, man!
As for changing the renderer I tried the MPC Video Renderer and that didn't fix it, as for the GPU ram, I have 4GBs and Task Manager reports around 15% of usage playing a 1080p video. 
I found some info in the Event viewer and I shall inform the dev about that, so thanks for pointing me in that direction.
