### ISSUE TITLE
Subtitle downloader does not deselect lines when unchecking

### ISSUE THREAD

**Issue by koitsu** [clsid2/mpc-hc#276]
There's some odd UI behaviour in the Subtitle downloader, where when *unchecking* a selection does not actually de-select it in the list.  Reproduction steps on Windows 7 SP1 x64, MPC-HC 1.9.1:

1. Launch MPC-HC + load a video
2. File -> Subtitles -> Download Subtitles...
3. Wait for the search results to finish (need at least 2 subtitles to demonstrate this)
4. Left-click on a subtitle's checkbox, i.e. `[x]`
5. Left-click on another subtitle's checkbox, i.e. `[x]`.  Now two subtitles will be selected (as if you had selected both holding Ctrl or Shift)
6. Uncheck the box of a subtitle chosen in steps 4 or 5
7. The box will uncheck, but the selection of the item itself does not disappear (i.e. remains selected)

See attached screenshot for an example.  Here I `[x]`d the Croatian subtitle, then the English subtitle, then the Hebrew subtitle -- then unchecked the English subtitle, but the selection bar for it remained.

![Untitled](https://user-images.githubusercontent.com/8430773/74617292-4264fe00-50e1-11ea-80c4-bcb8bc2ff1e2.jpg)

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/278

I think this regression was due to using CPlayerListCtrl in more areas than it was before the Dark Theme was created.  

This line is highlighting the current row whenever it gets clicked (not necessarily checked!):

![image](https://user-images.githubusercontent.com/3324395/74687443-44829780-5189-11ea-8186-5ea9dfacc35b.png)

Since the list in this dialog allows "multiple selection," these highlights stacked up.  I changed that property and it seems to be working correctly, now.

A better fix might be changing CPlayerListCtrl to highlight the current row and clear the highlight from the old row, when LVS_SINGLESEL is set.
