### ISSUE TITLE
Retake focus from playlist

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#2811]
Show playlist and click on it to give it focus.

If you now click on toolbar/statusbar/menu, then focus stays on playlist. Meaning that for example pressing O for options does not respond. Only clicking on video area restores focus to mainframe.

**Comment by Aleksoid1978** [comment]
You just need to transfer all hotkeys that are not used in the playlist to the main window.

**Comment by adipose** [comment]
I seem to recall the playlist hotkeys don't all escape the playlist due to being list ctrl keys.

This sounds like the opposite issue.  Not sure we need focus for hot keys, but other arrow keys and stuff also require focus.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/issues/2709

This is related.  I did take a look at `PreTranslateMessage` from MPC-BE and it's about 200 lines compared to <15 for mpc-hc.  I can see it's making a lot of effort to piece out the various keystrokes, and has different logic depending on active edits in the playlist.

It seems like an ok solution.  I can see if the focus solution is possible, though.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2867

**Comment by clsid2** [comment]
> #2709
> 
> This is related. I did take a look at `PreTranslateMessage` from MPC-BE and it's about 200 lines compared to <15 for mpc-hc. I can see it's making a lot of effort to piece out the various keystrokes, and has different logic depending on active edits in the playlist.
> 
> It seems like an ok solution. I can see if the focus solution is possible, though.

I think redirecting keystrokes would be useful to try. Perhaps start with just a few common single key shortcuts such as O (options) and Spacebar (play/pause) as a test. Should of course only redirect when not editing a playlist entry title.

**Comment by adipose** [comment]
> > #2709
> > This is related. I did take a look at `PreTranslateMessage` from MPC-BE and it's about 200 lines compared to <15 for mpc-hc. I can see it's making a lot of effort to piece out the various keystrokes, and has different logic depending on active edits in the playlist.
> > It seems like an ok solution. I can see if the focus solution is possible, though.
> 
> I think redirecting keystrokes would be useful to try. Perhaps start with just a few common single key shortcuts such as O (options) and Spacebar (play/pause) as a test. Should of course only redirect when not editing a playlist entry title.

Interestingly, the first test I did, this was already a problem.  In my playlist, I had "opaque subtitle."  I hit the "O" key and observed that it immediately highlighted that entry (because it starts with "O").  I then realized that one can type in the names of entries and it will jump in the playlist to that entry.  Other obvious keys that work are up/down arrows, page up/down, home/end, delete.  F2 does not work, although I would like it to, similar to Explorer.

We could disable the typing of entries in the playlist, and that would open up other potential hotkeys.  I already allow any hotkeys that involve `<alt>`, but probably `<ctrl>` could be added as well, provided we excluded behavior for edits.

One other thing.  It's a minor issue, but `<shift>` is actually used by the playlist. If you are typing to jump to an entry, and the entry contains a symbol that requires shift to type (like _, @, (, ), +, etc.), you need to pass that keystroke to the playlist.

**Comment by clsid2** [comment]
I am not sure how many people would actually use a letter key to seek within a playlist. It doesn't seem useful to me for most playlists.

Maybe an actual proper seek function (Ctrl+F) to seek for a substring would be a cool future addition.

**Comment by adipose** [comment]
Probably not many, but it shows how keys have behaviors that would be lost by allowing shortcuts.  I personally had no idea it did that, but it's actually a pretty handy behavior (and mirrors what Windows Explorer does in terms of jumping to an entry).

Perhaps we can define what keys we _do_ want to restrict, like arrows, pg up/down, home, end, and delete?

**Comment by clsid2** [comment]
With restrict you mean handle them in playlist? Yes, those are ok.

I guess there are few left that can be forwarded. Ctrl may also be used for copy/paste actions of text.

Now that focus issue is fixed, it is much less of a problem, so I a going to close this one.
