### ISSUE TITLE
little space for text

### ISSUE THREAD

**Issue by Lukjan41** [clsid2/mpc-hc#2816]
pleasse fix
![Bez tytułu](https://github.com/clsid2/mpc-hc/assets/163265642/41f486a8-1030-443f-ac78-2d9b48f7d512)

**Comment by adipose** [comment]
Will take a look.

**Comment by Lukjan41** [comment]
thank

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/5b4f6b95-9e12-4314-800f-704515674e46)

Second problem seems better.  For the first, it's a bit of an ugly one.  That field is meant to have numbers in it, but we put "auto" sometimes.  But making it wide enough to fit _automatyczny_ is going to look odd.

Making it dynamic won't fix it because it doesn't know about that specific text.  Maybe I can write a special workaround, but better would be a shorter word...

**Comment by clsid2** [comment]
Just use "auto" or "autom." as translation. It is obvious what it means in this situation. In English the proper word is automatic, and we even use the short form there.

We are not going to jump through hoops to make super long translations fit.

**Comment by Lukjan41** [comment]
ok, if it doesn't work, I'll change it to a shorter one
