### ISSUE TITLE
[Feature request] Skip buttons

### ISSUE THREAD

**Issue by narcolepticinsomniac** [clsid2/mpc-hc#292]
Appreciate your work here. Really digging the dark theme.

I've never understood the point of fast-forward and rewind. They're like a throwback to VCR days, only weirder since the audio is active, so you either wind up listening to the chipmunks or Satan himself.

A couple skip buttons for either direction, to actually integrate the "jump long/short forward/back" keypress functionality into the UI, would be a pretty sweet feature.

If you wanna make a significant jump in the timeline, you'll most likely click on the timeline, since it's easier to guesstimate based on duration, but smaller increments like 10-60 seconds are much more difficult to gauge.

**Comment by clsid2** [comment]
The internal audio renderer has pitch correction, which improves sound quality a non-standard speeds.

No buttons will be added. That would break existing custom toolbar buttons skins. I am not interested in that.

There are keyboard shortcuts for skip/jump.

**Comment by narcolepticinsomniac** [comment]
Worth a shot.

>No buttons will be added. That would break existing custom toolbar buttons skins.

Fair enough. Any chance you'd consider an option to replace existing fast-forward/rewind button functionality with a forward/back skip?

**Comment by clsid2** [comment]
No. I am not interested in implementing that.

You can seek with Arrow key (5 sec) and Alt+Arrow (20 sec).

**Comment by narcolepticinsomniac** [comment]
Also worth a shot. I'm aware of the shortcuts. Thanks anyway.

**Comment by adipose** [comment]
@clsid2 

I had an idea for a "modern" toolbar that works differently than the current one.  Basically the idea was to have individual image files for each button (could be zipped or stored in a single image like the current toolbar).

Images:
toolbar background/border
toolbar button
toolbar button (disabled)
toolbar button (hovered)
toolbar button (active)
action image1
action image2
...

This would allow us to add toolbar buttons as needed, with a new image only needed for each new action we add (should be rare enough).  And the toolbar could be customized to show or hide individual actions.

Finally, as a backup plan, if the current theme can't draw that toolbar button, we could supply a default using a standard unicode character or something that could be scaled easily to the size of the button.  Or buttons could be added with a text string, to do any action ("Zoom 50%").

I have been thinking about it since someone asked for the subtitles toggle button, which struck me as a good button to have on the main toolbar.

The modern toolbar could possibly be only an addon toolbar, as well, leaving the original entirely alone and only used for new buttons that don't work on the original.  Or we could make it backwards compatible to an extent by extracting images from the old toolbar image.

Anyway, if there is interest I could work on it, probably not for a while though.

**Comment by clsid2** [comment]
I don't think it is worth investing a lot of time in such a big change. All important functionality is already available in the menus and with keyboard shortcuts.

There are plenty of other small improvements that could be made, which will bring joy to a larger group of users. For example adding A-B repeat. If you want I could look over the old bug tracker and make a list with small feature requests that I think are interesting.

**Comment by adipose** [comment]
Sure, that's a good idea to add all the good requests to the bug tracker.

As for the toolbar, it's a bit of a project, but maybe not worth it, as you say.  However, the ability to add text/image buttons to the right of the existing toolbar might be fairly easy to pull off, and would allow people to put whatever custom actions they needed.

**Comment by narcolepticinsomniac** [comment]
![2ewhb1](https://user-images.githubusercontent.com/14100003/76176989-17724500-6189-11ea-8eec-75fe7d657dd7.jpg)

**Comment by clsid2** [comment]
That is a possibility. They could be named "quick action" buttons. Allow up to 3 extra buttons. In settings have a dropdown list for each button with all commands from Keys page. Button is displayed only when an action is selected. Tooltip shows the command description. Button texts could be simply "1" "2" "3".

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1002
