### ISSUE TITLE
If `FullscreenDelay`>0, Windows taskbar become visible when mouse on Mpc-hc seekbar on fullscreen

### ISSUE THREAD

**Issue by xLn2** [clsid2/mpc-hc#2991]
![svhOwgqmTt](https://github.com/user-attachments/assets/0bf0501d-1341-4b71-a847-82f347dfecc3)

**Comment by NBruderman** [comment]
@xLn2 did you test whether this one got fixed?

**Comment by xLn2** [comment]
Since the relevant commit came into effect after the last published test build, I will check it when the next test build is released. If I am late to report the result, please feel free to give your feedback.

**Comment by xLn2** [comment]
Still reproducible, taskbar just blink in the fraction of a second. I think Mpc-hc goes custom fullscreen or frameless window mode if FullscreenDelay>0.

There is some focus war when VideoPreview window disappear. 

![explorer_DAJiXCca6v](https://github.com/user-attachments/assets/2167f777-4833-4ae1-b395-f34a9e14a70a)

**Comment by adipose** [comment]
Recent test build:

https://mega.nz/file/1MhlgAbT#ymjBBBFEppQKK-6-iHw3GiyAGeqYmEfYuczFmSCut8g

**Comment by xLn2** [comment]
I tested 2.3.4.24 and 25 and it is still reproducible. Fast hover on and out seekbar with VideoPreview can trigger short amount of time taskbar blink.

**Comment by adipose** [comment]
The problem is caused by this commit: https://github.com/clsid2/mpc-hc/commit/43467b8486

@clsid2 , can you remember what that solved?  If I simply remove this line:

`m_wndPreView.SetWindowPos(&wndNoTopMost, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);`

It solves it.  I'm not sure why it needs to be removed from a hidden window but the commit suggests it's to do with LAVFilter window.

I have a few other ways I can solve it but they cause some flicker.  Now, what is weird is the issue only affects the fullscreen window that was cloaked during the fs operation.  It's similar to the other issue but both are caused by the "notopmost" flag.

**Comment by clsid2** [comment]
Based on the commit message I think it fixed an issue where filter property windows did not show properly after using the preview. Modal dialog does not set itself to topmost?

When hiding preview, setting it to `Bottom` z-order might work better than NoTopMost?

Maybe all z-order management could be moved to a central location. Then all player window handles can be used to order them relative to each other rather than using the generic position flags. Might be a big task and needs a lots of testing.

**Comment by clsid2** [comment]
Hmmm, `wndBottom` does not work and actually sets the main window to bottom position. That's weird. Edit: nevermind, it's mentioned in the API docs.

Removing the line does not seem to cause any obvious issues here.

**Comment by adipose** [comment]
> Hmmm, `wndBottom` does not work and actually sets the main window to bottom position. That's weird. Edit: nevermind, it's mentioned in the API docs.
> 
> 
> 
> Removing the line does not seem to cause any obvious issues here.

Yeah I found the same.  When a child window loses topmost, its parents do too.  And because of owner order, bottom probably takes parent to bottom.

I tried top but that didn't work correctly with the preview window.

**Comment by clsid2** [comment]
pushed the removed line

**Comment by adipose** [comment]
The following code is intended to restore topmost to the main window after the lose it.  It should no longer be needed, either:

```
        if (WindowExpectedOnTop()) {
            SetWindowPos(&wndTopMost, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
            //now that we have set the main window to topMost, its toolbars will have to be re-ordered as well
            for (const auto& pair : m_controls.m_panels) {
                CWnd* owner = pair.second->GetParentOwner();
                if (owner && owner->IsWindowVisible()) {
                    owner->SetWindowPos(&wndTopMost, 0, 0, 0, 0, SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
                }
            }
        }
```

**Comment by clsid2** [comment]
removed
