### ISSUE TITLE
Music coverart is really really small since upgrading to v2.3.4

### ISSUE THREAD

**Issue by echoxxzz** [clsid2/mpc-hc#2994]
Ever since upgrading to 2.3.4 when I open a music file the cover art is so small it's almost unrecognizable. If there is a new setting to restore the default behavior in 2.3.3 I cannot find it.

**Comment by NBruderman** [comment]
Already been fixed
https://github.com/clsid2/mpc-hc/issues/2990

**Comment by SkyMegatrends** [comment]
It's not fixed. It's still the same for me.

You have to drag and adjust the window size, play the next file, and it'll fit to the window.

But after you close the player and open the file again, the cover is back to being small like before.

I don't want to click "Remember last window size" because the resolution of the resolution of all cover art is not all the same.

The previous version could automatically adjust the resolution size to fit the window, even if you changed a value in "CoverArtSizeLimit".

**Comment by clsid2** [comment]
Are you using 2.3.4.17 ?

**Comment by SkyMegatrends** [comment]
I'm using version 2.3.4
![2 3 4 (2)](https://github.com/user-attachments/assets/3ca5443a-f7e3-47f3-b56c-5d20ed193b18)

**Comment by clsid2** [comment]
Well genius. That is the problem.
