### ISSUE TITLE
Problem with Dolby Atmos- MPC plays multichannel instead of Atmos

### ISSUE THREAD

**Issue by Northimus** [clsid2/mpc-hc#3003]
I can't get Dolby Atmos to work, I read that MPC supports it natively, but when I play Dolby Atmos video file it just plays multichannel instead of Atmos. Something is broken it seems?

**Comment by clsid2** [comment]
You need to enable bitstreaming in the audio decoder settings.

And of course you need a receiver that supports Atmos.

**Comment by Northimus** [comment]
> You need to enable bitstreaming in the audio decoder settings.
> 
> And of course you need a receiver that supports Atmos.

I don't see option to enable bitstreaming in MPC HC, and of course my receiver supports Atmos.

**Comment by clsid2** [comment]
options > internal filters > audio decoder

**Comment by Northimus** [comment]
Thank you, found it and got it to work but there is some kind of sound, image stutter, I have no idea why.

**Comment by molitar** [comment]
Northimus, for your stuttering problem try these settings this is the way I got Dolby Atmos to work with no issues at all.

Update for configuration settings as the new mpc-hc 64 bit has changed. For one it has newer LAV so here is the updated settings.

**LAV Audio Splitter:**

**Audio Settings Tab:**
Dolby-Digital Plus (eAC)
DTS
DTS-HD
Force Max DTS-HD
Expand 6.1 to 7.1
All output formats checked

**Mixing Tab:**
Mixing Enabled
Mixing Configuration: 7.1
Matrix Encoding: None

Also the settings FAQ in Dolby Access it 100% wrong!  You need to have both these settings enabled.

**Sound Settings:**

**Advanced Tab**
Enable/Check Allow applications to take exclusive control of this device
Eanble/Check Give exclusive mode applications priority

The FAQ says to uncheck these options but it is WRONG!  At least in Windows 10 as you will not get Dolby ATMOS in anything but Dolby Access.  The pros of enabling is you can get Dolby Access out of other applications that support Dolby ATMOS but when playing ATMOS audio other audio will not work.

**Comment by clsid2** [comment]
Dolby Access and bitstreaming Atmos are two different and unrelated subjects. You do not need Dolby Access or any other apps to do bitstreaming.

Allowing exclusive mode in sound settings is required to be ENABLED for all bitstreaming.

Mixing is irrelevant for bitstreaming, since the compressed audio is send to the receiver completely untouched. Receiver is responsible for all decoding/processing/mixing. Mixing settings only apply to formats that can not be bitstreamed, and which will be send as PCM. For old receivers with optical connection you need to set it to stereo.
