### ISSUE TITLE
Playing DTS core from a DTS-HD audio track makes video framerate go crazy (MKV video)

### ISSUE THREAD

**Issue by CiroConsentino** [clsid2/mpc-hc#313]
I think it started in latest MPC builds as it was working without issues before. Whenever I try to play a MKV video (AVC or HEVC encodes, 1080p and 2160p resolution) with DTS-HD audio track, the video framerate goes way up, like 50 fps or so instead of the 23.976 fps and the audio also plays in a faster speed. The speed playback rate in MPC is always at normal speed, it never goes up or down even when this bug is occurring.

I use "SPDIF" pass-thru via optical cable in audio settings since my audio receiver does the Dolby Digital / DTS decoding, but it only supports regular DTS and regular Dolby (no HD audio format or HDMI audio ports, only optical port). MPC plays the DTS core from the DTS-HD track, and that is what causes the problem. Perhaps this is a "LAV Filter" bug ?
If I extract the DTS core from the DTS-HD track, either remux it into the MKV file or as an external .dts file, and play the video, MPC plays it correctly and the video framerate stays normal.
I don't have .mp4 or any other video format to test this. Any help/suggestions are appreciated.

**Comment by clsid2** [comment]
Install the version that you were using before and test if that solves the problem.

This is the first time I see a report for this specific issue. It could be a sound driver issue. The reference clock for playback comes from the audio hardware/driver.

**Comment by CiroConsentino** [comment]
Ok, I'll try the old version and report back. I recently did a clean Win7 reinstall (hate Win10, don't ask...
), but device drivers are all the same, including the sound card driver. The only thing I changed is updating MPC-HC and LAV Filter.

**Comment by CiroConsentino** [comment]
I use the default video renderer. I tried with madVR render and the video framerate bug was happening as well.
But I fixed the problem. Older build (v1.83) worked fine, then I compared MPC settings and found out the "DTS" and "AC3" checkboxes in "Internal Filters" settings were unchecked. I enabled them and restarted MPC. 
Problem was gone, video framerate now stays at 23.976 fps and the DTS core from a DTS-HD track plays correctly. See attached pic. After my Win7 reinstall, those settings got unchecked somehow.
Thank you for the help :)
![mpc-dtshd-core-framerate-bug-fixed](https://user-images.githubusercontent.com/18468619/76700809-0ac68300-669a-11ea-9ced-edc3ad27cf72.jpg)

**Comment by sam0thius** [comment]
Hi and despite this thread being closed for a long time, just had to comment and thank CiroConsentino for writing about this issue here back in 2020! 

I do not have that many videos with DTS-HD MA sound track, but came across one few weeks back, and this very same issue that Ciro wrote about has been driving me nuts ever since. After countless hours messing around with AI and making various MadVR setting adjustments to no avail, found this post by chance, and issue was fixed by enabling all audio codecs with the MPC-HC Transform Filter list. Unsure why I had the AC3/... and DTS disabled with the mpc-hc interal filters from the first place, but just glad I got to fix the issue.
