### ISSUE TITLE
[ Enhancement ] Add more functionallity to the rarsource selection

### ISSUE THREAD

**Issue by Tsoccerguy3** [clsid2/mpc-hc#327]
As it stands , selecting a rar file to play opens a menu to select the file to play. The old functionality was it would know to play the video , avi , mkv , etc and if there was a part 1 and a part 2 it would play them in sequence , without the need to open the rar file again and manually select part 2 , cd2 , etc ...

**Comment by adipose** [comment]
Are you sure?  I tested with mpc-hc 1.8.7, put three videos in a rar, and tried to play them.

The result was a dialog asking which file to play, despite it containing 3 videos labeled part1, part2, part3.  I asked it to play the first file, and it stopped after playing that file.

![image](https://user-images.githubusercontent.com/3324395/77811383-0d8c8500-7057-11ea-8ff6-810e7870a5ac.png)

If you can supply me an example file that worked in 1.8.7 (prior to the updated rar code) that doesn't work now, I'll take a look.

**Comment by Tsoccerguy3** [comment]
My bad . I tried with a older rar archive with a avi split in 2 parts . It had the same behavior in 1.7 . I must have confused it with a multi part rar archive with a 1 part mkv inside that plays fine . Its been a long time since i played those old avi files . I guess this auto advance to the next file would be a enhancement . sorry for the confusion

**Comment by adipose** [comment]
The main point of rarsource (as I see it) is to allow playback of large files that have been split into segments for downloading, without having to pre-extract them.  Most of the time, the original video isn't split up, but some old DVD or VCD may well have been extracted in two parts, and then compressed.

In that rare case it might be useful to auto-continue.  But auto-play seems bad, because it takes away the option of the user to choose which file to play.  Both could possibly be added as advanced features, but I would consider it pretty low priority.
