### ISSUE TITLE
Rarsource filter needs updating to deal with new RAR format

### ISSUE THREAD

**Issue by Tsoccerguy3** [clsid2/mpc-hc#35]
https://github.com/mpc-hc/rarfilesource needs updating to play files zipped with RAR5 , which is refered to as just RAR now . The update should detect Rar4 and Rar5 and play from the archive

**Comment by Dr-Flay** [comment]
Why can't you just use unrar.dll ?
Works for WACUP just fine.

**Comment by clsid2** [comment]
I need someone who wants to write code. Anything else isn't helpful as I am not working on this.

**Comment by adipose** [comment]
I have a solution for this.  However, it requires changes to the RARFileSource subproject, and has a dependency of the unrar source.  Since there is already an mpc-hc fork of RARFileSource, might you (@clsid2) want to fork it again--or just import the RARFIleSource into mpc-hc tree.

RARFIleSource is not really maintained anymore, and the core logic of it I have removed entirely in favor of generic calls to unrar, which works for all version of RAR rather than v4.  In theory, even future versions could work.

@Dr-Flay, the unrar DLL is not suitable for this task, really, because it allows little more than access to archive extraction to disk.  Although that could work, RARFileSource worked by reading directly from the archive rather than extracting it first, which is much faster, more efficient, and saves disk space. However, with one small change to unrar source, I was able to use the static library to do the same thing for versions up to RAR5.

**Comment by Dr-Flay** [comment]
@adipose Much more preferable indeed (the unpacking of an archive collection each time I play 1 tracker mod is annoying) I didn't think you could do that with RAR due to the way it is made. I guess opinions have been based of the official unrar, rather than 3rd party options.
A current RARFileSource would be very handy for other projects that prefer not to spaff a load of temp files all the time (especially in an era of SSDs)

**Comment by adipose** [comment]
@Dr-Flay "store-only" means the data sits unmodified in the archive, so other than jumping between multi-volume sets, it's just a question of reading the right data.

It's stupidly ambitious, but I did lay the groundwork for extracting a compressed rar in memory, but didn't finish that part yet (maybe never).  The basic problem there is, you have to start from the beginning due to the way huffman encoding works, so it can be slow (read: extract the whole archive) to get to the end.  On the other hand, 90% of the time you probably wanted to start from 0:00 anyway, so it could work pretty well for the basic scenario.

Other option is just extract to disk first, then play.  But if you wanted to do that, you could have just done it to begin with!

**Comment by clsid2** [comment]
Importing it into the tree would be fine.

**Comment by adipose** [comment]
PR here:

https://github.com/clsid2/mpc-hc/pull/170

Test build here:

https://mega.nz/#!Aco2jI7b!ZsFVz7BIY68DKKPjvatEeoE3PBFFL6ecYv0FimEvPFk

This should work with RAR4/RAR5 uncompressed archives.  

@clsid2, I am not sure how to test the asynchronous reading part of OutputPin in mpc-hc.  If you can comment on that.

**Comment by clsid2** [comment]
Patch has been committed.

I don't know about async stuff either.

**Comment by Tsoccerguy3** [comment]
Could you post a new release for this . thank you
