### ISSUE TITLE
Immediate reaction when seeking with mouse

### ISSUE THREAD

**Issue by qo4on** [clsid2/mpc-hc#370]
You [wrote](https://webcache.googleusercontent.com/search?q=cache:NbguyjD6Mb0J:https://trac.mpc-hc.org/ticket/5850%3Fcversion%3D0%26cnum_hist%3D3+&cd=1&hl=en&ct=clnk) that it was fixed in v1.7.18. I installed [v1.9.2](https://www.videohelp.com/download/MPC-HC.1.9.2.x64.exe), disabled "Fast seek" but dragging the cursor in the seekbar still has a delay around 1 second. Is it possible to fix that?

**Comment by clsid2** [comment]
It works very responsive here with fast seek enabled. When you disable fast seek, then seeking will be much slower. Dragging the cursor triggers a lot of seek operations, which causes delay if seeks are slow.

**Comment by qo4on** [comment]
When fast seek is enabled it useless, it jumps between keyframes. I opened the same video file on the same PC in Premiere Pro and I see that Premiere shows every frame and do it immediately, without any delay.

**Comment by clsid2** [comment]
Clicking instead of dragging will give immediate response.

For framestepping use Ctrl+RightArrow.

**Comment by qo4on** [comment]
It is very inconvenient. As some guy has already wrote to you:
> It's obvious that I get an immediate response if I click instead of dragging.
> The problem is that it can be very inefficient (and also a bit annoying) compared to dragging. That's exactly why I opened this ticket.
> The use-case is simple: you are looking for some familiar part in a song or a movie of which you have no idea where it is and you don't want to click a hundred times.

**Comment by DV2FOX** [comment]
I am actually using an older release from that discontinued CCCP pack (2015-10-18), wich is the:

MPC-HC (CCCP Build, 64-bit)
---------------------------

Build information:
    Version:            1.7.8.162 (ff72737) (blitzkrieg) (master@46ce9d6)
    Compiler:           MSVC 2013 Update 4
    Build date:         Oct 18 2015 21:53:39

LAV Filters:
    LAV Splitter:       0.65.0.5
    LAV Video:          0.65.0.5
    LAV Audio:          0.65.0.5
    FFmpeg compiler:    MinGW-w64 GCC 4.9.2

Operating system:
    Name:               Windows NT 10.0 (build 18363)
    Version:            10.0 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    GPU:                NVIDIA GeForce RTX 2070 SUPER (driver version: 26.21.14.4587)

With this SPECIFIC version, with "Fast Seek (On Keyframe)" DISABLED/UNCHECKED, i can do what qo4on said (Click n hold the mouse on the timeline and it'll be nearly super precise when moving the mouse around it, making each tiny mouse move a frame/timeskip. Aka "you move the mouse and stop, the new play from that point will be done)

However, in whatever latest build, with the same configuration and all, you click n drag the mouse around the timeline and it won't happen until you either fully stop the mouse or release the click.

Is there a way to fix this in the newest releases?.. Because if it gets fixed i can finally jump to the newest version and see the newest changes and benefits related to the codecs, functions, etc

(For example, very very few MKV vids wouldn't play on my version.. However, on the newest version they're played without a problem and even with subs (Though the subs looks like they're darker and even curved or placed at corners instead of the bottom center of the screen)

**Comment by clsid2** [comment]
I made an improvement to make it react in 100ms.

**Comment by qo4on** [comment]
@clsid2 Why don't you want to fix this? A lot of people asking for that.

**Comment by qo4on** [comment]
@DV2FOX Try Options - Internal filters - Video decoder - Hardware acceleration - NVIDIA CUVID. Which delay do you have?

**Comment by clsid2** [comment]
Are you fucking stupid? I fixed it an hour ago.

**Comment by qo4on** [comment]
100 ms != immediate

**Comment by Hrxn** [comment]
There is no such thing as immediate, or 0 ms.

**Comment by DV2FOX** [comment]
> 
> 
> @DV2FOX Try Options - Internal filters - Video decoder - Hardware acceleration - NVIDIA CUVID. Which delay do you have?

I've just downloaded the latest release and I went to where you said and changed the HW setting to Nvidia CUVID but it keeps having the same delay/issue.

**Comment by FluorineDog** [comment]
> > 
> 
> > 
> 
> > @DV2FOX Try Options - Internal filters - Video decoder - Hardware acceleration - NVIDIA CUVID. Which delay do you have?
> 
> 
> 
> I've just downloaded the latest release and I went to where you said and changed the HW setting to Nvidia CUVID but it keeps having the same delay/issue.
> 
> 
> 
> Want me to do a recording difference between my version  (CCCP) and the latest one shown here (1.9.2 x64)?

just a friendly reminder: the fix was an hour ago, which didn’t merge into the latest release. You have to wait for the next release, or compile from source yourself.

**Comment by DV2FOX** [comment]
Ok, i'm a total noob with this. Does it means i have to download an specific file and overwrite a file from the installation folder or something?

**Comment by clsid2** [comment]
You have to wait until a new release is available. There is no date planned yet.

**Comment by lifegpc** [comment]
@DV2FOX I compile from latest source and you can download it.
You need just overwrite the file.
x64 https://1drv.ms/u/s!Aoq8mAMlVv8Uk0RwRkIlo98GFTiv?e=jcLK0s
x86 https://1drv.ms/u/s!Aoq8mAMlVv8Uk0UKwlsGtvQKEM5F?e=nSnHEu

**Comment by DV2FOX** [comment]
It's even MORE precise than the previous version!. The minimal mouse movement (i guess) does the frame activation, while the previous version might have a tad tiny bit bigger gap to make the dragging to happen! (If ya know what i mean, Mr.Bean)

I think that, when installing MPC above the previous version i have (the folders of installation, however, are different, since one is CCCP and the other is the one you guys know), it remembers the settings (Like "Repeat forever"), wich's a good thing ^^

I'll try to play around with the new one when it tends to come with subtitles as they come (vids with subs)

Lil apology about the off-topic, but back then when i wanted to watch the "X-MEN Phoenix" movie in MKV with a not-so recent version of this app (NOT the CCCP one, as it didn't worked somehow), either the subs were placed sometimes at a corner and were darker instead of white, or the subs themselves were always in Italic (Curved) or generally darker in colours.. However, inserted/forced subs for JoJo's Bizarre Adventure Part 4 seems intact (White texts, same font, etc, wich's GOOD)..

Anyways, again, i'll try to play around with the newer version. Thank you for listening to us to make things better! X3. Glad i met GitHub to support the project a tiny bit some!. Apologies for the possible issues that i might've caused due to my knowledge/language!
