### ISSUE TITLE
[Request] Old MPC-HC skins avaliable for newer version?

### ISSUE THREAD

**Issue by DV2FOX** [clsid2/mpc-hc#379]
Back then on the official MPC-HC site, the one with the 1.7 version, used to have a page with custom bottom toolbar skins.

However, the link for such is not there anymore, with all the skins gone.

I wanted to ask if there's a site to download all of those old skins (Specially the 1.7 version's default skin's SMALLER buttons, since the actual GitHub's 1.9 version are way bigger)

Thanks in advance!

**Comment by clsid2** [comment]
Here you can find the toolbar images:
https://web.archive.org/web/20200101080942/https://trac.mpc-hc.org/wiki/Toolbar_images

You can change the size of the default buttons in:
Options > Advanced

Link in Aboutt menu will be replaced later.

**Comment by DV2FOX** [comment]
The Advanced thing did the trick!. I'll check the tools from ya link. Thanks!

Great to see it also got added to the Code section for upcoming fix. Glad to be of help!

**Comment by peytontodd** [comment]
Are there skins available with different functionality for MPC-HC? I need MPC-HC because my users need my videos to freeze on the last screen without just closing or reverting to a logo. They will also find it useful so scroll through a video one frame at a time - a functionality that exists in MP:C-HC but it requires special knowledge of what to do and is not intuitive to use. My users do NOT need and will have no interest in the current default meaning of the left and right arrows, which look for the next video on one's hard drive. 

Is there an alternate skin where the left and right arrows go to the previous or next video frame? This is how the left and right arrows work in Quicktime. But someone discovered a security hole in the PC version of Quicktime, which keeps it locked down on the internet. MPC-HC stays on the last frame just as Quicktime does, but I can't use it because of the security problem.

**Is there no skin for MPC-HC where the left and right arrows go to the previous or next frame?**

**Comment by clsid2** [comment]
You can customize keys in the options.

There are no options or skins that change which buttons are shown.
