### ISSUE TITLE
GUI becomes unresponsive if another file is opened while "Pin connection failure" window is visible

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#381]
Play a file that triggers a pin connection failure. [Sample](https://www101.zippyshare.com/v/VTxyq3Zu/file.html). Leave the error window open. Then open another file through Explorer. The window disappears, and the new file will eventually play. However, now the whole GUI is unresponsive. It seems that the pin failure window isn't closed properly, and also partial filter graph of previous file is still active.

**Comment by bfoos** [comment]
I'm not seeing this behavior on my system. Sample file throws the pin connection failure error. However if I leave the error window open and open another file through Explorer, it just opens another instance of MPC-HC and plays fine.

**Comment by clsid2** [comment]
Then you are not using default settings.

**Comment by bfoos** [comment]
> 
> 
> Then you are not using default settings.

Using default settings was not stipulated in your test scenario, and I seemingly was not savvy enough to pick up on the fact that a recycled player instance was needed to test for this.

Bug confirmed after setting "Use the same player for each media file" in options.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/394

This is caused by having a modal dialog (on the render thread, no less), but still accepting commands.  When a modal dialog is launched it disables the main window.  It seems the waitforsingleobject eventually gives up and forcibly terminates the other thread, which solves one issue, but makes it so the dialog never reenables the main window.

A better solution might be a modeless dialog.  No reason to block the process for a notification?  But what I did here will stop the new file from attempting to launch.
