### ISSUE TITLE
[question] why is latest release not available on the official website?

### ISSUE THREAD

**Issue by wadawada** [clsid2/mpc-hc#404]
Site last updated was on 05 May 2020 for https://mpc-hc.org, but the latest version on the website is 1.7.13 64-bit. 
I got here because I was searching for MPC dark mode, Otherwise, I would wonder if the player is not being updated.
Is the website maintained by the same team?

**Comment by clsid2** [comment]
No, we don't have any control over that website.

**Comment by NebelNidas** [comment]
@clsid Can't you contact @vBm or @Jellyfrog about this? They are in charge of the website according to the About section. Also, why haven't you officially teamed up with them? They were looking for more developers, and here you are, but working on you own without them. Aren't they interested in the project anymore or what happened?

**Comment by NebelNidas** [comment]
@clsid2 Can't you contact @vBm or @Jellyfrog about this? They are in charge of the website according to the About section. Also, why haven't you officially teamed up with them? They were looking for more developers, and here you are, but working on your own without them. Aren't they interested in the project anymore or what happened?

**Comment by vBm** [comment]
@NebelNidas Only X has keys to the kingdom. We did help here and there with the the project in the past.

**Comment by PrplHaz4** [comment]
Unfortunately, the mpc-hc.org website repo appears to be archived, so someone can't even PR to it.  

Would be great to see the resources combined to reduce confusion and establish a more "official" vnext of MPC-HC.

@XhmikosR would you even entertain transferring ownership (or adding admins) of the github org and/or domain for MPC-HC?

**Comment by XhmikosR** [comment]
Well, to be fair, the fork shouldn't use the original project name in the first place, to avoid all this confusion. Random MPC-HC builds started appearing on various software sites.

I tried to onboard some new developers back in 2017 when we were left without developers, but no one with any serious contributions showed up (no offense to the people who did showed up, but nothing happened for months). Thus, a month or so ago, I archived all of the organization repositories to reflect the project status, and put a warning on the website because there is at least a known CVE.

I don't have the time or the strength to do anything this period regarding MPC-HC. I recently managed to renew the server sponsorship to keep the sites alive, just for historical reasons. Trac really needed to go away, it needs Python 2.7 and performs pretty bad. I do have everything backed up, though, but my suggestion is to really ditch it and move to something like GitHub issues.

So, at this point, if anyone is serious about keeping MPC-HC going, they should contact me to see what we can do. I have no gain by letting the project die, quite the opposite, I did want to keep the project going, hence all my calls for help in 2017. That being said, like I mentioned above, I don't have the time nor the strength to do a lot anymore. Transferring the GitHub org, or the domain is something pretty serious, which I don't plan to do randomly. I need to make sure there is clear good will behind this, and no foul play. I've seen a lot of cases of bad play for me to take this lightly.

**Comment by NebelNidas** [comment]
> Transferring the GitHub org, or the domain is something pretty serious, which I don't plan to do randomly. I need to make sure there is clear good will behind this, and no foul play. I've seen a lot of cases of bad play for me to take this lightly.

That's understandable. However, I don't think this really applies here:

> Well, to be fair, the fork shouldn't use the original project name in the first place, to avoid all this confusion. Random MPC-HC builds started appearing on various software sites.

If I'm not mistaken, @clsid2 is the original founder of MPC-HC, isn't he? So I wouldn't view this as a "random fork" of the original project, it simply is the continuation by one of its original developers. I just don't understand why he continued on his own without you and the others, but it would certainly be the best for everyone to simply incorporate this fork back into the main project and continue from there. I think @clsid2 should clarify this confusing situation a bit and explain his motives.

**Comment by XhmikosR** [comment]
It does not apply here. MPC-HC is already a fork of MPC (MPC was created by Gabest) and MPC-HC was created on 2006 by Casimir666 who later moved to other stuff.

Anyway, if anyone has a serious offer, they can contact me via my email address.

**Comment by NebelNidas** [comment]
Yeah, but MPC-HC was a "real" fork of the MPC project because it's developed by completely different people with different motives. In this case here, clsid, the original founder of MPC-HC, picked up development again after the rest of team stopped. I suppose he only forked it out of necessity because he didn't have access to the original repository, but still it's being made by the same original developer from all the years back.

 
> MPC-HC was created on 2006 by Casimir666

Hmm, Wikipedia states this:
>  The active forks are Home Cinema (MPC-HC) by clsid2

**Comment by clsid2** [comment]
No, I am not the founder. That is also not what Wikipedia is saying.

My "fork" was originally intended to be just a basic continuation of a dead project. I was there when  attempts were made to keep it alive, but at that time there weren't enough people with the time and skills to do any serious development. My initial goal of the fork was to keep the player updated with latest LAV Filters and some other minor fixes. Nothing more. I have done a similar thing with the original MPC when Gabest vanished. But thanks to some more free time and effort on my side, and due to great contributions by other developers, some significant improvements have been made to the player.

If X wants to add a link to my repo so users can get the newer version, that would be great. But I don't really have the time, energy, and desire to take over and maintain a website.
If X wants to make his own 'official' signed builds to put on the site, that would be totally fine with me as well.

Maybe I will rebrand the player with a new name at version 2.0 to avoid confusion. I need to think about that.

I have looked at that CVE before but I don't see any usable information to reproduce or fix the issue.

**Comment by NebelNidas** [comment]
@clsid2 Ah, ok, weird that Casimir666 is never mentioned on the Wikipedia site. But my question remains: Why did you fork the project instead of contributing the updates right to the main branch? Seems unreasonable to me. That way, MPC-HC could have entered maintenance mode officially with the help of the other developers while also avoiding all the confusion coming with this fork.
Speaking of confusion, please don't rename the player! For non tech-savy people it's hard enough already to follow all the latest changes with websites/forks/developers etc. If @XhmikosR accepts your offering and if you're able to eventually incorporate this fork back into the main project, that would be the way to go I think.

**Comment by clsid2** [comment]
Information on Wikipedia is not always correct or complete. Casimir is just one of many people who have worked on MPC-HC. Underground and Kasper probably have written much more code than him.

I did not have access to the main repo. It also does not matter at all where the work is done. Moving back does not have any benefit. It doesn't change the code. It won't bring more developers. If you don't understand it is your problem. The original project isn't suddenly going to stop being dead.

**Comment by NebelNidas** [comment]
> Moving back does not have any benefit.

It doesn't benefit the code, yes. However, it would clarify this weird "limbo" situation the project is in now. If your builds could be made official downloads on the website, it would be much better.

**Comment by wadawada** [comment]
While I guess some don't understand why the project is being forked, instead of getting access to the main branch and do altering, ultimately it is up to the contributors' and I appreciate the effort of all contributors, including the original founder and people who were/are contributing.

Personally, I think if this player is going to have a new name later to avoid confusion, I would prefer to see mpc in it, something like mpc-something, considering both are sharing a similar UI, except for dark mode. Of course, it is also fine to continue to use the current name.

And FYI, I will just want to inform people that github has an option to add a sponsor button on repositories, in case if anyone want to add it
https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

**Comment by adipose** [comment]
> 
> 
> > Moving back does not have any benefit.
> 
> It doesn't benefit the code, yes. However, it would clarify this weird "limbo" situation the project is in now. If your builds could be made official downloads on the website, it would be much better.

Anyone who is paying attention (developers or doom9 members) already knows this is the active fork.  End users are most commonly enlisted through k-lite, which is using this fork. So, I don't really see any issue.

Now, as to the website, I think something should be done about that.  @XhmikosR , do I understand you control the mpc-hc.org domain name?

I probably don't have time to do much maintenance on website, but I probably could take over keeping it up and running, so it at least has latest builds or a link to the github page.  We could add some recent screenshots, put a link to github.com releases page, and call it a day.  Maybe do some dynamic lookup of the latest version to keep it looking good.

I registered another domain in anticipation of creating another landing page that could start to rise up in the rankings. But if the .org is available, that would be vastly preferable.

**Comment by adipose** [comment]
@XhmikosR I sent you an email, haven't heard back yet. Just checking in case it went to spam.

**Comment by adipose** [comment]
@XhmikosR This will be my last try (except I will send one more email to you).  I guess maybe my offer wasn't serious enough to merit attention? ;-)
