### ISSUE TITLE
mpc-hc can't correctly handle MKV chapters with linked files (videos)

### ISSUE THREAD

**Issue by Sa-ghosts** [clsid2/mpc-hc#428]
Let's say you have an mkv anime episode splited to 3 files (Episode, OP, EN), and linked together using mkv chapters. this will introduce 2 problems (bugs) with mpc-hc.

First one - in case of all 3 files being in the same folder:
What currently happens:
When playing the main file (the one with the chapters), mpc-hc will only play one of linked files (in my case it's the ED) and won't play the main file 'Episode'.

What expected to happen:
mpc-hc would play the whole episode with both OP and EN in the appropriate postion. (this is what mpv does at the moment)

Second one - in case you only have the main Episode without the linked video:
What currently happens:
mpc-hc will play the video but you wont get the videos timeline (how much have you watch and how much remaining) and you wont be able move forward or backward in the video

What expected to happen:
mpc-hc will play the video with no problem with the timeline. (this is what mpv does at the moment)
_________________

Affected files - for testing:
deleted link

**Comment by clsid2** [comment]
LAV Filters, which MPC-HC uses as internal codecs, supports ordered chapters just fine.

I have opened the episode file with the chapter editor of MkvToolNix. All chapters except the ED were actually flagged as 'disabled'. This means they should be skipped during playback. Enabling the other chapters and then saving the file makes them play correctly.

So fault is with person that created the file. Mpv only plays it 'correct' because it doesn't follow full Matroska specification.

**Comment by Sa-ghosts** [comment]
Thank you for clearing this up for me.
