### ISSUE TITLE
[DrDump] MPC-HC crashes because of xy-VSFilter

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#452]
MPC-HC crashed because you are using an old and buggy version of xy-VSFilter.

**Best solution:**
Use the internal subtitle renderer of MPC-HC. This will give you better quality subtitles and it is also much more stable.
MPC-HC options > Playback > Output > Subtitle renderer

You should also unregister and remove vsfilter.dll

**Alternative solution for stubborn people:**
This version of xy-VSFilter should be more stable:
[VSFilter_x64.zip](https://github.com/user-attachments/files/24350431/VSFilter_x64.zip)
[VSFilter_x86.zip](https://github.com/user-attachments/files/24350435/VSFilter_x86.zip)

**Comment by turbanoff** [comment]
>You should also unregister and remove vsfilter.dll
Hm. How to do that?) I mean "unregister" part.

**Comment by clsid2** [comment]
An easy way to disable/unregister is with [Codec Tweak Tool](http://codecguide.com/download_other.htm#codectweaktool): (Codec and Filter Management > DirectShow)

**Comment by CaptainFrosty** [comment]
That link isn't good anymore, but I'll find it somewhere else. I just realized I have version 3.0.0.21 of xy-VSFilter from way back in 2012. I use VSFilter because it's the only way I know of to render two subtitles at once. Unless there's a better external renderer that MPC-HC supports. 

There are a couple of mpc based players out there with internal subtitle renderers that support two subtitles, but they mysteriously lost the ability to do it one day on my PC. Both players at the same time. With INTERNAL renderers. Weirdest bug ever. I tried a lot of things, including reinstalling DirectShow filters and pouring through a registry snapshot looking for bad changes (didn't really know what I was looking for though). So I'm stuck rigging it with internal + VSFilter.
