### ISSUE TITLE
Freeze on streamings (unknown causes)

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#467]
Ref: https://codecs.forumotion.net/t3472-how-report-crashes-in-mpc-hc
I'm writing here because the forum is messed up currently.

The problem happens with and without DXVA, with madVR and MPC Video Renderer, so I'm not sure what is the cause.

**Comment by clsid2** [comment]
Can you confirm if the problem only occurs with streaming content?

Can you trigger the problem shorty after starting playback? I ask because in case of for example Youtube the extracted links can 'expire'.
Also, can you trigger it with a single seek, or only with multiple seeks in quick succession?

**Comment by ale5000-git** [comment]
I don't have much videos on the PC so currently it is difficult to test it offline since it doesn't happen immediately.
I usually watch anime with hardcoded subtitles (NOT from Youtube, links do NOT expire) so sometime I seek back some seconds to read it again the text (multiple seeks but NOT in quick succession).

If you can send me the link of latest compiled debug versions of MPC-HC x64 and madVR / MPC Video Renderer I can test again with them.

**Comment by ale5000-git** [comment]
I got it crashed more than 100 times, now I'm sure it happens only on streamings (possibly related to an unstable wireless connection).
