### ISSUE TITLE
youtube-dl format settings are ignored when playing from mpc-hc

### ISSUE THREAD

**Issue by madjxatw** [clsid2/mpc-hc#527]
I have the `--format` setting in the youtube-dl config file to specify video quality, but mpc-hc always picks the best quality. Is this intended behavior or some other settings I am missing?

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/86922549-680da500-c15f-11ea-94ec-bf63401106dc.png)
You can see here. Here is the setting.

**Comment by madjxatw** [comment]
I simply set `YDLCommandLine` to `-f 18` to play a 640x360 youtube video (with format code 18), it doensn't work. MPC-HC  always picks the best quality.

**Comment by clsid2** [comment]
YDLCommandLine is only used for downloading (File > Save a copy), not for streaming.
YDLVideoFormat allows you to configure preferred video format for streaming. Hover your mouse above it for details.
YDLMaxHeigth allows you to maximize the resolution.

I am not going to add any more options.

**Comment by Rikk** [comment]
For me it seems MPC use the default '`best`' format of YDL for streaming and can't be configured. The problem is YDL very often doesn't use the truly better quality by default - which would be the highest resolution video-only (dash) + an audio-only format, two files. Instead, '`best`' means the better single file video+audio available.
'`bestvideo+bestaudio`' instead of '`best`' may solve it.
I'm talking about YouTube, I don't know how YDL handles other sites.

Upt: I'm wrong about this supposition. But some videos don't play in best available quality.

**Comment by clsid2** [comment]
It already uses separate streams when that is better choice.
If you are talking about downloads instead of streaming, then you need to add ffmpeg.exe to the folder. Then it can/will download separate streams (and merge them).

You need to give an actual example link if you think it makes wrong choice.

**Comment by Rikk** [comment]
You were too fast today :D I was about to rewrite my post after some tests I'm doing... An example is this: https://www.youtube.com/watch?v=QNLvm-oCz_Q

**Comment by clsid2** [comment]
It currently ignores Dash Manifest URLs because those are not handled properly by LAV Filters.

Such streams have multiple audio and video tracks. The problem is that wrong video track is selected. MPC-HC no longer has influence on which one is used. LAV picks first one that is set as default in the Manifest, which is usually low resolution one.

**Comment by reallyuniquename** [comment]
> YDLCommandLine is only used for downloading (File > Save a copy), not for streaming.

@clsid2 Is there a way to pass custom arguments to youtube-dl when it's launched for streaming?

**Comment by lifegpc** [comment]
> > YDLCommandLine is only used for downloading (File > Save a copy), not for streaming.
> 
> @clsid2 Is there a way to pass custom arguments to youtube-dl when it's launched for streaming?

No. You need edit [source code](https://github.com/clsid2/mpc-hc/blob/863a7d1280ea54ea9eda0d8d3bcbaeef5f0a1406/src/mpc-hc/YoutubeDL.cpp#L84)

**Comment by lifegpc** [comment]
But you can configure youtube-dl by using its configure file. https://github.com/ytdl-org/youtube-dl#configuration

**Comment by reallyuniquename** [comment]
>No. You need edit source code

Having checked the source line you mentioned I actually don't. Just inject whatever args you have into `YDLExePath`. I can finally watch ad free Twitch through MPC-HC.

>you can configure youtube-dl by using its configure file

I've thought about that too but then I would have to use `--ignore-config` for all other instances of youtube-dl which is unwanted.

**Comment by win98se** [comment]
Sorry for hijacking this issue - when `YDLVideoFormat` is set to `1`, although respecting to only select H.264, 60fps is still selected.

If it is needed to create a new issue for it, please inform me, thank you.

**Comment by clsid2** [comment]
Don't bother opening a new issue. I am not going to fix it because there likely is no bug. If it selects 60fps there wasn't a usable 30fps stream available. And if there is, you are out of luck. I don't care at this moment.
