### ISSUE TITLE
Fix for short space on spanish text line

### ISSUE THREAD

**Issue by hellishvictor** [clsid2/mpc-hc#551]
On the file "mpcresources.es.dll" there should be made a correction on:
Dialog -> 20014:10 -> Line 12 -> 37 must be 43:
   CONTROL "Verdadero", 11040, BUTTON, BS_AUTORADIOBUTTON | WS_CHILD | WS_VISIBLE, 66, 262, 37, 14 
![A  wrong](https://user-images.githubusercontent.com/34694956/88431968-3f3e0e80-cdf3-11ea-89a8-ba7466827452.jpg)
->
![B  correct](https://user-images.githubusercontent.com/34694956/88431969-406f3b80-cdf3-11ea-9701-cb0288cc9d4e.jpg)
   CONTROL "Verdadero", 11040, BUTTON, BS_AUTORADIOBUTTON | WS_CHILD | WS_VISIBLE, 66, 262, 43, 14 

That's it! Cheers.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/583

Check out the dark theme.  It happens that the dark theme didn't have this issue so I didn't notice it.  That's because the dark theme used to alter the default font, so it dynamically resized text elements to fit.  Classic theme doesn't have that feature, so this happened but I didn't see.
