### ISSUE TITLE
[Request] Pause playback on minimize to taskbar

### ISSUE THREAD

**Issue by BooBerry** [clsid2/mpc-hc#558]
Please add an option to the Playback section of the Options allowing MPC-HC to automatically pause playback when minimizing the window to the taskbar (which resumes playback when restoring the window). There's a few benefits to this, for example it could be used as a one click "boss key" type of thing to hide the window and pause playback when minimizing the window.

This could be extended as well allowing customization, e.g. allowing pause on minimize for video files only, whereas audio files will continue playback when minimized.

**Comment by clsid2** [comment]
There already is a "boss key" (B) that does that. I am not adding another similar option.

**Comment by K0media** [comment]
@BooBerry , you mean something like this, right?

![image](https://user-images.githubusercontent.com/22375465/96296678-06fb3600-0fc6-11eb-9d5f-db95f9f98f8c.png)

If yes, I reckon this idea. My current laptop doesn't have such media buttons to Play/Pause or Previous/Next controlling.

That would be pretty handy.

But since clsid2 is a very busy subject, I doubt it's gonna be added anytime soon. If it's ever gonna be added, that is. 🙄

**Comment by clsid2** [comment]
It already has that functionality.

Options > Tweaks > Use Enhanced task bar features

That is enabled by default so if it doesn't work you might have disabled it in Windows somewhere.

**Comment by K0media** [comment]
Oh yeah, that's true. I remember seeing this before but somehow it disappeared. Now that I toggled it off/on again it got back to work.

Thanks for the tip. 🙂
