### ISSUE TITLE
Twitch video URLs refuse to load in latest version

### ISSUE THREAD

**Issue by ObjectInSpace** [clsid2/mpc-hc#560]
MPC will no longer open VODs from twitch. Youtube was working, did not test a twitch live stream or content from other sites.
Example VOD:
https://www.twitch.tv/videos/658929640
File > open > paste URL > OK.
In V. 1.9.6, this video will load. In V. 1.9.7, this video will not load. Tried updating youtube-DL to no avail.

**Comment by clsid2** [comment]
I have fixed it.

@adipose
The extracted url from youtube-dl was getting passed to ParseM3UPlayList. Previously that would fail due to lack of https support. But now it tries to parse the m3u8 playlist. I have restored old behavior by skipping the parsing for playlist urls coming from youtube-dl. Those are send directly to lav splitter again now.

But this issue did reveal two other bugs in MPC-HC.
1) this m3u8 file isn't parsed correctly: (#ID3-EQUIV not ignored) (base url not used)
2) after the wrong parsing the playlist in MPC-HC contains only invalid entries. This causes an endless loop of skipping to next one. I think it should be changed to stop skipping files when end of playlist is reached.

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#ID3-EQUIV-TDTG:2020-06-23T13:37:41
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TWITCH-ELAPSED-SECS:0.000
#EXT-X-TWITCH-TOTAL-SECS:25938.006
#EXTINF:10.000,
0-muted.ts
#EXTINF:10.000,
1-muted.ts
#EXTINF:10.000,
2-muted.ts
#EXTINF:10.000,
3-muted.ts
(... cut ...)
```

**Comment by clsid2** [comment]
Fixed the M3U parsing issues.

**Comment by reallyuniquename** [comment]
@clsid2 
Any ETA on when this fix hits release branch?

Thanks a lot for keeping MPC-HC alive and keeping youtube-dl intergration updated!

**Comment by clsid2** [comment]
There already is a build available:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.7.34

**Comment by reallyuniquename** [comment]
Yes, I saw that but it says `Development build` so I assumed it's better to wait for stable release.

Is there no difference between those two, like some debug things?

**Comment by clsid2** [comment]
Same as normal builds.
