### ISSUE TITLE
Please bring back Windows XP support

### ISSUE THREAD

**Issue by palikacska** [clsid2/mpc-hc#57]
Hi there,

I have tried to install the latest version v.1.8.4 onto my system and it said Windows XP is not supported. I don't really see why you are removing the support for an operating system that is still in use by even more people that use Linux and there are not even any new features that would give a good reason to drop XP support.

Media Player Classic is the only light, fast still full-featured media player out there for Windows. People on XP are mostly on older computers with less resources and no drivers for newer operating systems (like Vista, 7 or 10). If upgrade was an option it would have already happened in the last 4 years.

Please revert [c04cff832a7aa4f705e4bd7a56f158e7144ea817](https://github.com/clsid2/mpc-hc/commit/c04cff832a7aa4f705e4bd7a56f158e7144ea817) and bring back Windows XP support.

**Comment by clsid2** [comment]
Not going to happen.

**Comment by palikacska** [comment]
Why exactly isn't it going to happen?
What are your technical reasons not doing it so beyond nonsense stock phrases like _"XP is hundred years old and you'll be hacked every day if you use it"_?
What are the obstacles that prevent you from compiling binaries that run on XP?

Why do you support Windows Vista used by almost nobody (0.27% market share = just few million people) and not XP (4.08% market share = more than a hundred million people)? MPC-HC integrates well into the XP ecosystem and is the only fast and lightweight media player that performs well on old computers which can't be upgraded to Windows Vista, 7 or 10.

**Comment by lvqcl** [comment]
@palikacska 
1) The last XP-compatible version is still available from the official web site: https://mpc-hc.org/downloads/
Why don't you want to use it? Why do you think that you need the latest version?

2) Look at the top of this page, and you'll see the text
```
clsid2/mpc-hc
forked from mpc-hc/mpc-hc
```

**Comment by clsid2** [comment]
I work on this project in my spare time. For free. So I decide what I care about and what I work on. And I don't care about XP anymore.

XP was dropped already before I forked. The reason was simple: the internal codecs (LAV Filters) had dropped XP support, which in turn was because its dependency FFmpeg dropped it.

The minimum is now Vista because that is the lowest version of Windows (6.0) that offers the required APIs. The fact that it has a tiny market share is totally irrelevant. It is just a minimum.

You are using an 18 year old OS on a computer that is probably at least 15 years old. Demanding to be able to use the latest cutting edge software is just stupid when the rest of your setup is old crap. If you would make an effort yourself then you could probably get a much newer computer somewhere practically for free.

But anyway you can use 1.7.13 on XP. That works fine. In fact, there are far more people with Windows 7/8/10 that still use that version (or even older) because "it does everything they need" (no reason to update), then there are XP users.

**Comment by palikacska** [comment]
> The reason was simple: the internal codecs (LAV Filters) had dropped XP support, which in turn was because its dependency FFmpeg dropped it.

As poor excuse as _Because Windows XP is not supported anymore_. You can still [build ffmpeg to run on Windows XP](https://msfn.org/board/topic/177308-ffmpeg-and-windows-xp-in-2017/). Since you have forked not just only MPC-HC but LAVFilters as well, you have everything in place to compile that forked LAVFilters with XP-compatible ffmpeg. There are also [precompiled binaries of ffmpeg for XP](https://rwijnsma.home.xs4all.nl/files/ffmpeg/?C=M;O=D). In addition and most importantly, there is **even a LAVFilters fork maintained for Windows XP** called [LAVFiltersXP](https://github.com/3dyd/LAVFiltersXP). It was created by the author of [3DYD](https://yd.3dyd.com/) who recognized the fact that there are a lot of XP users on low-end computers and took bold action to continue supporting these systems.

> You are using an 18 year old OS on a computer that is probably at least 15 years old.

Numbers only matter to an innovation idealist and to a consumerist who buy their computer hardware according to delusional IT fashions and trends instead of common sense. I'm none of the two so numbers don't matter to me.

>the rest of your setup is old crap

If something still works, don't fix it. If a computer still works but can't be upgraded to Windows 7 due to missing drivers, why trash it and why buy a new instead? Why fall into the trap of planned obsolescence caused by software?
> you could probably get a much newer computer somewhere practically for free

Which you can thank to highly unequal distribution of wealth and the fact that Chinese workers are making new hardware almost for free in overtime. Meanwhile they damage the environment incredibly, not to mention the pollution of shipping electronics to thousands of miles far. I do not want to support this supply chain and I'm very sorry you do want your users to.

Just to stay at the topic, MPC-HC belongs to the Windows 2000/XP era. It mimics the UI of the Media Player in Windows 98 and mostly exploits the capabilities that Windows 2000/XP brought in. Original developers advertise the project as dead to convert all their users to mindless YouTube and Netflix zombies. I thought you were our last hope who can step in and continue maintaining MPC-HC.

Since you're familiar with MPC-HC codebase, I don't think it would be much of an effort for you to make an XP build. So please change your mind soon.

**Comment by clsid2** [comment]
As I have said before, I am not spending any time on this. I spend my valuable time only on things that I care about. All your arguments are totally pointless. Do it yourself or find someone else to do it.

And when I said you could get a better computer for (nearly) free, I meant a second hand one.

**Comment by lvqcl** [comment]
From the rules of [r/ChoosingBeggars](https://www.reddit.com/r/ChoosingBeggars/):

>  Someone asking for free goods or service must also be an asshole. That's where the comedy is.

**Comment by mhtvsSFrpHdE** [comment]
@palikacska I'm pretty agree with you, there're billions of users still run Windows XP.
I have maintain a modded open source project is required to have Windows XP support, otherwise it is meaningless than vanilla version. 
All my friends running Windows XP, none of them upgrade to even Windows 7.

我非常同意你的看法，还有数十亿用户仍在使用Windows XP。
我在维护一个修改版的开源软件项目，它必须有Windows XP支持，否则与原版相比没有任何意义。
我所有的朋友都运行Windows XP，甚至他们之中没有人升级到Windows 7。

In this case, let's suppose you have your decent reason to not upgrade your Microsoft Operating System.
The same reason should exactly apply to a same thing: not to upgrade your MPC-HC version.
Since Microsoft stopped provide Windows upgrade to Windows XP for a hundred years,
you're not getting any system updates, and you can still running your system smoothly.
The same principle have no reason not apply to MPC-HC.
You can find a old version MPC-HC that have Windows XP support and use it to the end of time.

在这种情况下，我们假设你有体面的理由不去升级你的微软操作系统。
相同的理由应该完全对同一件事成立：不去升级你的MPC-HC版本。
微软公司已经停止对Windows XP提供更新超过一百年以上的今天，
你没有获得任何系统更新，而你仍然正常使用你的系统。
同样的原理没有理由不适用于MPC-HC。
你可找到一个以前版本的带有Windows XP支持的MPC-HC并使用它直到时间的尽头。

So even if we provide a MPC-HC upgrade with Windows XP support,
as expected, you should actively decline to upgrade to this version instead of upgrade your MPC-HC version.
Just like if the users turn off Windows Update, and stay on Windows XP initial version and refuse to install XP SP3 upgrade.
In this case, provide a MPC-HC upgrade for you is time wasting for all of us.
There're much more import things to do.

所以即使我们提供了一个带有Windows XP支持的新版本MPC-HC，
按照预期，你应该会主动拒绝升级到这个新版本，而不是进行更新。
就像有些用户关闭Windows更新，并且停留在Windows XP的初始发布版本和拒绝安装任何Windows XP的更新（包括Windows XP SP3）。
在这个预期下，特意为你提供这个MPC-HC更新对于我们所有人都是浪费时间。
有更重要的事情去做。

Are we clear?
我们能否达成共识？

**Comment by JeanPaulLucien** [comment]
Is there in this repo a version with windows xp support?

**Comment by clsid2** [comment]
No.

**Comment by mirh** [comment]
You can find here the latest scavenged builds
https://msfn.org/board/topic/177308-ffmpeg-windows-xp-updated-builds-by-corone/page/2/
