### ISSUE TITLE
[Feature Request] Global Media Keys enabled by default

### ISSUE THREAD

**Issue by DV2FOX** [clsid2/mpc-hc#573]
There are people like me who have Keyboards with dedicated media keys (Play / Pause, Stop,  Previous, Next) that'd be surprised that they'd be able to use 'em on MPC the very first moment they install it.

Back then on CCCP (Discontinued) this option was enabled by default, but NOT on the updated GitHub'd versions (Any build, even actual ones)

The request would be to change the installation and/or program code, so that whenever you install the program (or update it, whatever the order), such function found from Options (O Key) -> Player/Keys-> "Global media keys" checkbox gets enabled by default. That way people can enjoy their keyboards better.

I mean, atleast i use it frequently when it's the only player activated (Works by default with default Windows Media Player (W10) settings too)

Hope it helps

**Comment by clsid2** [comment]
It is intentionally disabled by default on Windows 10.

Many people were having issues where the player pauses/unpauses due to Windows sending an event for some reason. For example when a notification is shown or even by just opening the start menu. I am not sure about the exact conditions in which it happens as I use W7 myself on my main system.
