### ISSUE TITLE
External Subtitle Rendering issue when playing DVD.

### ISSUE THREAD

**Issue by lifegpc** [clsid2/mpc-hc#586]
When playing DVD, Animate at 100% of the video frame rate is not work for external subtitle.
The subtitles seem to be rendered only twice per second.
The example subtitle file: [00001.ok.o.zip](https://github.com/clsid2/mpc-hc/files/5106740/00001.ok.o.zip) 
The DVD file is same in #464 .( https://1drv.ms/u/s!Aoq8mAMlVv8Ul1tXuHPKJlDTuEwO?e=3Uy59p )

![image](https://user-images.githubusercontent.com/41434272/90851267-c22c9780-e3a6-11ea-818f-c48e6b493a25.png)
![image](https://user-images.githubusercontent.com/41434272/90851447-5e569e80-e3a7-11ea-9c5f-d4b94ae8928b.png)

**Comment by clsid2** [comment]
With DVD playback the time in the status bar only gets updated once per 500ms. That limitation is due to the DVD Navigator filter. Relevant code is in OnTimer() function.

The subtitle rendering is probably affected by that timing. Improving the time resolution would require some interpolation based on displayed frames.
