### ISSUE TITLE
Toggle to maximized window state after entering MPC in fullscreen.

### ISSUE THREAD

**Issue by JorgeR81** [clsid2/mpc-hc#675]
I don't know if this is a bug or if I just haven't found the setting for this ...    
After entering MPC in fullscreen, when I toggle to window mode, MPC does not resize the picture, so instead of getting a maximized window, I get a large window that is partially hidden by the windows taskbar. 
But this only happens the first time I toggle. If I maximize the window and toggle fullscreen, when to toggle back to windowed state, now I get a maximized window.
And If I enter MPC in maximized window state this does not happen. I can toggle in and out from fullscreen to maximized, from the very first try.

**Comment by clsid2** [comment]
Does not happen here. If I launch in fullscreen and toggle to windowed mode then video is resized correctly. It will not use maximized state unless you maximize it yourself. Instead it will fit the window in the space available. So without unnecessary black borders (on the sides).

It might be due to custom settings. Reset the settings to defaults (Options > Miscellaneous) and test your modifications one by one.
