### ISSUE TITLE
LOGO colors are wrong, seems faded out.

### ISSUE THREAD

**Issue by papahuge** [clsid2/mpc-hc#678]
![image](https://user-images.githubusercontent.com/73111061/96443599-7c3b5680-11d2-11eb-8f26-5de9de95325f.png)

The external logos now have faded colors when shown in player. In the setup options it shows correct colors.

**Comment by adipose** [comment]
It can adjust based on your color profile.

**Comment by papahuge** [comment]
> It can adjust based on your color profile.

Yes it can, however I didn't change my color profile. My profile has always been set to Adobe RGB 1998 on both of my monitors.
![image](https://user-images.githubusercontent.com/73111061/96557645-27561980-1280-11eb-8489-021228d7826e.png)

But when I recently updated MPC-HC all of the sudden the way the custom logo looked in the player changed, and you can see washed out colors. What was updated recently that would account for this? Can you please make an option to revert back to the way it was before, because before the black on black logo blended with the screen seamlessly. But now it stands out and you can see that grainy black box around the logo. Also the colors are a washed out. This only happens in MPC-HC after I updated it to the most recent version. My windows picture viewer displays normal coloring.

**Comment by clsid2** [comment]
Perhaps the color profile is now getting applied twice? Once by Windows and once by MPC-HC?

**Comment by papahuge** [comment]
Maybe. I'm not sure. But the strange part is, that in the options menu, when I import the external logo the preview looks just fine. But when it is applied to the video player, inside the player it looks wrong. Was anything changed about the way the logo is displayed inside the video player?  

I double checked to see if the shaders, or misc. color controls were being applied to the logo as well, and it turns out they were not affecting it. So there must have been some kind of change to the logo display in the player that caused this. Playback of videos is color correct.

**Comment by clsid2** [comment]
ICC profile is applied to the logo and coverart. See this topic:
https://github.com/clsid2/mpc-hc/issues/220

**Comment by papahuge** [comment]
> ICC profile is applied to the logo and coverart. See this topic:
> #220

so basically I need to revert to an older version before this change was implemented?

**Comment by adipose** [comment]
If that is fixes it, it will could be a bug with that feature, yes. Maybe applying the profile is no longer necessary.

**Comment by clsid2** [comment]
Are colors correct when playing video?

**Comment by papahuge** [comment]
> Are colors correct when playing video?

Yes the colors in the video playback are correct. Just the logo displayed when no video is playing is affected.

**Comment by adipose** [comment]
It may have to do with multiple monitors, too.  What happens if you try on a different monitor?  What happens if you try after disconnecting one monitor?

Did you try the old build to see if it's better?

**Comment by adipose** [comment]
There isn't a good way for me to determine if the behavior is "right."  What I can say is, it's not expected that the logo that shows in settings will be the same as the one showing on the player.  That's because color profiles are applied only to the player and not the settings window.  As Windows does not apply color profiles by default, any application you open the image in will not show the "applied" colors.  So MPC-HC is always going to look different in an attempt to at least honor profiles when displaying video and images.

I do not have color profiles assigned to my monitors, and maybe you don't really need the 1998 profile.  It's not even the default Windows color profile, I don't think (at least not for LCD):

![image](https://user-images.githubusercontent.com/3324395/98748989-a9ad9700-236f-11eb-82b4-b0cec89859c2.png)

To solve your issue otherwise, it's possible we could create an advanced option to disable color profiles on static images.  But keep in mind, that profile will still be applied to video going through many of the renderers.

Finally, I suspect the reason it's bothering you is due to a poor quality asset.  The "black" background that is showing up as a faded box is not ideal for an mpc-hc background.  MPC-HC has pure black (zero) for the background, so the edges of your image should be pure black, as well, unless you deliberately wanted a box to show up in the middle of mpc-hc.  Typically logos are going to be drawn on a pure black background, which when placed on top of the mpc-hc black background seamlessly overlay, and you can't tell where the logo stops and the mpc-hc bg begins:

![image](https://user-images.githubusercontent.com/3324395/98749535-b54d8d80-2370-11eb-8dcd-45dfabe60c6f.png)

The logo is only about the middle 3rd of the screenshot.

**Comment by flibdev** [comment]
I get a similar issue with all images, even the default logo

![mpc_issue](https://user-images.githubusercontent.com/6767042/101586459-f04cea80-3a1c-11eb-94f2-8b44d53f23f0.png)

Happens on multiple monitors with varying colour profiles.
Running MPC-HC.1.9.8.x64

**Comment by adipose** [comment]
The two aren't meant to be the same.  The one displayed in the video frame adjusts for the color profile in use.  Since W10 does not do this, the logo in the settings is not adjusted.

However, it is possible there is a bug that the profile is getting applied twice, or something, but so far it works ok for me.

Maybe an advanced option is in order--it's difficult to debug this sort of thing.

**Comment by clsid2** [comment]
Maybe there is an image editor that can apply a color profile on an image? Not just for display, but to actually adjust the image file. Then we could compare it with a screenshot to verify if it matches.

**Comment by adipose** [comment]
Irfanview can use color profiles, I will check that out.

**Comment by adipose** [comment]
![image](https://user-images.githubusercontent.com/3324395/102799390-51eb4e00-4367-11eb-8bab-3412a8c01e59.png)

I got it to work with Irfanview, but it was a bit of a challenge.  Irfanview only supports it if the image itself has an input profile, unless you check the box for default input profile and set it to sRGB (see below):

![image](https://user-images.githubusercontent.com/3324395/102799478-73e4d080-4367-11eb-9722-cf1a3e3297e8.png)

FastStone is much easier to default:

![image](https://user-images.githubusercontent.com/3324395/102799531-852ddd00-4367-11eb-856e-7e762a7d0a02.png)

It looks like all three show the same thing, and paint does not (does not support output profiles, apparently).  Based on this, I think mpc-hc is working correctly.  The amount of fade in the screenshot from @flibX0r looks like quite a dramatic icc change, more than I got using this Samsung profile.

@papahuge , @flibX0r , please test with these images viewers and report back.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/818

This will allow it to be disabled, as well as previewed correctly on the settings page.
