### ISSUE TITLE
Subtitle downloader: multiselection with shift+down

### ISSUE THREAD

**Issue by duzenko** [clsid2/mpc-hc#680]
This used to work in 1.7.13 before the opensubtitles downloader stopped working
Now I switched to this fork and the only annoying thing is no multi-selection with shift+cursor keys
Please fix or point me to a specific release where it still worked last.

**Comment by duzenko** [comment]
_1.9.1 seems to have it right_
Spoke too soon. Although it does multi-selection, it won't download those on Enter
1.9.0 is perfect

**Comment by cw2** [comment]
The multi-select feature was disabled in #278, unfortunately there is no description why. The change affected only the list control style (multiple -> single selection), the code to download multiple subtitles is still there...

**Comment by ale5000-git** [comment]
Maybe it was to avoid to overload the server, if there isn't any limit one could download even 200 files at once and maybe be banned but it is just a guess.

**Comment by cw2** [comment]
A close inspection reveals that the code downloads all subtitles that are checked, not selected/highlighted - so in order to download multiple subtitles, simply check them via mouse or <kbd>Spacebar</kbd>.

**Comment by duzenko** [comment]
> 
> 
> A close inspection reveals that the code downloads all subtitles that are checked, not selected/highlighted - so in order to download multiple subtitles, simply check them via mouse or Spacebar.

Which is for me a major UX downgrade
I select multiple adjacent subtitles with shift + down
To check them I'd have to double the key strokes

**Comment by adipose** [comment]
> The multi-select feature was disabled in #278, unfortunately there is no description why. The change affected only the list control style (multiple -> single selection), the code to download multiple subtitles is still there...

If you read the linked [issue](https://github.com/clsid2/mpc-hc/issues/276) on #278, you'd see the discussion about why it was done.  The bug report was of a disparity between the checkmarks and the selected items.

Somehow I never noticed that this regression in capability was actually caused by the "fix" I did back on #278.  After reviewing it, I realized that my fix was totally unnecessary, and actually the original bug report was not caused by the dark theme at all.  It was pre-existing, going back to at least 1.8.8.

The actual "bug" is a result of the split personality of the dialog, which IMO doesn't make any sense.

1. The "download" button only downloads the _checked_ rows.
2. The "OK" action (which isn't even accessible via the mouse UI, and is only activated via `enter`) downloads all the _selected_ rows.  This allows you to multi-select, hit enter, and download them all.
3. As you check / uncheck the rows, they also become selected, but as 1 & 2 are distinct approaches, the two should not be confused--but of course they will be as a checkmark is a valid way of "selecting" rows from a UI perspective.

This should be solved by modifying the dialog so that the selected rows and the checked rows are always kept in sync.  This would retain the behavior of 1 & 2, but make it so that clicking "download" would download all the selected rows (regardless of your definition of _selected_), and hitting enter would get all the checked/selected rows.

**Comment by adipose** [comment]
As an addendum, the dark theme did actually change the way the multi-select behaved.  The checkboxes and selection previously didn't match, but the dark theme inadvertently caused the selections to change while clicking checkboxes, too.

**Comment by clsid2** [comment]
Fixed

**Comment by duzenko** [comment]
Thanks for resolving this
From the point of UI/UX, I still think that this dialog would be better off without checkboxes at all though
