### ISSUE TITLE
Please Fix the Problem of increase speed while playing!

### ISSUE THREAD

**Issue by masumeee** [clsid2/mpc-hc#695]
During Video Playing the **"increase speed"** didn't work on .wmv media files. For mp4 files it shows increase 2.0% at the first click. Please make it slowly starting from .25% or .50%.

**Comment by clsid2** [comment]
It doesn't work for WMV because the default decoding filters that are used for those files do not support that functionality. Those are made by Microsoft, so we do not have any control over them. 
Enable the internal filters for Windows Media and it should work better.

Speed increment can be customized in the settings.
Options > Playback > speed step

Latest version (1.9.8) also has speed option in the menu.
Menu > Play > Playback rate
