### ISSUE TITLE
mpc-hc ignores fullscreen option when playing from device

### ISSUE THREAD

**Issue by PCigales** [clsid2/mpc-hc#709]
Probably due to the commit https://github.com/clsid2/mpc-hc/commit/2a8080826a957aeca79508978735df61163e70e0#commitcomment-43547937, mpc-hc does no longer open in fullscreen mode when requested to display DVB-T (running mpc-hc - /fullscreen /device). It is a pity as thanks to some recent fixes in audio management, mpc-hc can now be used as a DVB-T viewer (replacing the no longer maintained pouchintv).

Thanks for keeping mpc-hc alive, and it would be nice if this regression could be solved.

**Comment by demolitioner** [comment]
I already reported this bug here, BEFORE the final version 1.9.8 appeared:
https://github.com/clsid2/mpc-hc/issues/615#issuecomment-699603251

Instead of fixing the bug with the impossibility of "/fullscreen" when d3d was enabled, the "/fullscreen" function as well as the function in the "Launch files in fullscreen" options were simply disabled permanently. I suggested removing the word "/fullscreen" from "help - commandline switches" altogether, so users wont be deceived, but the developer for some reason did not do this.

**Comment by clsid2** [comment]
Fixed

**Comment by PCigales** [comment]
Thanks !
