### ISSUE TITLE
Active shaders dont update changes when modified while using madVR as renderer

### ISSUE THREAD

**Issue by bacondither** [clsid2/mpc-hc#722]
Modifying and saving an active shader in MPC-HC 1.9.8 using madVR does not update the shader. Have to restart the player for the changes to apply, removing it from active and adding it back again does not update it. Everything works fine with EVR.
Last version that worked correctly is 1.9.3. 1.9.4 and later does not update changes to shaders while using madVR.

**Comment by butterw** [comment]
Similar behavior with MPC-VR dx9 (tested with mpc-hc 1.9.6).

**Comment by adipose** [comment]
New code was released after 1.9.3 to support shaders in mpc-vr, and the codepath for madvr was affected too.  I'll take a look.

**Comment by adipose** [comment]
MPC-HC is now using some code that implements a shader cache.  This is based on some mpc-be code.  I do note that mpc-be has a built-in shader editor, which mpc-hc does not currently have.  It's a little clunky and I didn't see much point in bringing it over. However, the side effect is there is no way to do a "live" edit of the shaders.

We could either implement the editor in mpc-hc, or add a feature to "clear shader cache."  Or, we could just not cache at all (maybe an advanced option).  Caching the shaders seems like a good idea for performance.

@clsid2 , what do you prefer here?

**Comment by butterw** [comment]
Live editing shaders works in EVR-CP.

The built-in shader editor in mpc-be is unstable and useless. Having a button in Shaders Option to open in external editor  wouldn't be a bad idea though.

**Comment by clsid2** [comment]
Live editing is not an important feature. I doubt many people will use that. There is probably just a handful of people like butterw who modify shaders during playback for testing/development purposes.

I would say just press Ctrl+E to quickly reload the video. Or use EVR-CP during the testing.

**Comment by butterw** [comment]
Adjusting shader parameter values (ex: threshold, filmgrain strength) without closing isn't just useful for dev. VLC uses sliders for its built-in filters. Obviously in mpc, the user might break the shader if syntax isn't respected.

**Comment by adipose** [comment]
As long as there's an easy way to reload, it's probably not a super big problem, right?  Do I understand correctly there is currently no way to reload without restarting the player?

**Comment by adipose** [comment]
https://mega.nz/file/AFhFFKSI#LSAonPN810_paZR_tDrFffhPn0kv1wxbdLk1t3TulH4

Here's a test build, where I clear the cache when you disable shaders.  So ctrl+p, ctrl+p should work as a reload.  This should probably be good enough, but a dedicated hotkey would be cleaner.

**Comment by butterw** [comment]
Ctrl-E doesn't help in mpc-vr, madvr not tested. 

>> Version:            1.9.8.34 (36348a70a-dirty) (patch156) (develop@a91c9d4)   toggleshaders Build :  Nov 11 2020
- The 2 issues noted in https://github.com/clsid2/mpc-hc/issues/502 remain.
- There is an issue with ./ShaderCache in portable ini mode when an existing system install is present (this may be a pre-existing issue). Folder gets created in the portable directory in EVR-CP mode, but stops updating with mpc-vr (shaders still update though, so it seems it's either using a different folder or not caching). Location seems to be the hidden folder %Appdata%\mpc-hc ? 
- In EVR-CP shaders now live update in paused mode (instead of next frame): this is requested feature for dev.

**Comment by adipose** [comment]
@butterw , I can't really tell from your response what you tested.  Let's ignore #502 as it's a different problem which I haven't looked at yet.

Did ctrl+p/ctrl+p update in non-portable mode?

For EVR-CP I wouldn't think my changes would have any effect, not quite sure what you are saying about it being a requested dev feature?

**Comment by adipose** [comment]
https://mega.nz/file/wNoVza4b#wEem9ah7y8ZSQjk7bXVGeiuc1NxlrRrGHorrTca7XE0

Here's a build that does a smarter cache update (when disabling/enabling shaders).  Let's see if it works any better.

**Comment by butterw** [comment]
Previous version did work. But ShaderCache Folder location is confusing. mpc-vr doesn't use ./ShaderCache folder it seems.

- I have tested mpc-vr and EVR-CP in dx9 in portable ini mode in a separate folder (I have an existing v1.9.6 system install). Without reset settings first then with settings reset +CacheShaders=1. 
. . . Ctrl-P pre-resize and Ctrl-Alt-P post resize do update mpc-vr Shaders.
- EVR-CP behavior hasn't changed.  It has been suggested that when you remove all shaders from the active list the update should be effective immediately when paused (instead of next frame currently).

**Comment by adipose** [comment]
Ah, I see.  You can enter a separate issue for that if you want.

I could add an option to reload shaders, but if the enable disable is good enough, maybe we can leave it like this?

**Comment by clsid2** [comment]
Pressing hotkey twice to reload is just a minor inconvenience. It saves us from the effort having to add yet another option.

**Comment by butterw** [comment]
I agree that there is no need for a separate refresh shader option.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/742

**Comment by bacondither** [comment]
Yep that works fine. Thanks!
