### ISSUE TITLE
Fullscreen tooltip "Below seek bar" makes the screen go black

### ISSUE THREAD

**Issue by anmolbyte** [clsid2/mpc-hc#766]
I have Options->Tweaks->"Show time tooltip" enabled to "Below seek bar". when playing any type of media in full screen, the screen flashes black if I hover my mouse over the seek bar and get the tooltip to show. This is easily mitigated by setting the tooltip to be "Above seek bar."

**Comment by anmolbyte** [comment]
New update: to make the screen go black, you have to mouse down until your cursor hits the black bar. I don't think the error is based on the tooltip anymore, since disabling the tooltip still makes the screen flash black.

**Comment by clsid2** [comment]
If it happens only with HDR video, it is because displaying the seekbar switches off HDR temporarily. That is a driver issue. You can work around it by enabling HDR in Windows, or by using exclusive fullscreen in the video renderer.

If it happens with normal video:
Are you using Dark Theme in the player?
Which video renderer are you using?
Which GPU and driver?

**Comment by anmolbyte** [comment]
I'm not using dark theme, and I'm using intel iris 540 with the latest wddm drivers. I'm using madVR, and disabling it seems to fix the issue. How do I enable exclusive fullscreen?

**Comment by clsid2** [comment]
madvr settings > rendering > general settings
