### ISSUE TITLE
Streaming crash the player

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#770]
Opening this with MPC-HC (using youtube-dl) always crash the player: `https://www.wittytv.it/uomini-e-donne/lunedi-30-novembre/`

Work fine if downloaded directly from youtube-dl (without MPC-HC).

**Comment by clsid2** [comment]
There is a similar issue as described here:
https://stackoverflow.com/questions/3667368/problem-with-window-subclassing-endless-cycle

Happens here with MPCVR, but not with EVR-CP.

The problem seems to be caused by the fact that MPC-HC opens two streams at same time that both contain video. I have not checked why yet, but probably youtube-dl wrongly flagged one of the streams as audio only.

Two instances of MPCVR at same time -> problem.

@Aleksoid1978
Could you have a look at this?  Two instances of the video renderer should ideally not cause problems.

I will check later why this situation happens and try to prevent/fix it.

**Comment by v0lt** [comment]
Please use **MPCVideoRenderer 0.4.10.1479** or newer.

In any case, the problem of two renderers remains. "Basic video renderer" is always added to the graph, even if you specify not to.

**Comment by clsid2** [comment]
I have modified the filter graph manager to use a null video renderer when loading an audio dub. That way it will decode and render audio only. This should fix the problem.

I have also tweaked the stream selection a bit so that streams without any audio/video formats details are ignored.

**Comment by ale5000-git** [comment]
I confirm that it now works correctly.
