### ISSUE TITLE
Color fading with UHD movies!

### ISSUE THREAD

**Issue by karakarga70** [clsid2/mpc-hc#84]
Hello,

I have both 1080 HD and 2160 UHD versions of Star Wars Solo. This one is the most noticeable one, so I have chosen it. When playing both versions, the well known "turquoise" color in the beginning and at the very end, is fading with 2160 UHD playback to "grey" color!

All the movies I open with media player classic being 2160 UHD, the colors are fading, pastelish, dim & low bulb like cinematic effect. 1080 HD version playback is extremely well by means of color tone and balance.

I am a Radio, TV & Film studies graduate, so I am really familiar with color intensity. 

Please check this problem....

**Comment by clsid2** [comment]
For playback of HDR video you need to install and use Madvr as video renderer.

http://forum.doom9.org/showthread.php?t=146228

**Comment by karakarga70** [comment]
I am using Media Player Classic, comes with K-Lite Codec Pack Mega by the way.

**Comment by clsid2** [comment]
Then Madvr is already installed.

MPC-HC options > Playback > Output > Video Renderer

**Comment by karakarga70** [comment]
Yes, the result is like that. I have ticked "madLevelsTweaker.exe" and now I have completely black screen! :)

**Comment by karakarga70** [comment]
Installing MPC-HC.1.8.5.x64.exe now....

**Comment by karakarga70** [comment]
Fine now, I have opened "2001 A Space Odyssey (1968) 4k 2160p UHD Bluray" same dim colors very bad still....

**Comment by clsid2** [comment]
Just follow these EXACT instructions:
MPC-HC options > Playback > Output > Video Renderer > Madvr

**Comment by karakarga70** [comment]
Some tweaks are necessary!

**Comment by karakarga70** [comment]
As you have said, I have found it!

From Media Player Classic Home Cinema screen, 2nd from left, "View" then Options at the bottom. Top right line, DirectShow Video menu. Ticked the menu and chosen madVR.

Colors are very well now. Thank you very much! :)

**Comment by karakarga70** [comment]
Forgotten 2 stages, I am writing down again for others. (may read too)

From Media Player Classic Home Cinema screen, 2nd from left, "View" then Options at the bottom. **In the playback menu, there is Options.** Top right line, DirectShow Video menu. Ticked the menu and chosen madVR.

**Comment by Eno77** [comment]
I a m using the 64 bit standalone/zip version and it seems not to recognize madVR. (I ran the install batch file in Admin mode)
So in order too make madVR work / recognized by mpc-hc, I would have to use the installer?

Is there any way to use madVR with this zip version to get rid of the washed colors / low contrast of HDR material?

**Comment by clsid2** [comment]
It works fine with zip version. If it doesn't recognize madvr it means that madvr was not registered correctly. Do that again and also don't move or delete the madvr64.ax file.

**Comment by Morc001** [comment]
@clsid2 First of all, thank you for developing MPC-HC after the original developer(s) left. Secondly as far as I know I had not had madVR installed, and MPC-HC set to Enhanced Video Renderer (EVR) (custom presenter) could play an HDR video just fine. Why? The video is encoded with HEVC in an MKV container. HDR videos, in terms of colour, look the same using the madVR renderer or EVR. I'm using Windows 10 Home.
@karakarga70 How did you fix the colour? The videos, like you described in the opening post, look pale/dull, undersaturated. I tried the Films & TV Microsoft store app with the Microsoft HEVC codec and colours look the same as with MPC-HC (madVR or otherwise). I noticed that even though both videos I compare are 10bit, but different colour primaries (BT.709 vs BT.2020), so maybe that is causing the difference.

**Comment by clsid2** [comment]
EVR-CP does **not** do HDR tonemapping.

10-bit video isn't necessary HDR.

MediaInfo will show details like this for HDR video:
```
HDR format                  : SMPTE ST 2086, HDR10 compatible
Transfer characteristics    : PQ
Matrix coefficients         : BT.2020 non-constant
Mastering display color pri : Display P3
Mastering display luminance : min: 0.0020 cd/m2, max: 1000 cd/m2
```

**Comment by Morc001** [comment]
These are all the video details, so it seems even through the filename says its HDR it is not?

`Video
ID                             : 1
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5@Main
Codec ID                       : V_MPEGH/ISO/HEVC
Duration                       : 38 min 46 s
Bit rate                       : 2 002 kb/s
Width                          : 3 840 pixels
Height                         : 1 616 pixels
Display aspect ratio           : 2.40:1
Frame rate mode                : Constant
Frame rate                     : 23.976 (24000/1001) FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Bits/(Pixel*Frame)             : 0.013
Stream size                    : 555 MiB (91%)
Default                        : Yes
Forced                         : No
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : PQ
Matrix coefficients            : BT.2020 non-constant`

**Comment by Morc001** [comment]
I downloaded the first sample from here: https://4kmedia.org/ With this file madVR works fine using default settings. With the previous file I had to tell madVR to use tone mapping. Here are the video details:

Video
ID                             : 257 (0x101)
Menu ID                        : 1 (0x1)
Format                         : HEVC
Format/Info                    : High Efficiency Video Coding
Format profile                 : Main 10@L5@High
HDR format                     : SMPTE ST 2086, HDR10 compatible
Codec ID                       : 36
Duration                       : 1 min 12 s
Width                          : 3 840 pixels
Height                         : 2 160 pixels
Display aspect ratio           : 16:9
Frame rate                     : 25.000 FPS
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 10 bits
Writing library                : ATEME Titan KFE 3.7.3 (4.7.3.1003)
Color range                    : Limited
Color primaries                : BT.2020
Transfer characteristics       : PQ
Matrix coefficients            : BT.2020 non-constant
Mastering display color primar : Display P3
Mastering display luminance    : min: 0.0500 cd/m2, max: 1200 cd/m2

**Comment by clsid2** [comment]
First one seems to be missing the HDR metadata.

**Comment by Morc001** [comment]
I just spotted that. How can it be added, with what tool? Do you have a suggestion?

**Comment by clsid2** [comment]
Maybe with this:
https://github.com/youtubehdr/hdr_metadata#ingest-metadata-with-mkvmerge

For more assistance you need to seek help elsewhere.

**Comment by Morc001** [comment]
Thanks! I found this as additional info: http://forum.doom9.org/showthread.php?t=174517 As it turns out I have video files which don't show this "HDR format" tag, yet play fine with default madVR settings.

For others who stumble upon this ticket, madVR has a MPC-HC remote controller called madHcCtrl.exe When started an icon appears in the notification area. Right-click on that and select "Edit madVR Settings" A windows pops up, where under devices open the screen where you want to display the content and click on hdr. If the video stream has the correct tag then "let madVR decide" should work fine, otherwise on 8bit displays select "tone map HDR using pixel shaders" and leave the settings that appear untouched, maybe except "target peak nits" that I guess should be adjusted to the screen's maximum brightness (1 nit = 1 cd/m2) Click OK and restart MPC-HC
