### ISSUE TITLE
Feature request: Favorites menu options/ideas

### ISSUE THREAD

**Issue by wisemike2** [clsid2/mpc-hc#898]
When you have many favorites, the list is so long that you have to scroll all the way to reach what you want.  It would be useful to add:
- Option to make the list show in 2 or 3 columns for instance (like Windows Start Menu) or something.
- An option to search favorites.

Other options could be like:
- Sort list (by name, file size, location, date added.. etc.)
- It could highlight with red for example obsolete (dead) links.
- It would be great if you can add folders to the Favorites menu: One for classics, pop, videos.. etc. Like browser's bookmarks.. 
- There could be a built in menu like the Playlist (ctrl+7) one that opens in the mpc window for the favorites too, for faster access other than the menu.

**Comment by clsid2** [comment]
I am not interested in working on such functionality. So you need to hope more developers join.

**Comment by cw2** [comment]
> * Option to make the list show in 2 or 3 columns for instance (like Windows Start Menu) or something.

This could be added - it would work similarly to Windows Explorer's "List" view, i.e. multiple columns.

> * An option to search favorites.

This also could be added.

> * Sort list (by name, file size, location, date added.. etc.)

Sorting by name and location could be added, because the information is already available. File size and date added is not - I guess date added could be relatively easily added to the favorites data, the file size would need to be the value at the time the favorite was created to avoid potentially expensive file system (possible network) operation.

> * It could highlight with red for example obsolete (dead) links.

Although this could be also done relatively easily, it would definitely need to be done asynchronously (in a background thread) to keep the UI responsive, because checking for possible dead links could be a lengthy operation. Maybe a dedicated "Remove dead links" button would be better (?)

> * It would be great if you can add folders to the Favorites menu: One for classics, pop, videos.. etc. Like browser's bookmarks..

Based on my personal experience, folders are not enough, resp. tags are better and may be even simpler to implement. Not promising anything at the moment, though...

**Comment by clsid2** [comment]
For advanced library and playlist features people should use a specialized audio player.
