### ISSUE TITLE
Play menu Subtitle Track display wrong language for zh_TW.srt and others

### ISSUE THREAD

**Issue by ronkwann** [clsid2/mpc-hc#927]
using Win7 x86 mpc-hc 1.9.9 from clsid2.

as shown below, the four local .srt locale
.zh_HK
.zh_TW
.zh_CHT
.zh_MO
should be displayed as "Chinese (Traditional)" instead.
they use Traditional Chinese in the these regions.

![mpc-hc_bug](https://user-images.githubusercontent.com/69777982/108452883-4c957b80-72a4-11eb-88ce-2d4e3d57e395.jpg)

My MPC-HC Help > About > Copy to clipboard
MPC-HC
------

Build information:
    Version:            1.9.9 (4aa0ed08a)
    Compiler:           MSVC v19.26.28806
    Build date:         Feb  9 2021

LAV Filters:
    LAV Splitter:       0.74.1.92
    LAV Video:          0.74.1.92
    LAV Audio:          0.74.1.92
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1

Hardware:
    CPU:                Intel(R) Core(TM)2 CPU         T7600  @ 2.33GHz
    GPU:                Mobile Intel(R) 945 Express Chipset Family (Microsoft Corporation - WDDM 1.0) (driver version: 8.15.10.1749)

**Comment by lifegpc** [comment]
MPC-HC just use zh to find Language name. (This is ISO639-1

**Comment by ronkwann** [comment]
>  ISO639-1

if this is the case please follow through ISO 639-1 and use "Chinese" but not "Chinese (Simplified)"

**Comment by lifegpc** [comment]
Yea. In the map, Chinese (Simplified) is in front of Chinese (Traditonal).
我之前也提过这个问题。（

**Comment by cw2** [comment]
There is a slight problem with Windows built-in `GetLocaleInfo[Ex]` function that return invalid name for neutral locales. The existing MPC-HC code can be easily extended to handle language names with regions, for example by calling `LocaleNameToLCID` (with LOCALE_ALLOW_NEUTRAL_NAMES flag) and then `GetLocalInfo[Ex]` - but whilst this works fine for most languages with regions (and fixes the examples mentioned above, with the exception of zh_CHS and zh-CHT which are not currently supported), unfortunately it does not correctly handle netural language names, i.e. for 'en' it returns 'English (United States)', which is wrong.

_Technical note: I am talking about LOCALE_SENGLISHDISPLAYNAME vs. LOCALE_SENGLISHLANGUAGENAME; the latter does not include the region at all._

**Comment by clsid2** [comment]
The behavior could depend on whether the input language code has an underscore/dash.
"en" -> get basic language name
"en_CA" -> get extended language name

**Comment by adipose** [comment]
Can you upload the file used in the bug report?

**Comment by adipose** [comment]
![image](https://user-images.githubusercontent.com/3324395/156977926-164144ff-7ead-4e3d-b862-cc9faf343b44.png)

OK, this probably needs testing, but I've made a patch that gets proper lcids, locale names, and localized display names.

https://github.com/clsid2/mpc-hc/pull/1586

**Comment by clsid2** [comment]
Does track selection still work with this patch, now that a full lcid can be returned?

Unrelated to the patch, but I notice that the embedded track has "zh-" as lcid (fault of LAV). I suspect we might not handle that properly in track selection? Could be fixed by stripping the third char to handle it as 2 char iso code.

**Comment by adipose** [comment]
I think it works fine.  To explain the changes, I basically just try to grab the longer langid, if possible, when I find a dash.  At that point I use LocaleNameToLCID to get the LCID, instead of the hard coded mpc-hc table.  And later, when showing the descriptive name, I use GetLocaleInfoEx using the langid instead of the lcid (but this is just text to show in the menu).

So, it will always get an LCID, just like before, and can use this.  I do know that are some possible langids that are assigned "temporary" LCIDs due to LCID being a deprecated concept on Windows.  But even those should work during a given instance.

![image](https://user-images.githubusercontent.com/3324395/157106704-f83059a8-07a4-40da-a0dc-62e01ad6c2e0.png)

![image](https://user-images.githubusercontent.com/3324395/157106601-a405c5fe-e0dd-44d1-a034-c87752cd316a.png)

I did find a "bug," when showing the lang on the status bar, it is using LOCALE_SISO639LANGNAME2, which shows zho for both TW and HK.

![image](https://user-images.githubusercontent.com/3324395/157108278-6957e322-89fa-4804-8820-1ad5816f10a2.png)

Not sure there's a way around that except to start showing the long lang id "zh-TW".

**Comment by adipose** [comment]
![image](https://user-images.githubusercontent.com/3324395/157112464-a8890069-58b0-4887-9080-379afeb82c48.png)

It now can load the locale langids from the lcids.  However, zh-Hans becomes zh-CN, which to my understanding is because they are basically the same thing.  Microsoft must be mapping them both to the same LCID.  Another reason to consider losing LCID entirely.
