### ISSUE TITLE
Question : What's effect "Ignore system channel mixer" ?

### ISSUE THREAD

**Issue by FX8350** [clsid2/mpc-hc#951]
Hi,
I have questions about "Ignore system channel mixer" of MPC's internal audio renderer.
I'm using typical Realtek 7.1ch onboard audio device with 2ch speakers ( or headphone ).
What's effect "Ignore system channel mixer" settings ?

And why does 5.1ch audio sound different in exclusive mode and shared mode ? (regardless of whether "Ignore system channel mixer" is enabled or disabled)
Exclusive mode is probably playing only the rear channels sound to my speakers , shared mode is probably playing the sound mixed correctly to 2ch. ( or just can't hear the rear sound,only front channels. ) 

![audio](https://user-images.githubusercontent.com/10481430/109417993-5be59900-7a09-11eb-975e-c18aa6b50758.png)

**Comment by clsid2** [comment]
Exclusive mode bypasses the Windows sound mixer and the output goes directly to the sound driver. Difference in sound quality is due to processing done by the Windows mixer. Besides channel mixing, it can also apply certain "enhancement" filters.

Control Panel (control.exe) > Sound > Speakers > Properties > Enhancements tab (and Dolby tab)

If you use only Stereo speakers/headphones, then your settings in Windows are wrong because in screenshots it outputs to 6 or 8 channels.
Control Panel (control.exe) > Sound > Speakers > Configure > Stereo

And I also recommend enabling the mixer in the audio decoder:
MPC options > Internal Filters > Audio Decoder > Mixer > Stereo
(set center mix level to 1.0 to increase volume of voices)

**Comment by FX8350** [comment]
Thank you for your response and detailed comments.
Now, I understand how exclusive mode and shared mode work. 
And thank you for telling me about the mixer in the audio decoder. I think it will be very useful.

but now, I changed Windows speaker setting but still MPC-HC are outputting 6/8ch sounds.
It's okay to use the mixer in the audio decoder, but I'd love to provide any necessary information about this problem(?).
![speaker](https://user-images.githubusercontent.com/10481430/109419471-f85f6980-7a10-11eb-87c4-dabb176eaefe.png)

**Comment by clsid2** [comment]
Enable the mixer in the audio decoder.

Disable exclusive mode in the audio renderer.

**Comment by FX8350** [comment]
The mixer in the audio decoder convert it 5.1ch to 2ch, and the audio renderer seems to convert it to 8ch (7.1ch).
Are there any problems?
![Sound](https://user-images.githubusercontent.com/10481430/109419900-22199000-7a13-11eb-9d0e-67cfc50218c4.png)

**Comment by FX8350** [comment]
Oops,Uncheck "Ignore system channel mixer", it was output to 2ch.
