### ISSUE TITLE
Embedded font should not override system font

### ISSUE THREAD

**Issue by KyotoIro** [clsid2/mpc-hc#958]
Hello

When i open a video file mkv, all menu text change in unknown language, by defaut it's french menu. 
I have made the file with MKVToolNix Gui.
![Capture d’écran 2021-03-01 173918](https://user-images.githubusercontent.com/79862241/109528544-1383b500-7ab5-11eb-8c7b-68d84723e649.png)

It's a first time with a made MKV. I've update MPC-HC with the latest (1.9.10)

Thanks for your help.

**Comment by KyotoIro** [comment]
Hello,

I've a problem. If I remade my mkv file without "Segoe UI.ttf" i don't have a menu bug.
[Segoe UI.zip](https://github.com/clsid2/mpc-hc/files/6063119/Segoe.UI.zip)

If you want i can share a video with a bug.

Thanks

![Capture d’écran 2021-03-01 174933](https://user-images.githubusercontent.com/79862241/109529963-7cb7f800-7ab6-11eb-97b2-3411a75b9409.png)

**Comment by clsid2** [comment]
That font is used for the player menu. Maybe using it during playback causes a problem, causing the menu to fallback to another system font.

Yes, please share an example file.

**Comment by KyotoIro** [comment]
Hello

The link for my mkv file with WeTransfert
https://we.tl/t-e8Y78PdIb5

Thanks

**Comment by clsid2** [comment]
There seems to be something wrong with your font file. It is much smaller than the font file on my system. If I remux with the `segoeui.ttf` file from my Windows installation, then the menu bug is gone.

Embedded fonts should not get loaded if that would result in temporarily replacing system fonts. So that is something I will investigate further.

**Comment by KyotoIro** [comment]
ooohhh Sorry!

Yes, i have try with another segoeui.ttf, it's good now! Very sorry.

Thank you for your help.

**Comment by ale5000-git** [comment]
@clsid2
Just an idea (I'm not sure if it works):
If you load the font for the user interface of MPC-HC privately with full path and filename (from `C:\Windows\Fonts\segoeui.ttf`) instead of loading it as installed font maybe it doesn't suffer the same problem.

Look here: https://www.codeproject.com/articles/107377/load-and-use-custom-font-without-installing-it
